{title: Por Toda La Eternidad}
{artist: Warcry}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-es, latin metal, rock en espanol, spanish metal}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 116284
# Empreinte source SHA256: 0d97c88cc7fb40cff5bfac80275e32a2fe1dc362d5224b472db783d6cf178a70
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

Fija su mira[Bm]da,
[D]Allá donde no hay nada...
[A]Perdida en un [G]mundo lejos de a[Bm]quí...

[Bm]Siempre ensimismada...
[D]Sonríe ilusionada...
[G]Parece[Em] ser feli[Bm]z....
Dicen que [G]lo
Conoc[Em]ió años at[Bm]rás...

Él se [G]marchó y[Em] no lo pudo s[F#]uperar...

Coro
[Bm]Decidió detener el tiempo...
Se que[D]dó en el mejor recuerdo...
Y le [G]amó por to[Em]da la eternid[Bm]ad...

[Bm]Decidió detener el tiempo...
Se que[D]dó en el mejor recuerdo...
Y le [G]amó por to[Em]da la eternid[Bm]ad...

[Bm]Los días que está m[G]ejor.. Se [Em]levanta a b[G]ailar... [Bm][G][Em][F#m][G]

[Bm]Decidió detener el tiempo...
Se que[A]dó en el mejor recuerdo...
Y le [G]amó por to[Em]da la eternid[Bm]ad...

[Bm]Murió... En aquel momento...
Romp[D]ió algo en su cerebro...
Sin [G]él, no quer[Em]ía continu[Bm]ar...
Sólo b[Bm]ailar...
Sólo b[D]ailar...

[D]Ohohoh[G]ohohoh[Em]ohhhoh[Bm]ohohoh
[A]Ohohoh[G]ohohoh[Em]ohhhoh[Bm]ohoho[D]h [Bm]
