{title: Danny's Song}
{artist: Kenny Loggins}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, album rock, classic rock, mellow gold, new wave pop, rock, soft rock, yacht rock}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 36188
# Empreinte source SHA256: de65f9e4a5be143c8317669eb5ab42e19a2d85a53394554a3c09a0367ae24f27
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

       PEOPLE SMILE[D] AND TELL, ME I'M[D/C] THE LUCKY ONE ..[Bm].
       AND WE'VE [E7]JUST BEGUN, THINK I'M GONNA [A7]HAVE A SON ...
       [D]HE WILL BE LIKE [D/C]SHE AND ME,  AS [Bm]FREE AS A DOVE ...
       [E7]CONCEIVED IN LOVE, SUN IS GONNA [A]SHINE ABOVE ...

       [G]AND EVEN THOUGH WE A[A]IN'T GOT MONEY...
       [D]I'M [D/C#]SO IN [D/B]LOVE WITH YA, [D/A]HONEY
       [G]AND EVERYTHING WILL [A]BRING A CHAIN OF [D]LOVE[D/C#] ...[D/B][D/A]
       [G]AND IN THE MORNING W[A7]HEN I RISE
       [D]YOU BRING A TEAR OF [D/C]JOY TO MY EYES...
       AND [Bm]TELL ME, [E7]EVERY[A7]THING IS GONNA BE ALRIGHT

       [D]SEEMS AS THOUGH A [D/C]MONTH AGO I WAS [Bm]BETA-CHI...
       [E7]NEVER GOT HIGH, OH, I WAS A [A7]SORRY GUY...
       [D]AND NOW A SMILE AND [D/C]FACE THE GIRL THAT SHA[Bm]RES MY MAME...
       NOW I'M TH[E7]ROUGH WITH THE GAME, THIS BOY WILL NEVER B[A7]E THE SAME...

       (REFRÂO)

       [D]PISCES,  VIRGO [D/C]RISING IS A [Bm]VERY GOOD SIGN...
       [E7]STRONG AND KIND, AND THE LITTLE [A7]BOY IS MINE...
       [D]NOW I SEE A [D/C]FAMILY WHERE THERE O[Bm]NCE WAS NONE...
       NOW WE'VE [E7]JUST BEGUN, YEAH WE'RE GONNA [A7]FLY TO THE SON...

       (REFRÂO)

       [D]LOVE THE GIRL WHO [D/C]HOLDS THE WORLD IN A [Bm]PAPER CUP...
       [E7]DRINK IT UP, LOVE HER AND SHE'LL[A7] BRING YOU LUCK...
       AND [D]IF YOU FIND SHE [D/C]HELPS YOUR MIND, BETTER [Bm]TAKE HER HOME...
       DON'T YOU L[E7]IVE ALONE, TRY TO EARN WHAT [A7]LOVERS OWN...

       (REFRÂO)
