{title: Il Regalo Più Grande}
{artist: Tiziano Ferro}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, italian adult pop, italian pop}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 47169
# Empreinte source SHA256: 7a5b16e7ded5a606faa935b9e618ea68a67cf36a215da0c922ddc366aa9fe854
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

            Accordi e testo Il regalo più grande Rev anti # :D

[A]VOGLIO FARTI UN REGALO

QUALCOSA DI DOLCE QUALCOSA DI RARO EH EH EH EH EH

[D9]NON UN COMUNE REGALO DI QUELLI CHE HAI PERSO

[A]MAI APERTO O LASCIATO IN TRENO

[E]O MAI ACCETTATO EH EH EH EH EH

[Bm7]DI QUELLI CHE APRI E POI PIANGI

[E]CHE SEI CONTENTA E NON FINGI

[Bm7]IN QUESTO GIORNO DI META' SETTEMBRE

[E]TI DEDICHERO' IL REGALO MIO PIU' GRANDE

[A]VORREI DONARE IL TUO SORRISO ALLA LUNA PERCHE'

DI NOTTE CHI LA GUARDA POSSA PENSARE A TE

PER RICORDARTI CHE IL MIO AMORE

[E]E' IMPORTANTE CHE NON IMPORTA CIO'

[Bm7]CHE DICE LA GENTE PERCHE' TU MI HAI PROTETTO

CON LA TUA GELOSIA CHE ANCHE

[E]CHE MOLTO STANCO IL TUO SORRISO

[Bm7]NON ANDAVA VIA DEVO PARTIRE PERO' SO NEL CUORE

[E]LA[A] TUA PRESENZA E' SEMPRE ARRIVO E MAI PARTENZA

[F#m7]IL REGALO MIO PIU' GRANDE

[D]IL REGALO MIO PIU' GRANDE EH EH EH EH EH EH EH EH

[A9]VORREI MI FACESSI UN REGALO

[D9]UN [A6]SOG[E]NO INESPRESSO DONARMELO ADESSO EH EH EH EH EH

[Bm7]DI QUELLI CHE NON SO APRIRE

[E]DI FRONTE AD ALTRA GENTE

[Bm7]PERC[E]HE' IL REGALO PIU' GRANDE OH...

E' SOLO NOSTRO PER SEMPRE

[A]VORREI DONARE IL TUO SORRISO

ALLA LUNA PERCHE' DI NOTTE CHI LA GUARDA

POSSA PENSARE A TE PER RICORDARTI CHE IL MIO AMORE

[E]E' IMPORTANTE CHE NON IMPORTA

CIO' CHE DICE LA GENTE PERCHE'

[Bm7]TU MI HAI PROTETTO CON LA TUA GELOSIA CHE ANCHE

[E]CHE MOLTO STANCO IL TUO SORRISO

[Bm7]NON ANDAVA VIA DEVO PARTIRE PERO' SO NEL CUORE

[E]LA TUA PRESENZA E' SEMPRE ARRIVO E MAI

[A]E SE ARRIVASSE ORA LA FINE CHE SIA IN UN BURRONE

[F#m7]NON PER VOLERMI ODIARE SOLO PER VOLER VOLARE

[D6]E SE TI NEGA TUTTO QUEST'ESTREMA AGONIA

[A]E SE TI NEGA ANCHE LA VITA

RESPIRA LA MIA E STAVO ATTENTO A NON AMARE

[A6]PRIMA DI INCONTRARTI E CONFONDEVO LA MIA VITA CON QUELLA DEGLI ALTRI

[D]NO[A]N VOGLIO FARMI PIU' DEL MALE ADESSO L'AMORE...AMORE...

[A#]VORREI DONARE IL TUO SORRISO

[A#6]ALLA LUNA PERCHE' DI NOTTE CHI LA GUARDA

[D#6]POSSA PENSARE A TE PER RICORDARTI CHE IL MIO AMORE

[A#]E' IMPORTANTE CHE NON IMPORTA CIO' CHE DICE LA GENTE E POI

L'AMORE DATO AMORE PRESO AMORE MAI RESO

[A#6]AMORE GRANDE COME IL TEMPO

[D#]CHE NON SI E' ARRESO AMORE CHE MI PARLA COI TUOI OCCHI

[Fsus4]QUI DI FRONTE SEI TU SEI TU SEI TU SEI TU

SEI TU SEI TU SEI TU SEI TU AH IL REGALO MIO PIU' GRANDE
