{title: Dormir contigo}
{artist: Luis Miguel}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, bolero, latin, latin pop}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 5580
# Empreinte source SHA256: e790e46f47931b0b4f4d6bc26732effaee4b7f7934a6ff27670511a36ad297ad
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

DORMIR CONTIG[D]O,ES EL CAMIN[F#m]O MAS DIREC[Bm]TO AL PARAI[Em]SO, [G][A]
SENTIR QUE [F#m]SUEÑAS,MIENTRAS TE [D]BESO Y LAS M[Bm]ANOS TE ACA[Em]RICIO.[G]...[A].
DORMIR CON[G]TIGO,ES NAVE[Gm]GAR EN UNA EST[Em]RELLA HASTA EL E[F#m]SPAC[D]IO..
ES EMBRIA[Bm]GARME,
CON EL SUS[G]URRO DE TU HA[Gm]BLAR TIERNO Y D[Em]ESPAC[A]IO.............
DORMIR CON[D]TIGO,ES CON[F#m]OCER LA DIMEN[Bm]SION QUE TIENE UN[Em] VER[G]SO[A]....
SENTIR QUE D[F#m]UERMO,Y AL MISMO T[D]IEMPO CON[Bm]OCER EL UN[Em]IVERS[G]O.[A]......
DORMIR CON[G]TIGO,CON TU CA[Gm]BELLO ACOM[Em]ODADO AQUI EN MIS [F#m]BRAZO[D]S
Y EL TERCIO[Bm]PELO QUE ME BRINDA TU RE[G]GAZO.......
QUE MARA[Em]VILLA........DORMIR CON[A]TI[F#m]GO...[D7]..........
DORMIR CON[G]TIGO,CON LA ILU[Gm]SION DE QUE DES[Em]PERTARE M[F#m]AÑANA[D]......
CON EL CA[Bm]LOR DE UN NUEVO  DIA EN LA VE[G]NTANA.........
FUE ALGO HER[Em]MOSO AM[A]OR............DORMIR CO[D]NTIGO...........
DORMIR CON[G]TIGO,CON TU CA[Gm]BELLO ACOM[Em]ODADO AQUI EN MIS[F#m] BRAZO[D]S
Y EL TERCI[B]OPELO QUE ME BRINDA TU RE[G]GAZO...........
QUE MARA[Em]VILLA..[A]........DORMIR CON[F#m]TIGO...[D7]................
DORMIR CON[G]TIGO,CON LA ILU[Gm]SION DE QUE DE[Em]SPERTARE M[F#m]AÑANA[D]
CON EL CA[Bm]LOR DE UN NUEVO DIA EN LA VEN[G]TANA..........
FUE ALGO HER[Em]MOSO AM[A]OR............DORMIR CON[D]TIGO...........
