{title: Disease (Keyboard version)}
{artist: Matchbox Twenty}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, neo mellow, pop rock, post-grunge}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 34602
# Empreinte source SHA256: 3204018f1211c18936f547842e473882f3b7f2137771b82d9dd235083b5d67f6
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : INTRO = F#m C#7/F F#m C#7/F}
# SOURCE A VERIFIER:             INTRO = F#m  C#7/F F#m C#7/F 

FEELS LIKE YO[F#m]U MADE [C#7/F]A MISTAKE
YOU MADE SOMEB[F#m]ODY'S H[C#7/F]EART BREAK
BUT NOW I HAVE TO[Bm] LET [D]YOU GO
I HAVE TO [F#m]LET Y[C#7/F]OU GO

YOU LEFT A ST[F#m]AIN  [C#7/F]
ON EVERY ONE O[F#m]F MY G[C#7/F]OOD DAYS
BUT I AM STRONGER [Bm]THAN [D]YOU KNOW
I HAVE TO [F#m]LET Y[C#7/F]OU GO

NO ONE'S EVER T[D]URNED YOU OVER
[E]NO ONE'S TRIED
TO E[F#m]VER LET YOU D[Bm]OWN
BEAUTI[D]FUL GIRL-BLE[C#7]SS YOUR HEART

I GOT A [F#m]DISEASE

DEEP INSIDE ME
MA[Bm]KES ME FEEL UNEASY, BABY
[C#7]I CAN'T LIVE WITHOUT YOU, TELL ME
[F#m]WHAT AM I S'POSED TO DO ABOUT IT
[F#m]KEEP YOUR DISTANCE FROM IT
[Bm]DON'T PAY NO ATTENTION TO[C#7] ME
I GOT A[F#m] DISEAS[C#7/F]E

FEELS LIKE YOU'RE MA[F#m]KING A [C#7/F]MESS
YOU'RE HELL ON WHEEL[F#m]S IN A BLACK[C#7/F] DRESS
YOU DROVE ME [Bm]TO THE[D] FIRE
AND LEFT ME T[F#m]HERE T[C#7/F]O BURN

EVERY LI[D]TTLE THI[E]NG YOU DO IS TRAGIC
ALL [F#m]MY LIFE BEFO[Bm]RE WAS MAGIC
BEAUTIFU[D]L GIRL-I[C#7/F] CAN'T BREATHE

I GOT A [F#m]DISEASE

DEEP INSIDE ME
[Bm]MAKES ME FEEL UNEASY, BABY
[C#7]I CAN'T LIVE WITHOUT YOU, TELL ME
[Bm]WHAT AM I S'POSED TO DO ABOUT IT
[F#m]KEEP YOUR DISTANCE FROM IT
[Bm]DON'T PAY NO ATTENTION TO[C#7] ME
I GOT A DIS[F#m]EASE

YEAH, WELL I THINK THAT I'M [F#m]SICK

BUT LEAVE ME BE
WHILE[Bm] MY WORLD IS COMING DOWN ON ME
[C#7]YOU TASTE LIKE HONEY, HONEY
[F#m]TELL ME CAN I BE YOUR HONEY BEE

BE STRONG
KEEP T[Bm]ELLING MYSELF
THAT IT WON'[C#7]T TAKE LONG 'TILL
I'M FREE[Bm] OF MY DISEASE
I'M FREE[F#m] OF MY DISEASE
I'M FREE[Bm] OF MY DISEASE
OH, OOWW [C#7]

I GOT A [F#m]DISEASE

DEEP INSIDE ME
MAKES[Bm] ME FEEL UNEASY, BABY
[C#7]I CAN'T LIVE WITHOUT YOU, TELL ME
[F#m]WHAT AM I S'POSED TO DO ABOUT IT
[F#m]KEEP YOUR DISTANCE FROM IT
[Bm]DON'T PAY NO ATTENTION TO [C#7]ME
I GOT A DIS[F#m]EASE

YEAH, WELL I THINK THAT I'M [F#m]SICK

BUT LEAVE ME BE
WHILE[Bm] MY WORLD IS COMING DOWN ON ME
[C#7]YOU TASTE LIKE HONEY, HONEY
TELL[F#m] ME CAN I BE YOUR HONEY[F#m]BEE

BE STRONG
KEEP T[Bm]ELLING MYSELF
THAT IT WON'[C#7]T TAKE LONG 'TILL
I'M FREE [F#m]OF MY [C#m5]DISEASE

FREE OF [F#m]MY DIS[C#m5]EASE
SET ME F[F#m]REE OF[C#m5] MY DISEASE
OH , OOW[F#m]W... [C#m5]
[C#m5] [F#m]
