{title: Mi Mandi Rose}
{artist: Mina}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, classic italian pop, italian adult pop, ye ye}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 80820
# Empreinte source SHA256: 163308062415800ebe68fb10974983f38076c32090951d391d59dab79848db55
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tonalite_absente

[Am]COME MAI MI MANDI ROSE[Dm]
CERTE COSE[E] LE FAI TU[Am]
MI AMI GI[A]A MALEDIZIO[Dm]NE
LA TESTA MI VA IN CONFUSIONE[E]
E CONDUSIONE PER CHI[Am]
DI TANTO IN TANTO TI VORREI[Dm]
MA SACRIFICIO TRISTEZZA[E] TU SE[Am]I
MA ACCANTO A TE[Dm] MI UBRIACHERO CANTANDO[Am]
SEI COME UN SAMBA SUL MIO CUORE ORMA[Dm]I
BALLI TI SCATENI E N[E]ON LA SMETTI MA[Am]I
MI MANDI ROSE E POI[Dm]

CHE STRANA BESTIA E QUESTO SENTIMENTO[Am]
A VOLTE NO NON BASTA UN TRADIMENTO MA[Dm]
SOLO UN GESTO CHE[E] MI SAZI UN PO[Am]
MI MANDI ROSE E POI[Dm]

CHE STRANA BESTIA E QUESTO SENTIMENTO[Am]
A VOLTE NO NON BASTA UN TRADIMENTO MA[Dm]
SOLO UN GESTO CHE [E]MI SAZI UN PO[Am]   [E]
MA TU CHI SEI[Am] L UOMO CHE POSA[Dm]
O QUALCOSA[E] FORSE UN SI[Am]
FAI CON M[A7]E L INNAMORA[Dm]TO

MI DICI CHE SEI DISPERATO[E]
E C[E7]HE SEI PAZZO DI ME [Am]
DI TANTO IN TANTO TI VORREI[Dm]
MA SACRIFICIO TRISTEZZ[E]A TU S[Am]EI
ACCANTO A TE[Dm] MI UBRIACHERO CANTANDO[Am]
SEI COME UN SAMBA SUL MIO CUORE ORMAI[Dm]
BALLI TI SCATENI [E7]E NON LA SMETTI MAI[Am]

MI MANDI ROSE E POI[Dm]
CHE STRANA BESTIA E QUESTO SENTIMENTO[Am]
A VOLTE NO NON BASTA UN TRADIMENTO MA[Dm]
SOLO UN GESTO CHE[E7] MI SAZI UN P[Am]O
MI MANDI ROSE E POI[Dm]
CHE STRANA BESTIA E QUESTO SENTIMENTO[Am]
A VOLTE NO NON BASTA UN TRADIMENTO MA[Dm]

SOLO UN GESTO CH[E7]E MI SAZI UN PO[Am]

[Dm7] [Dm] [Am9] [Em] [F] [E] [Am]

MI MANDI ROSE E POI[Dm]
CHE STRANA BESTIA E QUESTO SENTIMENTO[Am]
A VOLTE NO NON BASTA UN TRADIMENTO MA[Dm]
SOLO UN GESTO C[E]HE MI SAZI UN P[Am]O. [E][Am]
