{title: Papo de esquina}
{artist: Roberto Carlos}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, jovem guarda, mpb}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 131684
# Empreinte source SHA256: 16b7dfbc8ad5dda781bdf8bf8ca02fd22eb9cdb966ff94f8c327f43f416eb69b
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : Intro. E7}
# SOURCE A VERIFIER:             Intro. E7 

[E7]QUE BOM TE VER AQUI COM ESSA CARA DE CONTENTE
FAZ T[A]EMPO QUE EU NAO VEJO VOC[E7]E

A MESMA IMPRESSAO EU TENHO DO AMIGO
SORR[A]INDO PRA TUDO QUE [E7]VE
QUEM V[A]IVE SORRINDO ASSIM DESSE JEITO
SO PODE MESMO SER POR AM[E7]OR
VAI AD[A]IVINHAR NO MATO MEU GRANDE BARATO
PARECE QUE ALGUEM TE CONT[E7]OU

NUM DIA DE CHUVA QUE COISA MAIS LINDA
ELA T[A]AVA ESPERANDO O SIN[E7]AL

NUN DIA DE SOL ME SORRIU TAO BONITA
E EU PUXE[A]I UM ASSUNTO BAN[E7]AL
JOGU[A]EI MEU CASACO PRA QUE ELA PISASSE
E ELA ME DEU NOTA D[E7]EZ
A M[A]INHA ESTAVA ENXUTA DE FATO
MAS NAO TAO SOMENTE NOS P[E7]ES
[B7]TODA RAZAO DESSA FELICIDADE
E UMA G[A]ATA CHOCANTE QUE EU CONHECI NA CID[E7]ADE

NA SEGUNDA-FEIRA DE SHORT AMARELO
ELA T[A]AVA O QUE NAO TA NO GIB[E7]I

A MINHA NA TERCA SOBRAVA NO SHORT
SE E[A]RA AMARELO EU NEM [E7]VI
NA QU[A]ARTA E NA SEXTA NUM BEIJO ME DISSE
QUE TAVA GOSTANDO DE M[E7]IM
QUE C[A]OISA ENGRACADA NA QUINTA E NO SABADO
COMIGO TAMBEM FOI ASSI[E7]M

ELA GOSTA DAS FLORES QUE EU MANDO
E O CARTAO QUE EU ESCR[A]EVO SORRI QUANDO L[E7]E

A MINHA USA FLOR NO CABELO
SERA QUE ESSA FL[A]OR NAO E DO MESMO BOUQU[E7]ET
ELA CU[A]IDA DO CORPO, ELA CORRE NA PRAIA
ELA ADORA SAIR PRA DANC[E7]AR
NAO S[A]EI SE ME EXPLICO MAS TUDO DA MINHA

O AMIGO ACABOU DE FALAR
[B7]TODA RAZAO DESSA FELICIDADE
E UMA G[A]ATA CHOCANTE QUE EU CONHECI NA CIDA[E7]DE
CONTA MA[A]IS, QUERO SAB[E7]ER O [B7]QUE VOCE TEM PRA ME DIZ[E7]ER
CONTA MA[A]IS O QUE QUIS[E7]ER, Q[B7]UERO SABER
MAIS DESSA MULH[E7]ER, [A] [E7][B7][A][E7]

VOCE NAO TA ACHANDO

MAS E CLARO QUE EU ESTOU SAO HISTORIAS PARECIDAS DEMAIS

ME DIZ COMO ELA E, SERA QUE E A MESMA

DE REPENTE ATE SAO DUAS IGUAIS
A M[A]INHA E A MORENA QUE ALI JA VEM CHEGANDO
COM OUTRA MORENA TAM[E7]BEM
A O[A]UTRA E A MINHA, AS DUAS SAO LINDAS
AMIGO, ENTAO TA TUDO B[E7]EM
QUE B[B7]OM QUE A RAZAO DESSA FELICIDADE
SAO DU[A]AS MORENAS QUE A GENTE ENCONTROU NA CIDA[E7]DE
CONTA MA[A]IS, QUERO SA[E7]BER O[B7] QUE VOCE TEM PRA ME DIZ[E7]ER
CONTA MA[A]IS O QUE QUI[E7]SER, [B7]QUERO SABER MAIS DESSA MU[E7]LHER[A]  [E7][B7][A][E7]
