{title: Tontos e Loucos}
{artist: Aviões do Forró}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, forro, pagode, sertanejo, sertanejo universitario}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 87780
# Empreinte source SHA256: 16f62cc998a35f3e472f0bb3a57cd3bdb466ee25fb5393379e22eb2267015c22
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

O tempo nunc[C#m]a fez, eu te esquecer [B]
[F#m]Não apagaram as marcas desse a[C#m]mor
Ainda si[A]nto o sabor do teu beijo em minha [B]boca
Ainda s[E]into tua mão,
acariciando a minha [C#m]pele...
E eu não [A]quero seg[B]uir ass[C#m]im...
[A]Estando com e[B]la e pensando em [C#m]ti...
Co[A]migo aconteceu igu[B]al...
Não d[E]eixo de pensar em [C#m]ti...
Tem [A]dias que acordo, contigo na ca[B]beça...
[E]Chamando o teu no[C#m]me...
E eu não [A]quero segu[B]ir assi[C#m]m...
[A]Estando com e[B]la e pensando em t[C#m]i...
[C#m]Que tontos, que loucos que somos nós [B]dois
Estando com o[A]utro e nos aman[C#m]do...
