{title: O Meri Jaan}
{artist: KK}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-so, desi pop, filmi, modern bollywood, sufi}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 35606
# Empreinte source SHA256: ac5610d13f7310780a9782975dd2f8b858052ceea27747a2df6707df9be74989
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tonalite_absente

D[Ab]il khudgarz h[Fm]ai
fislaa hai ye[Bbm]...
phir haath se[Eb]...
k[Ab]al.. uska rah[Fm]a...
ab hai tera[Bbm]..
iss raat se[Eb]...
D[Ab]il khudgarz h[Fm]ai
fislaa hai ye[Bbm]...
fir haath se.[Eb]..
k[Ab]al.. uska rah[Fm]a...
ab hai tera.[Bbm].
iss raat se.[Eb]..
o meri ja[Ab]an.. uu[Eb]uu... u[C#]uuu...
o meri ja[Ab]an.. uu[Eb]uu... u[C#]uuu...
o[Eb] meri ja[C#]an...[Ab]...

T[Ab]u aa gaya yu[Fm]n nazar mein
j[Bbm]aise subah d[Eb]opahar mein.. madhoshi....
y[Ab]uhinn nahi d[Fm]il pe chahi
n[Bbm]iyat ne li a[Eb]ngdai..chhua tune..[Ab].
k[Ab]uch iss tara[Fm]h...
b[C#]adli fizah badla sa[Eb]mah...
o meri j[Ab]aan .. u[Eb]uuu... u[C#]uuu...
o meri j[Ab]aan .. u[Eb]uuu... u[C#]uuu...
o[Eb] meri ja[C#]an ..[Ab]....

n[Fm]aadan samjhe naa haan ye d[Eb]il mera
j[Fm]aanu naa jaanu naa isko ky[Eb]a hua
teri baa[F#]hon ki phir se dhundhe ye[C#] panah
tu hai kah[Ab]aan ...
tu hai kah[Eb]aan ...
o meri ja[Ab]an .. u[Eb]uuu... u[C#]uuu...
o meri ja[Ab]an .. u[Eb]uuu... u[C#]uuu...
o[Eb] meri jaa[C#]n ...[Ab]....
