{title: Huracán}
{artist: Abel Pintos}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, argentine rock, argentine telepop, folklore argentino, pop argentino}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 34326
# Empreinte source SHA256: d414a8dc2655ebde097114dbf835f43a83703a49c0e9e85aceef80567430b4ce
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

            8_HURACAN (HUAYNO CON AIRES DE MURGA)
LETRA:ABEL PINTOS
MUSICA:ABEL PINTOS, ARIEL PINTOS, ANGEL GONZALEZ

(PRIMERA ESTROFA, VA SIN GUITARRA Y CON ACOMPAÑAMIENTO DE REDOBLANTES)

LA LUNA LLORA, EL SOL SIN LUZ
LA TIERRA A PUNTO DE ABRIRSE EN DOS
LAS AVES MUEREN SOBRE EL MAR
Y EL MAR NO AGUANTA SU DOLOR

[Bm]LA GENTE CORRE[G] SIN [F#7]PENSAR
[Bm]Y EL HURACAN N[G]O DA [F#7]PERDON
[Bm]ENTRE LOS HOMBRES[G] YA NO H[F#7]AY PAZ
[Bm]EL MUNDO ES UNO Y[G] SE C[F#7]ANSO

[Bm]PERO YO TE TENGO [A]AMOR
[Bm]EN LA GUERRA Y EL D[A]OLOR
YA NO [Bm]SE QUE VA A P[A]ASAR
[Bm]PERO YO SEGUIRE CON[A] VOS, [F#7]HASTA E[Bm]L FINAL

[Bm]AUNQUE LA TIERRA SE [G]ABRA [F#7]POR LA MITAD
[Bm](SEGUIMOS SOBREV[G]IVIENDO [F#7]AL HURACAN)
SIN SOL NI LUNAS BRILLANDO EN LA OSCURIDAD
(SEGUIMOS SOBREVIVIENDO AL HURACAN)

LAS RUINAS ARDEN EN SOLEDAD
Y NADIE BAJA DE LA CRUZ
TODOS BEBIERON DE SU LUZ
Y AHORA NADIE LO VA A CARGAR

EL CIELO YA COMENZO A LASTIMAR
Y EN UNA ROCA LLORA DIOS
LOS NIÑOS MUEREN POR EL PAN
Y EL MAR NO AGUANTA SU DOLOR

PERO YO TE TENGO AMOR
EN LA GUERRA Y EL DOLOR
YA NO SE QUE VA A PASAR
PERO YO SEGUIRE CON VOS, HASTA EL FINAL

AUNQUE LA TIERRA SE ABRA POR LA MITAD
(SEGUIMOS SOBREVIVIENDO AL HURACAN)
SIN SOL NI LUNAS BRILLANDO EN LA OSCURIDAD
(SEGUIMOS SOBREVIVIENDO AL HURACAN)
AUNQUE NOS REINEN LA MUERTE Y LA SOLEDAD
(SEGUIMOS SOBREVIVIENDO AL HURACAN)
SOMOS LAS ALMAS ERRANTES QUE QUEDARAN
(SEGUIMOS SOBREVIVIENDO AL HURACAN)
SOMOS LAS ALMAS ERRANTES QUE QUEDARAN
(SEGUIMOS SOBREVIVIENDO AL HURACAN)
