{title: Lifesong(ver. 2)}
{artist: Casting Crowns}
{capo: 1}
{x_source_capo: 1}
{x_chord_convention: concert; formes source transposees du capo}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, ccm, christian alternative rock, christian music, world worship, worship}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 41417
# Empreinte source SHA256: 05a944f24728ede866bb4fff660af3aec726ecbb2bad684abb7daded3dd15e8f
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: capo_source_interprete_formes, tonalite_absente

{start_of_part: Intro}
[Db] [Bbm] [Ab] [Gb]

{end_of_part}
{start_of_verse: Verse}
Empty hands held h[Db]igh...
Such small sa[Bbm]crifice...
If not joined with m[Gb]y life...
I sing in va[Eb]in toni[Ab]ght...

{end_of_verse}
{start_of_part: Pre-Chorus}
May the words I s[Db]ay...
And the things I [Bbm]do...
Make my lifeso[Eb]ng si[Ab]ng...
Bring a smile to Y[Gb]ou...

{end_of_part}
{start_of_chorus: Chorus}
Let my l[Db]ifesong sing to Y[Ab]ou...
Let my l[Bbm]ifesong sing to Y[Gb]ou...

I wanna s[Gb]ign Your name...
To the e[Ab]nd of this day...

Kn[Bbm]owing that my heart was [Gb]true...

Let my li[Eb]fesong si[Ab]ng to Y[Db]ou...

{end_of_chorus}
{start_of_verse: Verse 2}
Lord, I give my l[Db]ife...
A living sac[Bbm]rifice...
To reach a world in n[Gb]eed...
To be Your hands and f[Eb]eet[Ab]...

{end_of_verse}
{start_of_part: Pre-Chorus}
May the words I s[Db]ay...
And the things I [Bbm]do...
Make my lifeso[Eb]ng si[Ab]ng...
Bring a smile to Y[Gb]ou...

{end_of_part}
{start_of_chorus: Chorus}
Let my l[Db]ifesong sing to Y[Ab]ou...
Let my l[Bbm]ifesong sing to Y[Gb]ou...

I wanna s[Gb]ign Your name...
To the e[Ab]nd of this day...

Kn[Bbm]owing that my heart was [Gb]true...

Let my li[Eb]fesong si[Ab]ng to Y[Db]ou...

{end_of_chorus}
{start_of_bridge: Bridge 2 (x3)}
[Gb]Halleluj[Db]ah...
[Bbm]Halleluj[Ab]ah...
[Gb]Let my life[Db]song sing to Y[Ab]ou...

{end_of_bridge}
{start_of_chorus: Chorus (2x)}

{end_of_chorus}
