{title: Barbarella}
{artist: Stone Temple Pilots}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, alternative metal, alternative rock, grunge, hard rock, nu metal, pop rock, post-grunge, rock}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 36526
# Empreinte source SHA256: f413f1c102584cf8b5da498d944702b5e210ea9aa371541e3e5a2e9c636d644e
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : (intro) Cm G}
# SOURCE A VERIFIER:             (intro) Cm  G 

(verso)
[G]You play the game...
Let's go, let god...
And all the tangerines...
[Em]You run the race...
...not in yours or yours.
[C]You sing the pink...
Don't know just who...
[D]I'll stay at home...
I'm the meat of the...
[G]So high that I...
More deep than space numbe[Em]r 9...
[C]She's so ready...
[D]Can't hold time by...

[G]Barbarella come and save me...
[Em]Can't you see it's a disease
[C]Shoot the bad guys...
[D]Lost in space...

(ponte)
[A]Na na na na
[D]Na na na na

[C] [C] [D] [C] [G]
