{title: Parado En La Sentina}
{artist: Luis Alberto Spinetta}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-es, argentine indie, argentine rock, latin alternative, latin rock, post-punk argentina, rock en espanol, rock nacional}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 72737
# Empreinte source SHA256: 3dae444462738dbb95612b621aace3226f897492f7497fc02a83ac3e477a450a
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

Quiero llega[D]r y ya no solo caer... [Em7]
entre las ira[A]s de Dios
y la maldad [D]de tantos hombr[Cmaj7]es... [D]
[Cmaj7]gente sin [D]luz...

Alguien me hirió, y algo más me hirió,
y luego otro también...
y me quedé super-herido...
nadie más me oyó...

[Bm7/9/11]!Llámenme! que alguien pregunte [Gmaj7/6]por mí...
[F#m7/11]la fiebre es tan [Em7]alta...
[F#m7/11]la tierra es tan [Em7]inmensa...
{comment: À vérifier : F#m7/11 Dmaj7* C7/9(sin 5) Bm7/9/11}
# SOURCE A VERIFIER: F#m7/11          Dmaj7*             C7/9(sin 5)   Bm7/9/11 
no tengo ya nin   -   gún   -   -   lu   -   -   -  gar...
{comment: À vérifier : Dmaj7* C7/9(sin 5) Bm7/9/11 Em7 A}
# SOURCE A VERIFIER: Dmaj7*         C7/9(sin 5)       Bm7/9/11       Em7     A 
don   -   -   -  de  -  es  -  -   tar...

Y si alguien me ve y no consigo llegar
mi corazón morirá, caerá deshecho en la negrura...
del sin-mirar...

Debo llegar, tan sólo debo llegar...
partir...

Debo llegar hacia las manos de alguien
que sepa de mi alma...
que sepa en mi alma...
que sepa que ya no está en mí...
no, no, no, no está...

Creo en la luz, es como un busca-huellas...
no desesperes amor...estoy parado en la sentina...
ya sin mirar...
------------------------------------------------------------------------
