{title: Tu Juguetito}
{artist: Aventura}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, bachata, bachata dominicana, latin, latin hip hop, latin pop, trap latino, tropical}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 15605
# Empreinte source SHA256: 3dea89205f67d170ae4e66fb0cf5229e851e95c2e67cd9b4f60b11cd0d679f55
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : ....Intro... Em G D C x2}
# SOURCE A VERIFIER:             ....Intro... Em G D C   x2 

Y HOY REGRESAS A[G]QUÍ
CON EL SINDROME DE VICTIMA CON L[D]LANTO
ENSAYASTES A PERFECCION ESTE T[Em]EATRO
P[C]ERMITEME REIRME, QUE GRAC[D]IOSO TE QUEDA EL SHOW

PERO NIÑA POR D[G]IOS,
NO PRETENDAS SOMETERME A TU CH[D]ANTAJE
DONDE TU PSICOLOGIA ME HACE EL CU[Em]LPABLE
[C]LEVANTATE DEL SUELO, QUE L[D]LORANDO TE VES FATAL?

Y [Em]NO?
Y NO TOL[C]ERO UNA INFIDELIDAD ABSURDA
SINONIMO DE TRA[D]ICION
NO [Em]NO...!
YA MAT[C]ASTES CON TU VERBO DE TESTIGO
AQUELLA HISTORIA QUE UNA VES A[D]QUÍ EXISTIOOO
YA ESTE A[C]MOOOOOR? [Em][D]

[Em]EMPEZO LA TRAIC[G]ION, CONTAGIO LA ILUC[D]ION
YA NO HAY MEDICAC[C]ION, QUE DESAGA EL TUM[Em]OR
QUE NACIO EN MI INTER[G]IOR, Y POR MI CONDIC[D]ION
LE QUEDAN MESES DE V[C]IDA AMI CORAZ[Em]ON
SUBE Y BAJA EL TEL[G]ON, REPETITIVA ACTUACI[D]ON
CON TUS LA GRIMAS F[C]ALSAS, PIDIENDO PERD[Em]ON
PERO YA TÉRMIN[G]O, TU JUEGUITO ACAB[D]O
DILE ADIOS AMI AM[C]OR?

Y AHORA APLUSOS PORFAV[G]OR
DENLE UN OSCAR A LA MEJOR ACTRIZ DEL [D]AÑO
POR LAS ESCENAS TAN DRAMATICAS Y EN[Em]GAÑOS
SI N[C]O ES UNA MOLESTIA, UN AUT[D]OGRAFO EN PAPEL?

Y [Em]NO?
Y NO TOL[C]ERO UNA INFIDELIDAD ABSURDA
SINONIMO DE TRA[D]ICION
NO [Em]NO?!
YA MAT[C]ASTES CON TU VERBO DE TESTIGO
AQUELLA HISTORIA QUE UNA VES A[D]QUÍ EXISTIOOO
YA ESTE A[C]MOOOOOR? [Em][D]

[Em]EMPEZO LA TRAIC[G]ION, CONTAGIO LA ILUC[D]ION
YA NO HAY MEDICAC[C]ION, QUE DESAGA EL TUM[Em]OR
QUE NACIO EN MI INTER[G]IOR, Y POR MI CONDIC[D]ION
LE QUEDAN MESES DE V[C]IDA AMI CORAZ[Em]ON
SUBE Y BAJA EL TEL[G]ON, REPETITIVA ACTUACI[D]ON
CON TUS LA GRIMAS F[C]ALSAS, PIDIENDO PERD[Em]ON
PERO YA TÉRMIN[G]O, TU JUEGUITO ACAB[D]O
DILE ADIOS AMI AM[C]OR?
