{title: Meu Oceano}
{artist: Grupo Revelação}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, pagode}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 133079
# Empreinte source SHA256: 09c16938ba78c6c4c1957683777dc8128e5c3059013505f5acd7affc40ce41e9
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : Introdução: A C#m Dm E7}
# SOURCE A VERIFIER:             Introdução:  A C#m  Dm  E7 

[A]Eu não consigo te esque[E]cer......[F#m]e essa dor não que[E]r passar.....
{comment: À vérifier : Dm G7 C7+ Aº Bm E7}
# SOURCE A VERIFIER: Dm       G7         C7+                      Aº                    Bm    E7
Nada mais me dá prazer ...você marcou meu viver....com o seu jeito de amar....
[A7+]Nessa paixão tudo apost[E]ei........[F#m]e agora eu só sei son[E]har......
{comment: À vérifier : Dm G7 C7+ Aº Bm E7/9}
# SOURCE A VERIFIER: Dm      G7           C7+                  Aº                        Bm   E7/9
O meu amor eu te entreguei se contigo eu errei.....foi querendo acertar.....
[F7+]Sinto sau[F6]dade do teu [G7/4]beijo.[G7].....[F7+]felici[F6]dade me dei[G7/4]xou....[G7]...
{comment: À vérifier : F7+ G7 C7+ Ao}
# SOURCE A VERIFIER: F7+    G7           C7+                           Ao
O teu corpo é meu desejo ....sonho com seu jeito meigo ......
Que um dia me apaixo[Bm]nou...[E7]........
[A7+]Amor só eu [A7/9]sei... como te [F#m]amei ...e ainda te [Dm]amo.....
[A7+]Me dá teu per[A7/9]dão.... sua pai[F#m]xão... é meu oce[Dm]ano [G7]....
[C7+]Não posso mais viver ass[Bm]im ......volta de [E7]vez pra mim.....
