{title: Dizem Que A Felicidade ( ver. 2 )}
{artist: Art Popular}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, pagode, samba}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 89038
# Empreinte source SHA256: af168816cbe5f568a05368918bd11cef1e83c1c1cd9089df7249aaa0be3ad543
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

            CIFRA PARA CAVAQUINHO!!!!!!!!!!!!
{comment: À vérifier : Introdução.: D G Am G Am}
# SOURCE A VERIFIER: Introdução.: D G Am G Am 

[G]Dizem que a felicidade é [D/F#]um momento...
Eeeeeia eiaa[F]a...
Que se econtra em um sorriso em um de[E7]sejo...
Eeeeeia eia[Am]aa...
É estar em uma fes[Cm]ta, é viver o que nos rest[G]a...
É dizer pro mundo intero que a[Cm7] cert[D7]a, é o amo[G]r...
**[G]Dizem que a felicidade é [D/F#]uma rosa...
Eeeeeia eiaa[F]a...
Que é linda porque é timida e den[E7]gosa...
Eeeeeia eia[Am]aa...
É sambar com um bolero,[Cm] é viver o que eu quero...
[G]É dizer pro mundo intero que t[Cm7]e amo[D7], te[G] qu[D7]ero..

{start_of_chorus: Refrão}
[G]Uma namorada vestida de noiva, [D/F#]beijos de criança...
Olha que esperança, [C]menina de trança...
[B7]Faça essa razão emoc[G]iona[D7]r...
[G]Estrela cadente, caia de repente, [D/F#]traga aqui pra terra...
A felicidade t[C]oda em pedacinho, que uma b[B7]risa de verão espalhar[Em]á...
Ela espalh[Am]ara[D7], ela espalha[G]ra[Em]
Ela espalh[Am]ara[D7], ela espalha[G]ra

Volta no **

Cifra Adicionada por.:

AndrezinhoO Marques - Grupo Satisfação - Curitiba - PR

{end_of_chorus}
