{title: Asi es el rock and roll}
{artist: La 25}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, argentine rock, cumbia villera, latin alternative, rock en espanol, rock nacional}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 118757
# Empreinte source SHA256: 6021b32d1447faddcdea74a50c0c9c570f9dd3aa8f69b0f8a68f83649d1ee990
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

LAS HORAS QU[F]E HAS PERDIDO PEINAN[C]DOTE EN LA SUCIEDAD
[F]LA NOCHE TE DEJO EN LA BOCA UNA BOL[C]SA DE SAL
[G]ES MEDIA NOCHE YA Y NADA QUE TOMAR
[F]TU SANGRE ESTA TAN FRIA Y NO TE LEVANTAS
[G]ENCHUFA EL TRANSISTOR DEL VIEJO VALBULAR
[G]PARA QUE PUEDAS EMPEZAR A REVIVIR OTRA VEZ
[G]Y ARRANQUES EL VOLUMEN DE TU CORAZON
[C]ROCK AND ROLL SI ES DEL V[G]IEJO ES [C]MEJOR
[F]VIAJANDO EN EL FURGOR HASTA QUE LLEGUE MI[C] ESTACION
[F]MIENTRAS TANTO VOY CONTA[C]NDOTE LO QUE ES ROCK AND ROLL
[G]EL HIJO DEL RIGOR TE BAUTIZARAN
[F]LOS IDOLOS DE BARRO SE DERRUMBARAN
[G]LA LEY DE LA CALLE SOMOS VOS Y YO
[G]Y DEFENDIENDO TU HONOR HASTA LLEGAR AL LUGAR
[G]Y YA MAS QUE VENCIDO DE TANTO CAMINAR
[C]MADRUGADAS ASI ES EL[G] ROCK AND R[C]OLL
[F]LA LINEA DE LA L[C]EY NUNCA FUE MI CAMINAR
[F]LA MUSICA CARETA[C] TAMPOCO ME ACOMPAÑARA
[G]ESTA LOCA BOHEMIA SOLO ME ENSEÑO
[F]LLEVAR LAS COSAS SIMPLES DONDE QUIERE DIOS
[G]NO ME DIO RESULTADO HACER LAS COSAS BIEN
[G]OLVIDA EL DESENGAÑO DE ESA MUJER
[G]RECUERDA SIEMPRE LA MANO DEL AMIGO QUE FUE
[C]Y NO OLVIDES AQUEL[G]LA BOINA DEL CH[C]E
[C]Y NO OLVIDES LA "[G]10" DEL MAXIMO RE[C]Y
[F]YA ES MUY TARDE Y SIGO TIRADO [C]EN EL BAR
[F]CARAS EXTRAÑAS ESTA[C]N DEVUELTA EN MI MENTE
[F]NADA DE MI HARA CAMBIAR [C]TU FORMA DE ANDAR ESTAS CALLES
[G]Y ROGARE POR TI [C]QUE TE ALEJES DE MI
[F]Y AL SALIR NADIE[C] ME ESPERA SOLO ELLA
[F]PORQUE SABE DONDE ESTO[C]Y DONDE ENCONTRARME
[F]DESPERTE Y VEO QUE ESTAS[C] OTRAVEZ JUNTO A MI Y DICES
[G]ESTA BEIN AS[F]I O VAS A QUERER M[C]AS
