{title: Auto Rojo}
{artist: Vilma Palma e Vampiros}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, argentine rock, latin, latin alternative, latin pop, latin rock, rock en espanol}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 55980
# Empreinte source SHA256: 69d280e4d40a281d61d46114e93f184d1b94824dd0963462ca78606d5db80cb7
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{start_of_part: INTRO}
{comment: À vérifier : D G A (6)}
# SOURCE A VERIFIER: D G A (6) 

[D]TE BUSQUE EN MI  AUTO ROJO A LA SE[A]IS
LLEVABA UN F[D]RAC MUY NUEVO
QUE EN VERDAD NO ME QU[A]EDABA MUY BIEN ,
[D]TE LLEVE POR LA RUTA[A] QUE VA AL SUR
NENE NO [D]MAS RAPIDO ME DIJISTES
MIR[A]ANDOME EXTRA~ADA

[D]UOH  UO[G]OH  U[A]OH UOOH

[D]UOH  UO[G]OOH U[A]OH UOOOH

TE CONF[F#m]ESE
QUE QUIERO METERTE E[G]N MI CAMA
VIE[A]NDOTE SONREIR DE PLAC[D]ER
TE PROM[F#m]ETI QUE SOLO TOC[G]ARIA TUS PIES
SI EMPA~[E]AMOS LOS VIDRIOS ESTA BI[A]EN

AHORA HA[D]CE CALOR Y LA MUSICA
SUE[A]NA BASTANTE BIEN
TE JUR[D]E POR MI AMOR
QUE ATRAS LA V[A]AMOS A PASAR MEJOR
(REPETIR)
SH[D]URA SHURU....SH[G]ARU S[A]HURA..[D]. [G][A]

SO-ABA VER TU PECHO TATUADO
DEBAJO DE TU COLLAR
QUE EN VERDAD TENGO GANAS DE ARRANCAR
TE TOQUE POR LA LINEA QUE VA AL SUR
PUEDE SER MAS RAPIDO
TE DIJE MIRANDOTE EXALTADO

[D]UOH  UO[G]OH  U[A]OH UOOOH

[D]UOH  UO[G]OOH U[A]OH UOOOOH

TE CONFE[F#m]SE
QUE QUIERO METERTE E[G]N MI CAMA
VIE[A]NDOTE SONREIR DE PLACE[D]R
TE PROME[F#m]TI QUE SOLO TOCAR[G]IA TUS PIES
SI EMPA~[E]AMOS LOS VIDRIOS ESTA BI[A]EN

AHORA H[D]ACE CALOR Y LA MUSICA
SU[A]ENA BASTANTE BIEN
TE JUR[D]E POR MI AMOR
QUE ATRAS LA [A]VAMOS A PASAR MEJOR

AHORA H[D]ACE CALOR Y LA MUSICA
SU[A]ENA BASTANTE BIEN
TE JUR[D]E POR MI AMOR
QUE ATRAS LA [A]VAMOS A PASAR MEJOR

AMOR SI ESTAS CON GANA DE MAS,
PORQUE NO TE DESVISTES EN LA PARTE DE ATRAS.
SI TE DA IGUAL DESGARRA MI FRAC  ESPERO MUCHISIMO,
Y SE QUEDA AHI SENTADA NO PUEDO PARAR,
YA NO AGUANTO MAS, ME SIENTO IMPARABLE
CON TU PARTE DE ATRAS, SI TE IGUAL DATE LA VUELTA...

TE CONFE[F#m]SE
QUE QUIERO METERTE [G]EN MI CAMA
VI[A]ENDOTE SONREIR DE PLAC[D]ER
TE PROME[F#m]TI QUE SOLO TOCAR[G]IA TUS PIES
SI EMPA~[E]AMOS LOS VIDRIOS ESTA BI[A]EN

AHORA H[D]ACE CALOR Y LA MUSICA
SU[A]ENA BASTANTE BIEN
TE JUR[D]E POR MI AMOR
QUE ATRAS LA [A]VAMOS A PASAR MEJOR

AHORA H[D]ACE CALOR Y LA MUSICA
SU[A]ENA BASTANTE BIEN
TE JUR[D]E POR MI AMOR
QUE ATRAS LA [A]VAMOS A PASAR MEJOR

{end_of_part}
