{title: Cuentame}
{artist: Pedro Suárez-Vértiz}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, peruvian rock, pop peruano}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 102761
# Empreinte source SHA256: ba13b9026d5be6ee515bb8ea4c70427e7c64cba57ed1305859c7c9c2d5703cf1
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

            NOTA:PONER CAPOTRASTES EN EL QUINTO TRASTE.

{comment: À vérifier : INTRO: G Em A F#m (2 VECES)}
# SOURCE A VERIFIER: INTRO: G  Em A F#m (2 VECES) 

1)
[G]OH OH [Em]OH OH OH OH[A] OH.. [F#m]
(2 VECES)

2)
NO ERA INCRE[D]IBLE
SU CON[F#m]DUCTA ERA TER[Bm]RIBE
HOY LA ENCONT[Am]RARON CON UN  PAR DE L[Em]OCOS
ASALT[Gm]ANDO PERSONAS DE CIU[Bm]DAD EN CIUDAD

2)
EN SU MIRADA EL AMOR YA NO MORABA
PERO ERAN TAN BELLOS SUS OJOS
QUE TODOS SE OLVIDABAN DE SU REALIDAD

3)
[G]CUENTA[Em]ME
[A]CUENTA[F#m]ME SOBRE TU VIDA
Y [G]TRATAR[Em]E
[A]DE QUER[F#m]ERTE TODAVIA

2)
AY DIOS, AY DIOS, AY DIOS
YO ERA UN NI~O QUE SE VOLVIA LOCO
CUANDO LA COMTEMPLABA SIEMPRE MODELAR

2)
ELLA LLORABA Y NADIE LA CONSOLABA
MI CORAZON SE QUEBRANTO DE A POCOS
LA MUJER MAS HERMOSA YA NO VOLVERA HUM HUM

3)
[G]CUENTA[Em]ME
[A]CUENTA[F#m]ME SOBRE TU VIDA
Y [G]TRATAR[Em]E
[A]DE QUER[F#m]ERTE TODAVIA

1)
[G]OH OH [Em]OH OH OH OH[A] OH.. [F#m]
(2 VECES)

{comment: À vérifier : 2) D F#m Bm Am Em Gm Bm}
# SOURCE A VERIFIER: 2) D F#m Bm Am Em Gm Bm 

2)
NO DESESPERES SI ALGO QUEDA EN MI TU PUEDES
SALIR DE ESTA ASI ME CUESTE TODO
PERO A MI SI ME CUENTAS TODA LA VERDAD

4)
[Gm]CUENTAME MI A[Bm]MOR  (4 VECES) [A]

2)
NO ME LLORES NO ME ABRACES NO HAGAS NADA
YA NO SE SI TU LO VALGAS TODO
PORQUE FUISTES ALGO QUE NO SE PUEDE OLVIDAR

2)
SOLO RECUERDA CUANDO LLORES DE ESE MODO
QUE EL MEJOR REMEDIO DE TODOS
ES PENSAR EN AQUELLOS QUE HICISTES LLORAR

1)
[G]OH OH [Em]OH OH OH OH[A] OH.. [F#m]
(VARIAS VECES)

(VAMOS CUENTAME AMOR, CUENTAME SOBRE TU VIDA,
Y TRATARE, DE QUERERTE TODAVIA, NO ME LLORES NO ME ABRACES,
NO ME ABRACES NO HAGAS NADA, QUE YO SE NADA,
CUENTAME SOBRE TU VIDA, CUENTAME SOBRE TU VIDA,
YO YA TE AMABA, YO DE NI~O TE MIRABA, DE NI~O TE
CONTEMPLABA, Y ESTUVE LOCO POR TI, NO QUEDA NADA, NO ME LLORES, NO ME
ABRACES, CUENTAME SOBRE TU VIDA,  CUENTAME SOBRE TU VIDA, POR QUE TE DI NO
QUEDA NADA......)
