{title: Cocaine Blues}
{artist: Johnny Cash}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, arkansas country, outlaw country}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 13137
# Empreinte source SHA256: 476414a58137b0c771f139109188003334f65b32ec19b0a68044b78258c9a464
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

EARLY ONE MO[C]RNIN' WHILE MAKIN' THE ROUNDS
I TOOK A SHOT OF COCAINE AND I SHOT MY [G]WOMAN DOWN

I WENT RIGHT HOME AND I WENT TO BED
I STUCK[C] THAT LOVIN' 44 BENEATH MY HEAD
G[C]OT UP NEXT MORNIN' AND I GRABBED THAT GUN
TOOK A SHOT OF COCAINE AND A[G]WAY I RUN

MADE A GOOD RUN BUT I RUN TOO SLOW

[C]THEY OVERTOOK ME DOWN IN JUAREZ MEXICO

LAID IN THE HOT JOINT TAKIN' THE PILLS
IN WALKED THE SHERIFF FROM [G]JERICHO HILL

HE SAID WILLY LEE YOUR NAME IS NOT JACK BROWN

Y[C]OU'RE THE DIRTY HACK THAT SHOT YOUR WOMAN DOWN
[C]SAID OH YES OH YES MY NAME IS WILLY LEE
IF YOU'VE GOT A WARRANT JUST A R[G]EAD IT TO ME

I SHOT HER DOWN CAUSE SHE MADE ME SLOW

I THO[C]UGHT I WAS HER DADDY BUT SHE HAD FIVE MORE

WHEN I WAS ARRESTED I WAS DRESSED IN BLACK
THEY PUT ME ON A TRAIN AND THEY TO[G]OK ME BACK

I HAD NO FRIEND FOR TO GO MY BAIL

THEY [C]SLAPPED MY DRIED-UP CARCASS IN THE COUNTY JAIL

EARLY NEXT MORNING ABOUT A HALF PAST NINE
I SPIED A SHERIFF COM[G]IN' DOWN THE LINE

HOCKED AND HE COUGHED AS HE CLEARED HIS THROAT

HE SAI[C]D COME ON YOU DIRTY HACK INTO THAT DISTRICT COURT
[C]INTO THE COURTROOM MY TRIAL BEGAN
WHERE I WAS HANDLED BY T[G]WELVE HONEST MEN

JUST BEFORE THE JURY STARTED OUT

I S[C]AW THAT LITTLE JUDGE COMMENCE TO LOOK ABOUT
[C]IN ABOUT FIVE MINUTES IN WALKED A MAN
HOLDING THE VERDICT IN [G]HIS RIGHT HAND

THE VERDICT READ IN THE FIRST DEGREE
I[C] HOLLERED LORDY LORDY HAVE MERCY ON ME
[C]THE JUDGE HE SMILED AS HE PICKED UP HIS PEN
NINETY NINE YEARS IN THE [G]FOLSOM PEN

NINETY NINE YEARS UNDERNEATH THAT GROUND

I C[C]AN'T FORGET THE DAY I SHOT THAT BAD BITCH DOWN
[C]COME ON COME ON AND LISTEN UNTO ME
[G]

LAY OFF THAT WHISKEY AND LET THAT COCAINE BE
