{title: Dance in the River}
{artist: Chris Tomlin}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, ccm, christian alternative rock, christian music, world worship, worship}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 34141
# Empreinte source SHA256: 3ec512f9babcd0ea7f325ff9867289cc0442b61345c661ab38036bf529f466c9
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: aucun_accord_converti, ligne_accords_non_reconnue, tonalite_absente

Yea Yea Yea Yea Yea Yea...

We're gonna dance in the river. Yea...
We're gonna dance in the river. Yea...
We're gonna dance in the river. Yea...
We're gonna dance in the river. Yea...

We're gonna dance in the river. Yea...
We're gonna dance in the river. Yea...
We're gonna dance in the river. Yea...
We're gonna dance! dance! Everybody dance now!

{comment: À vérifier : ( Break - D - G - D - G - D - G - D - G - D )}
# SOURCE A VERIFIER: ( Break - D - G - D - G - D - G - D - G - D ) 

We're gonna dance in the river. Yea...
We're gonna dance in the river. Yea...
We're gonna dance in the river. Yea...
We're gonna dance in the river. Yea...

We're gonna dance in the river. Yea...
We're gonna dance in the river. Yea...
We're gonna dance in the river. Yea...
We're gonna dance! dance! Everybody dance now!

{comment: À vérifier : ( Break - D - G - D - G - D - G - D - G - D )}
# SOURCE A VERIFIER: ( Break -  D - G - D - G - D - G - D - G - D ) 

SAY: One! Two! Three! Four!

( END ON )   D
