{title: Alcohol}
{artist: Jorge Ben Jor}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, bossa nova, manguebeat, mpb, pagode, samba, samba-rock, tropicalia}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 53499
# Empreinte source SHA256: 5996272efcd12dc4d82685e4a9536790a4b8e4d1cff51706f8d6be46945ebb68
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

O MAGO MANDO[F#m]U AVISAR: [B7]
ÁGUA DE BEBER, ÁGUA DE BENZER
ÁGUA DE BANHAR
ALCOHOL SÓ PARA DESINFETAR

POR QUE O CÉU É ÁGUA MARINHA
POR QUE O SOL É OURO
POR QUE A LUA É PRATA
POR QUE A CHUVA É CRISTALINA
POR QUE O MAR É ESMERALDA
POR QUE SOMOS SERES TERRESTRES
POR QUE SÃO JORGE MORA NA LUA
POR QUE VOCÊ NÃO VEM ME DAR UM BEIJO
UM BEIJO DE AMOR E DE DESEJO
PORQUE EU GOSTO TANTO DE VOCÊ
EU GOSTO TANTO DE VOCÊ
EU GOSTO TANTO DE VOCÊ

NA HORA DO ESPANTO
NÃO PRECISA TER OLHO CLÍNICO
PARA SABER PARA SABER
QUE O MELHOR É FICAR TUDO EM FAMÍLIA
UM CONTROLE AMBIENTAL
POIS CONTRA UMA LINGUA ATÔMICA
NEM MESMO UM PARA-RAIO DIGITAL

CADA PALAVRA CAÇADA
É UM COMPASSO DE UM PASSADO
QUE FOI ENTERRADO
A CAÇA AO FANTASMA CONTINUA PORQUE
O FOGO É MAIS ANTIGO QUE O FOGÃO
EM BUSCA DE UMA NOVA IDENTIDADE
NA FILA DOS APOSENTADOS
UM RADICAL CHIC ESPERA A SUA VEZ
JOGANDO XADREZ

ÁGUA DE BEBER, ÁGUA DE BENZER
ÁGUA DE BANHAR
ALCOHOL SÓ PARA DESINFETAR

EM VEZ DE UMA NOVA TROMBADA
UMA MARCHA RÉ COM DIGNIDADE
É MELHOR DO QUE FICAR COM PESADELOS
TÉDIO, CALÇA ARRIADA,
QUEDA DE AUDIÊNCIA , FILME QUEIMADO

AQUELE HOMEM GROOVER
AQUELE SANTO HOMEM
SÓ PORQUE GOSTAVA
DE ANDAR DE TERNO BRANCO,
CAMISA DE SEDA, CARDÃO DE OURO,
TÊNIS, CHINELO OU TAMANCOS
ERA CHAMADO DE MARGINAL

SUBIR, DESCER, ENTRAR, SAIR
FAZ PARTE DO TALENTO INDIVIDUAL DE CADA UM
POR QUE VOCÊ NÃO VEM ME DAR UM BEIJO
UM BEIJO DE AMOR E DE DESEJO
PORQUE EU GOSTO TANTO DE VOCÊ
EU GOSTO TANTO DE VOCÊ
EU GOSTO TANTO DE VOCÊ
