{title: Sólo Tu Vendras A Juntar Mis Días}
{artist: Luis Alberto Spinetta}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-es, argentine indie, argentine rock, latin alternative, latin rock, post-punk argentina, rock en espanol, rock nacional}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 72759
# Empreinte source SHA256: d03d65c2b3da06e894e6a011a759e767e8f2d40a7f9961838f36cec9332e7bf2
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

Sé muy bien..[C]. [Fm7]
{comment: À vérifier : Ebmaj7 Am7(sin 5) Gm7 Cm7}
# SOURCE A VERIFIER:     Ebmaj7     Am7(sin 5)         Gm7      Cm7 
Sólo tú ven  -  drás     a      buscar mis días...
Por [Fm7]fin...   eh y[Cmaj7/9]eah yeah

Y tal vez...
Si es que no pasaran más que las horas...
Yo querría... querría morir...
Solo a la l[Cm7]uz...
Te [Fm7]sigo [Gm7]así con tal in[G#maj7]tensi    -  [Bbm7/11] dad...    -[Eb7]   -   -
Mi [G#maj7/6/9]amor...
Y es ig[C#7/9]ual
[C7/9+]En mi obscuri[Fm7]dad...
Solo [Bbm7]tú vend[Cm7]rás a bus[C#maj7]car mis  [C#/Eb]  dí  -  -[Eb7/9]  as...
    G#maj7    (Fm7   C7/9+ cadencia para el solo)
Por fin...

(solo del Mono Fontana con la base de la primera parte)

[Emaj7]Sé que cada instante no par[G#maj7/6/9]ece realidad...
[C#m7/9]No puedo ya mo[Eb7/9+]verme sin tus [G#m7]ojos amor...
[Emaj7]Sé que si te pierdo...me [G#maj7/6/9]pierdo de verdad...
[C#m7]Mi vida yo te [Ebm7/5+]pido...   que [Bbm7]vuelvas ense[C#/Eb]guida hacia [Emaj7]mí...
Pues solo [G#maj7]tú ven  -  [Bbm7]drás a bus[Cm7]car mis [C#maj7]días... [C#/Eb]
[G#maj7]Así...
