{title: A Deus Dai Louvor}
{artist: 3 Palavrinhas}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, musica infantil}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 116843
# Empreinte source SHA256: 543f4133d0476fd17257704afd324c8a4e072a3cde2a28022b972a322d1fbeae
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, repetition_ou_jeu_source, tonalite_absente

# SOURCE A VERIFIER: (E F# G) A7 (3x) (A G F# E) D 
[E] [F#] [G] [A7] [A] [G] [F#] [E] [D]

A Deus d[D]ai louvor com todo ser,
com todo corpo, a Cristo [A7]dai louvor
Use as mãos e os pés, a cabeça e a voz,
com seu c[A]or[G]po [F#]dai [E]lou[D]vor

Com a [A7]mão...

Com a [D]mão...
Outra [A7]mão...

Com a [D]mão...
Outra [D]mão...
Com o [A7]pé...

Com a [D]mão...
Outra [D]mão...
Com o [D]pé...
Outro [A7]pé....

{start_of_part: Passagem}
[G7] [D] [G7] [G] [F#] [E] [E7] [A7]

Com a [D]mão...
Outra [D]mão...
Com o [D]pé...
Outro [D]pé....
Com a cabe[A7]ça...

Com a [D]mão...
Outra [D]mão...
Com o [D]pé...
Outro [D]pé....
Com a cabe[A7]ça...
E a [G7]voz! [D][D][D][A][B]
[D]  Dai louvor! [D]

{end_of_part}
