{title: Afertoon Delight}
{artist: Will Ferrell}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 104282
# Empreinte source SHA256: 230846a26df4fcc781a9447c1d1601edbb35a3a5fc609231f491903792628a93
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

GONNA FIND M[F]Y BABY, GONNA HOLD HER TIGHT
GONNA G[B]RA[B]B SOME AFTERNOON DELIGHT.
MY MOTTO'S ALWAYS BEEN; WHEN IT'S RIGHT, IT'S RIGHT.
WHY WAIT UNTIL THE MIDDLE OF A COLD DARK NIGHT.

[Gm]WHEN EVERYTHING'S A LITTLE CLEARER IN THE LI[C]GHT OF DAY.
AND YOU KNOW THE NIGHT IS ALWAYS GONNA BE THERE ANY WAY.

[F]THINKIN' OF YOU'S WORKIN' UP MY APPETITE
[B]LO[B]OKING FORWARD TO A LITTLE AFTERNOON DELIGHT.
RUBBIN' STICKS AND STONES TOGETHER MAKES THE SPARKS INGITE
AND THE THOUGHT OF RUBBIN' YOU IS GETTING SO EXCITING.

[F]SKY ROCKETS IN FLIGH[C]T AFTERNOON[Dm] DELIGHT [B]AF[B]TERNO[Gm]ON DELI[F]GHT.

STARTED OUT THIS MORNING FEELING SO POLITE
I ALWAYS THOUGH A FISH COULD NOT BE CAUGHT WHO WOULDN'T BITE

BUT YOU'VE GOT SOME BAIT A WAITIN' AND I THINK I MIGHT TRY NIBBLING A LITTLE LITTLE AFTERNOON DELIGHT.

SKY ROCKETS IN FLIGHT. AFTERNOON DELIGHT. AFTERNOON DELIGHT.

[Gm]PLEASE BE WAITING FOR ME BABY WHEN I COME[C] AROUND.
WE COULD MAKE A LOT OF LOVIN' 'FOR THE SUN GOES DOWN.

SOUNDTRACK FROM THE MOVIE THE ANCHOR MAN
BY DOUG THE ONE
