{title: El Beso}
{artist: Abel Pintos}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, argentine rock, argentine telepop, folklore argentino, pop argentino}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 34318
# Empreinte source SHA256: 235d75f15132cba601ac30da5f982adace2af4f87a1c04fcfc3e9a7e1e8552cc
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

YO QUISIERA [Dm]TAN SOLO BE[A7]SARTE [Dm]
AUN SIN [D7]DARTE TU BESO S[Gm]OÑADO
PERO [Gm]QUIERO REZAR EN TU[Dm] BOCA
LA ARDIENTE PLE[Bb]GARIA QUE SAN[E]GRAN MI[A7]S LABIOS
[Gm]SOLO QUIERO REZAR EN T[Dm]U BOCA
LA ARDIENTE PLE[Bb]GARIA QUE SA[A7]NGRAN MIS L[Dm]ABIOS

EN LA ALTA CRUZ DE TU MIRADA
QUE YO MISMO AFERRE A MIS SENTIDOS
EL DESTINO ME HA CRUCIFICADO
CERRANDO LA PUERTA QUE CRUZA EL OLVIDO
MI DESTINO ME HA CRUCIFICADO
CERRANDO LA PUERTA QUE CRUZA EL OLVIDO

[C7]EL COLOR DE LA NOCHE EN[F]CENDIDA
[Bb]EL POEMA QUE [E]NO HE TERM[A7]INADO
(EL RESTO SIGUE LA SECUENCIA DE ACORDES DE LAS OTRAS ESTROFAS)
LA PASION, LA RAZON, LOS PECADOS
EL MODO DE AMAR Y ESTE GRITO OLVIDADO
COM UN RAYO HAS LLEGADO A MI VIDA
ROBANDOME TODO Y LA ZAMBA QUE CANTO

DESAFIO EL ESPACIO Y EL TIEMPO
Y DESANDO LOS CUATRO CAMINOS
Y ME MUERO A LOS PIES DEL DESEO
QUE AL VERTE SE VUELVE CANCION DENTRO MIO
SIEMPRE MUERO A LOS PIES DEL DESEO
QUE AL VERTE SE VUELVE CANCION DENTRO MIO

SOLO QUIERO QUE ME HAGAS EL DUEÑO
DE LA LUZ QUE SE ANIDA EN TU BOCA
SOLO QUIERO BEBER DE UN MILAGRO
AL SENTIR QUE ESA FLOR EN MI AMOR SE DESHOJA
VIDA HAZME BEBER DE UN MILAGRO
AL SENTIR QUE ESA FLOR EN MI AMOR SE DESHOJA

EL COLOR DE LA NOCHE ENCENDIDA
EL POEMA QUE NO HE TERMINADO
LA PASION, LA RAZON, LOS PECADOS
EL MODO DE AMAR Y ESTE GRITO OLVIDADO
COM UN RAYO HAS LLEGADO A MI VIDA
ROBANDOME TODO Y LA ZAMBA QUE CANTO
