{title: Falsa consideração}
{artist: Jorge Aragão}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, mpb, pagode, samba}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 81876
# Empreinte source SHA256: 12b86d823b03a575bf814ce909e2cbc5eb3a4a2c27a3d5327cd915c30cb4aa37
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tonalite_absente

Ag[C9]ora eu sei.... que o amor [Dm]que [D#m]você [Em]prometeu.....
não foi  igual ao que v[Gm7/9]ocê me deu..... [A7/4]era m[A7]entira o que [Dm]você jurou[F5+]....
m[F]as não faz mal[F5+].... [Dm]eu apren[G7]di que não [Em]se deve crer....
[A7]em tudo aquilo que al[Dm]guém nos diz....
num momento de p[D7]razer ou [Dm]de amor..[G7]..
ma[C9]s tudo bem eu sei que um d[Dm]ia v[D#m]ai e o[Em]utro vem....
você ainda há de enco[Gm7/9]ntrar alguém.... [A7/4]vai lhe faze[A7]r o que v[Dm]ocê me fez[F5+]....
e [F]ai...[F5+].... [Dm]na hora do [G7]sufoco sei v[Em]ocê vai me procurar.....
[A7]com a mesma conversa que um dia [Dm]me fez apaixonar.....
[Gm7/9]por alguém de uma [A7/4]falsa [A7]consideração..... [Dm]e ai.[Fm]......[B7] você vai perceber
que eu estou numa [Em]boa[Ebm]....[Dm] qu[A7]e durante algum tempo fiquei sem[Dm] ninguém....
[G7]mas há males na vida que vem para [C9]o bem (E[G7] agora)
