{title: Walk A Country Mile}
{artist: Slim Dusty}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, australian country, australian rock, bush ballad, classic australian country}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 120931
# Empreinte source SHA256: 12fc496879eb65e92c4156810d239152ef7db97c12da7f932d5613fa1925e11b
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: aucun_accord_converti, tabulations_interpretees_4_colonnes, tonalite_absente

            WELL I'VE (G) WALKED A MILE OR (C) TWO IN MY (G) LIFETIME
AND I'VE (C) TRAVELLED DOWN SOME MUDDY TRACKS AND (G)DRY
(D) 'CAUSE IF I (G) WANTED TO (C) GET WHERE I WAS (B7) GOIN' (C)
I KNEW I'D (G) JUST HAVE TO WALK (D7) THAT COUNTRY (G) MILE

(G7) NOW A (C) COUNTRY MILE MIGHT BE THE LONGEST DISTANCE
A MAN COULD EVER TRAVEL WHEN HE'S (G7) DOWN
AND YOU CURSE THE NEVER ENDING ROAD BEFORE YOU
WHEN YOU THINK YOU'LL NEVER MAKE IT INTO (C) TOWN
BUT YOU (F) MEET A FRIEND OR TWO ALONG THE HIGHWAY
AND YOU (C) LEARN A LOT YOU (A7) NEVER KNEW (D7) BEFORE
AND IF THE (C) JOURNEY TAKES A LIFETIME
WHEN YOU (F) THOUGHT A YEAR OR (D7) TWO
WELL YOU (G7) JUST DON'T GIVE UP EASY ANY (C) MORE

AND I'VE (G) WALKED A MILE OR (C) TWO IN MY (G) LIFETIME
AND I'VE (C) TRAVELLED DOWN SOME MUDDY TRACKS AND (G)DRY
(D) 'CAUSE IF I (G) WANTED TO (C) GET WHERE I WAS (B7) GOIN' (C)
I KNEW I'D (G) JUST HAVE TO WALK (D7) THAT COUNTRY (G)MILE

LEAD:

(G7) WALKING (C) THAT LONG MILE HAS SHOWN ME CHANGES
CHANGES IN THE PEOPLE AND THE (G7) LAND
BUT I'LL BET THE ROAD TO MARBLE BAR'S NO BETTER
THAN WHEN I DROVE WITH TRUCKS AND (C) CARAVANS
AND THE COUNTRY (F) BLOKE IS STILL THE SAME OLD BATTLER
NO MATTER WHAT (C) THE PLACE (A7) HE'S WORKIN? (D7)  IN
AND ALTHOUGH (C) I'VE COVERED MANY MILES
I STILL (F) CAN'T WAIT TO (D7) SEE
WHAT THE NEXT (G7) LONG COUNTRY MILE WILL (C) BRING

WELL I'VE (G) WALKED A MILE OR (C) TWO IN MY (G) LIFETIME
AND I'VE (C) TRAVELLED DOWN SOME MUDDY TRACKS AND (G)DRY
(D) 'CAUSE IF I (G) WANTED TO (C) GET WHERE I WAS (B7) GOIN' (C)
I KNEW I'D (G) JUST HAVE TO WALK (D7) THAT COUNTRY (G) MILE

I KNEW I'D (G) JUST HAVE TO WALK (D7) THAT COUNTRY (G) MILE
