{title: Where Is The Love}
{artist: Gentleman}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, cologne hip hop, german reggae, reggae fusion}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 48229
# Empreinte source SHA256: 553f99aed4fa8569af657ed313203743fb40a903b73615c6c101b343ee076bd0
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

[Gm] [Eb]

PREHOOK:
ALL A THE SINS THAT WE HAVE PAID FOR
TELL ME WHERE IS THE SENSE IN THE THINGS WE HAVE DONE
IS THIS EVERYTHING WE MADE FOR
ME SEE MOTHER AGAINST DAUGHTER AND FATHER AGAINST SON

VERSE1:
THERE IS NO LIFE WHERE IS THE HOPE IN THIS YA DUPPY TOWN
CONCRETE JUNGLE WHEN THE NIGHT COME PIER GUN CLOWN
CHILDREN TOO QUIET NO ME CAN T HEAR A SOUND
PIER DUTTY NEEDLES ALL OVER THE PLAYGROUND
DEM TRY FI SAY IF WE NUH PARTAKE WE AGO DOWN
LEAVING NO ALTERNATIVES YOU LEAVING PEOPLE WITH A FROWN
DEM A GWAAN LIKE THE WORLD IT NUH ROUND
DEM A GWAAN LIKE A FI DEM COMPOUND

{start_of_chorus: Chorus}
WHERE IS THE BROTHERLY LOVE
NOW CAN WE TRY TO FIND SOME FIND SOME WAYS NOW
TO GET WE OUT THE MUD
BECAUSE WE TIRED AND ENOUGH IS ENOUGH
WHERE IS THE SISTERLY LOVE
NOW CAN WE TRY TO FIND SOME FIND SOME WAYS NOW
TO GET WE OUT THE MUD
BECAUSE WE TIRED AND ENOUGH IS ENOUGH

VERSE2:
YOUR SYSTEM SICK AND THE PEOPLE NEED A BYPASS
YOU LIKE A FLAG INA THE WIND YOU CHANGE YOUR SIDE FAST
THE RIVER ROUGH BUT YOU KNOW YOU GOT TO TRY CROSS
WHILE DEM INA HELICOPTER FLY PASS
THERE IS A NEVER ENDING NIGHTMARE IN PARADISE
ANYBODY OUT THERE PLEASE CAN I HEAR A VOICE
ANYBODY OUT THERE REALIZE
ANYBODY OUT WILLING TO RISE

{end_of_chorus}
{start_of_chorus: Chorus}

VERSE3:
YOU TRY FI TELL WE SAY THE WORLD AGO END
YOU TRY FI TELL WE SEH WE VISION CONDEMN
YOU NUH SEE SEH THAT WE STILL AROUND STILL AROUND
STILL AROUND AND UTTER SOUND
WE CAN MAKE IT HAPPEN CAUSE A WE A MAKE THE WORLD GO ROUND
YOU TRY FI TELL WE SEH WE HAVE TO REPENT
YOU TRY TO SAY BELIEVE THE MESSAGE YOU SEND
BUT TRIBULATION STILL AROUND STILL AROUND
STILL AROUND WE UTTER SOUND
WE CAN MAKE IT HAPPEN CAUSE A WE A MAKE THE WORLD GO ROUND

{end_of_chorus}
