{title: Hey Ya}
{artist: Razorlight}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, britpop, modern rock, pop rock, rock}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 74522
# Empreinte source SHA256: 8bc43398278eda0016d72adb1aa9bdb251c4cb43f8636684c11122891ce8a997
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

My baby don'[G]t mess a[C]round
Because she loves me so
And [D]this I know[E] fo shooo...
[G]Uh, but [C]does she really wanna
But can't stand to see me
Walk[D] out the doo[E]...
[G]Don'[C]t try to fight the feelin'
Because the thou[D]ght alone is [E]killing me right nooww...
[G]Uh, than[C]k god for mom and dad
For sticking through together
'Cause [D]we don't know[E] hooowww...
UH!

(Chorus)
[G]Heeeyyy... Y[C]aaaaaaa...
[D]Heeyy Ya[E]aaaaaaa...
[G]Heeeyyy... Y[C]aaaaaaa...
[D]Heeyy Yaaaaaaaa... [E]
[G]Heeeyyy... Ya[C]aaaaaa...
[D]Heeyy Ya[E]aaaaaa...
[G]Heeeyyy... Y[C]aaaaaaa...
[D]Heeyy Ya[E]aaaaaaa...
