{title: No es lo mismo}
{artist: Alejandro Sanz}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, cantautor, latin, latin arena pop, latin pop, mexican pop, rock en espanol, spanish pop}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 15450
# Empreinte source SHA256: ab55e4915489c18eb26d4da906b2a6da615106cb446893727c298dd66917d7e8
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

ERES TANTA G[C]ENTE, QUE DIME,
CON QUIEN HABLO[Em7] AHORA,

NO VEIS, QUE NO SOIS IGUALES?
ER[Bb4/7+]ES LA DE: 'QUEDATE CONMIGO,
PROMETO DARTE T[F]ORMENTO, DARTE MALOS RATOS...'
Y[Fm7]O TE PROMETO, SI ME ESCUCHAS NIÑA, DARTE ARTE[C],

QUE NO ES LO MISMO QUE:
Q[D7/9]UEDATE Y YA VEREMOS, QUE[F7+/C]DATE Y YA VEREMOS.

[C]NO ES LO MISMO SER QUE ESTAR,
NO ES[Em7] LO MISMO ESTAR QUE QUEDARSE... QUE VA!!
T[Bb4/7+]AMPOCO QUEDARSE ES IGUAL QUE PARAR,
N[F]O ES LO MISMO,
S[Fm7]ERA QUE NI SOMOS, NI ESTAMOS,
NI NOS PE[C]NSAMOS QUEDAR,
PERO ES DISTINTO CONFORM[D7/9]ARSE O PELEAR,
NO ES LO MISMO...[F7/C] ES DISTINT[F5-/7/9]O.

[C]NO ES LO MISMO ARTE, QUE HARTAR,
NO[Em7] ES LO MISMO SER JUSTO QUE 'QUE JUSTO TE VA...' (VERAS)
N[Bb4/7+]O ES LO MISMO TU QUE OTRA, ENTERATE,
N[F]O ES LO MISMO,
Q[Fm7]UE SEPAS QUE HAY GENTE QUE TRATA DE CONFUNDIR[C]NOS,
PERO TENEMOS CORAZ[D7/9]ON QUE NO ES IGUAL,
{comment: À vérifier : F7/C (A7/9. Ab7/9. G7/9)}
# SOURCE A VERIFIER:              F7/C         (A7/9. Ab7/9. G7/9)
LO SENTIMOS... ES DISTINTO.

V[C]ALE... QUE A LO MEJOR ME LO MEREZCO,
B[F7+/G]UENO... PERO MI VOZ NO TE LA VENDO,
P[F]UERTA... Y LO QUE OPINEN DE NOSOTROS,
[Fm/G#]LEEME LOS LABIOS..[G7]. YO NO ESTOY EN VENTA.

V[C]ALE... QUE A LO MEJOR LO MERECEMOS,
B[F7+/G]UENO... PERO LA VOZ NO LA VENDEMOS,
P[F]UERTA... Y LO QUE OPINEN DE NOSOTROS,
L[Fm/G#]EEME LOS LABIOS..[G7]. QUE A MI ME VALE MADRE.

PUERTA Y AIRE QUE ME ASFIXIO,
QUE NO SE TRATA DEL LADO QUE QUIERAS ESTAR,
QUE ESTAR DE UN LADO O ECHARTE A UN LADO... (VERAS)
NO SE COMO DECIRTE, NO ES LO MISMO,
VIVIR ES LO MAS PELIGROSO QUE TIENE LA VIDA,
QUE DIGAN POR TELEVISION,
QUE HAY SUELTO UN CORAZON,
QUE NO ES IGUAL,
QUE ES PELIGROSO... QUE ES DISTINTO.

NO ES LO MISMO BASTA, O VA A ESTAR,
NI ES LO MISMO DECIR, OPINAR, IMPONER O MANDAR,
LAS LISTAS NEGRAS... LAS MANOS BLANCAS (VERAS)
NO ES LO MISMO,
NO GANA EL QUE TIENE MAS GANAS,
NO SE SI ME EXPLICO?
QUE HOY NADIE QUIERE SER IGUAL,
QUE MAS TE DA,
NO ES COMO UN 'ISMO'... ES INSTINTO.

                      (Sube un tono)

VALE......(CORO)

TENGO POMADA PÁ TÓ LOS DOLORES
REMEDIO PARA TODA CALSE DE ERRORES
TAMBIÉN RECETAS PÁ LA DESILUCIÓN
