{title: Homesick}
{artist: Gentleman}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, cologne hip hop, german reggae, reggae fusion}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 48193
# Empreinte source SHA256: 6c3404c83d68bebf4bad4f748e3bf01fe2fdfd58cf18ec2dbe8787467e1cbf49
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

[F] [Am]
{start_of_part: Intro}

[F]HO[Am]MESICK FOR A PLACE YOU VE NEVER SEEN BEFORE
YOU LOVE LIFE BUT YOU CAN T FIND THE KEY TO IT'S DOOR
WHERE IS THE SMILE UPON YOUR FACE
YOU RE LIVING IN DISGRACE
YOU RE RUNNING BUT THE WRONG THINGS YOU CHASE
I M NOT SAYING ANYTHING YOU VE NEVER HEARD BEFORE
BUT I HOPE THIS TIME IT A GO REACH TO YOUR CORE

[F]AN[G]D [Em]NOW[F] WE CAN FIND WAYS AGAIN
TO GET THINGS UNDER CONTROL
STRAIGHT FORWARD NUH WASTE TIME AGAIN
MOVEMENTS CAUSE THE STONE HAVE TO ROLL
THE TORCH AND LIGHT AND THE FLAME
THE GOODNESS IN YOU TO UNCHAIN
NO MORE YOU ARE LIVING IN VAIN
TURN ANOTHER PAGE IT WON T BE THE SAME

{end_of_part}
{start_of_chorus: Chorus}
[F] [G] [Em] [F]

AND EVERYBODY S JOURNEY IS THEIR OWN
HAFI TAKE THE LEED AND NO FALL OUT
NOW IT'S TIME TO GET UP FROM THE GROUND
HAFI FIND THE STRENGTH AND NO STALL OUT

[F]AN[G]D [Em]YOU[F] RE TRYING NOT TO SEE THE MESS AROUND YOU
BUT EVERYWHERE YOU TURN  IT SEEMS TO ABOUND YOU
IN THE MIX OF IT THE DEMONS DEM SURROUND YOU
BUT THERE S NOTHING THEY CAN DO
TO STOP THE LOVE THAT HAS FOUND YOU
NOW THE LIGHT AND THE TRUTH CAN GO ROUND
CRUCIAL TO THE RIDDIM WORD POWER AND SOUND
NOW THE FEARS AND THE DOUBT CAN GO DOWN
CONTAGIOUS ALL OVER THE TOWN

{end_of_chorus}
{start_of_chorus: Chorus}

[F]TA[Am]KE THIS INVITATION TO TRAVEL YOUR SOUL
SEEK THE NAVIGATION UNTIL YOU FIND OUT YOUR ROLE
IT MIGHT BE UNCOMFORTABLE GO AHEAD AND BE A REBEL
OR YOU WILL ALWAYS FIND YOURSELF MISERABLE
NOW IS THE TIME TO LIVE LIFE BEFORE YOU GO OLD
THERE IS A FIRE INSIDE YOU DON T MAKE IT GO COLD

{end_of_chorus}
