{title: Pickup Man}
{artist: Joe Diffie}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, country, country road, country rock, oklahoma country, redneck}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 67387
# Empreinte source SHA256: 6cc865f6ed318ad63948d64d8113ff79d8c839e2ff7bb2ac3f98523e64d2495d
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

WELL I GOT MY FIRST[G] TRUCK, WHEN I WAS THREE,

DROVE A HUNDRED THOUSAND MILES ON MY KNEES
HAULED [C7]MARBLES AND ROCKS, AND THOUGHT TWICE BEFORE,
I HAULED A [G]BARBIE DOLL BED FOR THE GIRL NEXT DOOR
SHE TRIED TO [D]PAY ME WITH A KISS I BEGAN TO UNDERSTAND,
THERE'S JUST SOME[G]THI[N.C.]NG WOMEN LIKE ABOUT A PICKUP MAN [G]

WHEN I TURNED [G]SIXTEEN, I SAVED A FEW HUNDRED BUCKS,

MY FIRST CAR WAS A PICKUP TRUCK
STARTED C[C7]RUISIN' THE TOWN AND THE FIRST GIRL I SEEN
WAS B[G]OBBIE JO GENTRY THE HOMECOMING QUEEN
SHE F[D]LAGGED ME DOWN AND CLIMBED UP IN THE CAB,
AND SA[G]ID, I[N.C.] NEVER KNEW YOU WERE A PICKUP MAN

YOU CAN [C7]SET MY TRUCK ON FIRE, ROLL IT DOWN A HILL,
BUT I [G]STILL WOULDN'T TRADE IT FOR A COUPE DEVILLE
IT'S GOT AN [C]EIGHT FOOT BED THAT NEVER HAS TO BE MADE,
YOU KNOW IF IT [D]WEREN'T FOR TRUCKS WE WOULDN'T HAVE TAILGATES
I MET [C7]ALL MY WIVES IN TRAFFIC JAMS,
YOU KNOW THERE'S SOME[G]THING WOMEN LIKE ABOUT A [D]PICKUP [G]MAN

MOST FRI[G]DAY NIGHTS, I CAN BE FOUND,

IN THE BACK OF MY TRUCK ON AN OLD CHAISE LOUNGE
BACKED [C7]INTO MY SPOT AT THE DRIVE-IN SHOW,
YOU KNOW A [G]CARGO LIGHT GIVES OFF A ROMANTIC GLOW
I NEVER [D]HAVE TO WAIT IN LINE AT THE POPCORN STAND,
THERE'S JUST S[G]OMETH[N.C.]ING WOMEN LIKE ABOUT A PICKUP MAN

[C7] [G] [C] [D]

A [C]BUCKET OF RUST, OR A BRAND NEW MACHINE
[D]ONCE AROUND THE BLOCK AND YOU'LL KNOW WHAT I MEAN
