{title: Naughty Girl}
{artist: Beyoncé}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, dance pop, pop, post-teen pop, r&b}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 3385
# Empreinte source SHA256: 4459b0cca002290dbc6a6218db55103fd5ba583c82ae519635e4e1182cd7bdec
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: aucun_accord_converti, ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : (Eb D Eb / Bm D Eb) for all lyric}
# SOURCE A VERIFIER:             (Eb D Eb / Bm D Eb)  for all lyric 

 I'M FEELIN SEXY
I WANNA HEAR YOU SAY MY NAME BOY
IF YOU CAN REACH ME
YOU CAN FEEL MY BURNING FLAME

I'M FEELIN KIND OF N-A-S-T-Y
I MIGHT JUST TAKE YOU HOME WITH ME
BABY THE MINUTE I FEEL YOUR ENERGY
YOUR VIBE'S JUST TAKEN OVER ME
START FEELIN SO CRAZY BABE
I FEEL THE FUNK COMING OVER ME
I DON'T KNOW WHAT'S GOTTEN INTO ME
THE RHYTHM'S GOT ME FEELIN SO CRAZY BABE

TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLIN ALL MY GIRLS
WE'RE GONNA TURN THIS PARTY OUT
I KNOW YOU WANT MY BODY
TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLIN ALL MY GIRLS
I SEE YOU LOOK ME UP AND DOWN
AND I CAME TO PARTY

YOU'RE SO SEXY, TONIGHT I AM ALL YOURS BOY
THE WAY YOUR BODY MOVES ACROSS THE FLOOR
YOU GOT ME FEELIN N-A-S-T-Y
I MIGHT JUST TAKE YOU HOME WITH ME

BABY THE MINUTE I FEEL YOUR ENERGY
THE VIBE'S JUST TAKEN OVER ME
START FEELIN SO CRAZY BABE
I FEEL THE FUNK COMING OVER ME
I DON'T KNOW WHAT'S GOTTEN INTO ME
THE RHYTHM'S GOT ME FEELIN SO CRAZY BABE

TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLIN ALL MY GIRLS
WE'RE GONNA TURN THIS PARTY OUT
I KNOW YOU WANT MY BODY
TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLIN ALL MY GIRLS
I SEE YOU LOOK ME UP AND DOWN
AND I CAME TO PARTY

I LOVE TO LOVE YOU BABY
I LOVE TO LOVE YOU BABY
I LOVE TO LOVE YOU BABY

TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLIN ALL MY GIRLS
WE'RE GONNA TURN THIS PARTY OUT
I KNOW YOU WANT MY BODY
TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLIN ALL MY GIRLS
I SEE YOU LOOK ME UP AND DOWN
AND I CAME TO PARTY
BY E- CHORDS. COM
REPEAT TO END

YES
I SAID YES TO YOUR NUMBER
AND YES TO YOU DATING ME
YES WE CAN BE TOGETHER
BUT YOU GOTTA WAIT FOR ME
THE FIRST TIME I SAY NO
ITâ?TS LIKE I NEVER SAID YES

I SAID YES WE CAN BE TOGETHER
YES YOU CAN STAY WITH ME
BUT WHEN I SAY NO NOT TONIGHT
YOU ACTIN SO UNGRATEFULLY
THE FIRST TIME I SAY NO
ITâ?TS LIKE I NEVER SAID YES

YOU WAS ON THE WALL
I WAS WITH MY CREW
YOU WAS WATCHIN ME BABY
I WAS WATCHIN YOU
SLOWLY YOU WALKED OVER
I MAINTAINED MY COOL
YOU SAID HELLO TO ME
I SAID HELLO TO YOU

YOU ASK ME WHERE Iâ?TM FROM
I ASKED YOU WHAT YOU DO
YOU SOMEHOW INTRIGUED ME
I THOUGHT YOU WERE SO COOL
SOMEWHERE BETWEEN HI AND GOODBYE
I FELT SO COMFORTABLE
I FELT LIKE WE COULD TALK ALL NIGHT
SO I GAVE MY NUMBER TO YOU

I SAID YES YOU NUMBER
AND YES TO YOU DATIN ME
YES WE CAN BE TOGETHER
BUT YOU GOTTA WAIT FOR ME

THE FIRST TIME I SAY NO
ITâ?TS LIKE I NEVER SAID YES
I SAID YES WE CAN BE TOGETHER
YES YOU CAN STAY WITH ME
BUT WHEN I SAY NO NOT TONIGHT
YOU ACTIN SO UNGRATEFULLY
THE FIRST TIME I SAY NO
ITâ?TS LIKE I NEVER SAID YES

CERTAINLY YOU CAN CALL ME BABY
I LOVE TO HEAR FROM YOU
YES OF COURSE YOU CAN COME AND SEE ME BOY
I WANT TO GET TO KNOW YOU MORE
Iâ?TM FEELIN YOU
NO BABY, NOT YET, WE CANâ?TT TAKE THAT NEXT STEP
WHY YOU GETTING SO UPSET
BOY YOU ACT AS THOUGH I NEVER TOLD YOU YES BEFORE
YOU ARE SO UNGRATEFUL

YOU WAS AT MY HOUSE
I WAS SITTIN ON MY COUCH
YOU WAS REALLY BEGGIN
SO I TOLD YOU TO GET OUT
I HAD BEEN MISJUDGING YOU

YOU HAD A LOTTA NERVE
YOU TOO DAMN OLD TO BE SO IMMATURE
I HOPE YOU LEARN
YOU SAID I MOVE TO SLOW
I SHOWED YOU TO THE DOOR
YOU SAID YOUâ?TD CALL ME LATER
I SAID DONâ?TT CALL NO MORE
ITâ?TS COOL IF YOU CANâ?TT WAIT FOR ME
Iâ?TM GLAD YOU LET ME KNOW
CUZ YOU SHOW ME YOUR TRUE FACE BABY
THE FIRST TIME I SAID NO

_____________________________________
Tabber : chri stian @e- cho rds .c om
