{title: Hasta el 66}
{artist: La 25}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, argentine rock, cumbia villera, latin alternative, rock en espanol, rock nacional}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 118770
# Empreinte source SHA256: bd106919f35682e1f951a3f139d58052e0e7f44fac5d49e27da72bb62173ac4e
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

VIEJOS PARLANTE A TRANS[G]ITORES
DESPACHASTE POR MIS PULMONES
ESTA MA[C]ÑANA NO ME HA TRATADO BIEN
PERO YO S[G]E QUE HOY TE VUELVO A TENER
DICE UN AM[C]IGO NO PODEMOS ESTAR ESCUCHANDO A CHUCK
QUE ME DEC[G]IS QUE NO TE PUEDO ENTENDER
SI VOLVER[D]AS COMO AYER OTRA V[C]EZ
HASTA EL [G]66

Solo: Mismos acordes que en los veros

NO ES UN BLUES AMARGO Y LENTO CON SU RITMO CALSINO
QUE TE PUEDA CAER MAL,
O UNA BALADA CON AQUELLOS DOS VIEJOS AMIGOS,
QUE ME GUSTA PERO NO
Y NECESITO UN POCO DE ELECTRICIDAD
Y QUE ME DEJES EN ESTADO SHOCK
SI VOLVERAS COMO AYER OTRA VEZ
HASTA EL 66

solo de teclado: MISMOS ACORDES QUE VERSO

AAAAAAHH...

NO ES UN BLUES AMARGO Y LENTO CON SU RITMO CALSINO
QUE TE PUEDA CAER MAL,
O UNA BALADA CON AQUELLOS DOS VIEJOS AMIGOS,
QUE ME GUSTA PERO NO
Y NECESITO UN POCO DE ELECTRICIDAD
Y QUE ME DEJES EN ESTADO SHOCK
SI VOLVERAS COMO AYER OTRA VEZ
HASTA EL 66

CAMINAR[D]AS POR ESAS BRAZAS CALIENTES
LE DIJO LA CHICA AL ESC[G]LAVO
Y CAMBIAR[D]AS TU CAMPOS DE ALGODON
POR ESA BOLSA DE SAL[G]
Y PASA[D]ME TU LATIGO CALIENTE POR TODOS L[G]ADOS
Y VOLVERA[C]AAAS OTRA V[G]EZ HASTA EL 66
BRILLA[C]RAS CON LA LES [G]POU QUE SOLO
TE DARA UN R[D]NR   [C] REMEM[G]ORANDOLOS

Y VOLVERA[C]AAAS OTRA V[G]EZ HASTA EL 66
BRILLA[C]RAS CON LA LES [G]POU QUE SOLO
TE DARA UN R[D]NR    [C]  REME[G]MORANDOLOS

[G]APUÑALAME HASTA DESANGRAR
Y MORIRE LO QUE QUIERAS
Y C[C]ONVENCEME DE QUE TODO ES LENTO
Y YA NO V[G]A MAS
QUE L[C]OS PROBLEMAS QUE AYER FUERON PROBLEMAS
HOY SO[G]N MAS PROBLEMAS
SI VOLVER[D]AS COMO AYER OTRA V[C]EZ
HASTA EL [G]66
