{title: De homem pra homem}
{artist: MV Bill}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, brazilian hip hop, funk ostentacao, rap nacional antigo}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 95887
# Empreinte source SHA256: 89b3d486696273f99819c2ed17315d94a3a9518acd6ed6183b3ae9cd47d1bef4
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: aucun_accord_converti, tabulations_interpretees_4_colonnes, tonalite_absente

            DE HOMEM PRA HOMEM

SÃO ONZE DA NOITE EU VEJO TELEVISÃO
DAQUI A POUCO EU VOU SAIR PRA QUEBRAR
AQUELE VACILÃO QUE JÁ DEU VÁRIAS MANCADAS
COM A RAPAZIADA SUA PRÓPRIA FAMÍLIA NÃO
QUER SABER DE NADA JÁ FOI CARRO, RELÓGIO, VARAL
ESTUPROU UMA MINA DE 12 LÁ NO MATAGAL DEU CASCUDO
NO MEU MULEQUE A TOA AGREDIU MINHA MULHER XINGOU MINHA
COROA PULOU NA LEI NA MINHA CABEÇA JÁ NÃO SEI NÃO DÁ PRA
ESQUECER SE EU NÃO PERDOEI NO JURI DA FAVELA JÁ ESTÁ CONDENADO
AO SONO ESTERNO LÁ NO SÍTIO QUEIMADO O MUNDO TODO TÁ PEQUENO
PRA NÓS DOIS ELE JÁ RIU VÁRIAS VEZES QUERO VER RIR DEPOIS EU FICO
BOLADO DE CABEÇA QUENTE QUANDO EU PENSO QUE ELE USOU MASSACROU MUITA
GENTE INOCENTE NA TELEVISÃO O FILME DE AÇÃO ME DA EMPOLGAÇÃO PRA EU
SAIR PRA MINHA MISSÃO QUANDO EI VEJO UMA COROA TRISTE EU LEMBRO QUE
NO MORRO SEGUNDA CHANCE NÃO EXISTE UMA PALAVRA VALE MAIS DO QUE
CONTRATO SE VACILAR VAI PRO SACO SÓ UM CIGARRO AGORA PODE ME ALCAMAR
SOMENTE UM DE NÓS DESSA NOITE IRÁ PASSAR SEU MAIOR ERRO FOI ME SUBESTIMAR
SEGURA AGORA A ONDA QUE O BICHO VAI PEGAR MECHER COM A COROA DELE
JÁ MAIS EU VOU SUBIR SEU GÁS ESSA NOITE NÃO VAI TER PAZ A CONVERSA
AQUI É DE HOMEM SE O BICHO PEGA PRO SEU LADO JÁ ERA UM ABRAÇO
A CONVERSA AQUI É DE HOMEM PRA HOMEM POR ISSO A MINHA SEGURANÇA
EU MESMO FAÇO NÃO SE BRINCA COM A HONRA DE NINGUÉM ELE ME ESCULACHOU,
E ZOOU MORADOR TAMBÉM BATEU NA MINA DELE DE BARRIGA FERIU MINHA MULHER,
TIROU UMA VIDA EU FIZ POR MENOS ATÉ ONDE DEU UM PARCEIRO MEU MORREU
CONSPIRAÇÃO PAPO DE CUSÃO DEIXOU AMIGO AÍ DE QUEBRA SEM EXPLICAÇÃO
OUTRA VIDA FOI TUDO QUE SONHEI MAIS TENHO QUE HONRAR A CADEIA QUE EU
JÁ PUXEI TALVEZ UM CRIME A MAIS PRA ASSINAR UM A MAIS UM A MENOS
QUEM QUE VAI LIGAR JÁ SAÍ, JÁ VOLTEI SOU REINCIDENTE MAS NUNCA
COLOQUEI TERROR NA MINHA GENTE DEPOIS QUE A GENTE ENTRA NÃO TEM SAÍDA
121,157 TÁ NA MINHA VIDA PERSPECTIVA DE VIDA AQUI É FODA H47 COM UM
PENTE DE 90 É MODA MAIS UMA HISTÓRIA MAIS UM QUERENDO UMA VITÓRIA
NÃO VOU DAR MOLE PORQUE NÃO QUERO VIRAR MEMÓRIA A PAZ A GUERRA NUNCA
 ANDARAM DE MÃOS DADAS SE A GUERRA IMPEROU UM DE NÓS VAI FICAR NA VALA
PT 40 NA CINTA VOU PRA PISTA APAGAR MAIS UM CUSÃO DA MINHA LISTA
{start_of_chorus: Refrão}
TÁ CHOVENDO EU VOU SAIR DE CASA NERVOSO PRA CHEGAR ONDE ELE
PARA O BICHO VAI PEGAR QUANDO A GENTE SE ENCONTRAR UM VI
FICAR EM PÉ E O OUTRO VAI DEITAR ESSA HORA ELE DEVE TÁ NO FLIPERAMA
EU VOU CHEGAR E ACABAR DE VEZ COM SUA FAMA QUEM DEIXOU FALHA É COBRADO
LÁ NA FRENTE EU SOU O COBRADOR, O TERROR EM FORMA DE GENTE NÃO TEM
CRIANÇA, NÃO TEM NINGUÉM NA RUA EU TÔ QUE ENM LOUCO ANDANDO PELA CHUVA
JAQUETA DE COURO, CALÇA JEANS VELHA TOCA PRETA NA CABEÇA MINHA FARDA DE
GUERRA MEU FILHO SÓ JESUS PODE TE SALVR EU LEMBRO QUE JÁ OUVI ESSA FRASE EM
ALGUM LUGAR DEIXA PRA LÉ MEU DESTINO TÁ CHEGANDO PARECE UM FILME ANTIGO NA
TV REPRISANDO NÃO TENHA MAIS CERTEZA NEM SEGURANÇA SE VAI VALER A PENA
MINHA VINGANÇA QUE SE FODA QUE ELE MORRA NÃO VOU VOLTAR JÁ VIM ATÉ AQUI
AGORA NÃO POSSO FALHAR QUANDO LEMBRO O QUE ELE FEZ COM MEU FILHO NÃO SEI
SE É MOTIVO O DEDO COÇA NO GATILHO SINTO FRIO O BATIMENTO ACELERA EU SOU
MAIS UM SOLDADO ARMADO ESCRAVO DA GUERRA BOCA SECA MÃO TREMENDO MINHA
COROA FOI DORMIR COM UM MAL PRESSENTIMENTO EU VEJO DE LONGE O FLIPERAMA
TÁ CHEIO OLHANDO COM ATENÇÃO MAIS O PALHAÇO NÃO ESTÁ NO MEIO COM RECEIO
MAIS VOU ATÉ O FIM TO LIGADO QUE ELE TÁ BOLADO VINDO ATRÁS DE MIM
DESISTIR NÃO DÁ, RETROCEDER JÁ MAIS MAS A COVARDIA VEM COM TRÊS MALUCOS
DE FUZIL LÁ TRÁS TODO MUNDO ME OLHANDO DE FORMA ESQUESITA QUE SENSAÇÃO
MEU NOME VAI SAIR DA LISTA OUÇO APENAS UMA VOZ POR TRÁS EU LEMBRO QUE EU
FALEI QUE ESSA NOITE NÃO IA TER PAZ

{end_of_chorus}
