{title: Swing (De Igual para Igual)}
{artist: Os Travessos}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, pagode}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 123506
# Empreinte source SHA256: d6e089e4a1ae79caa943face1381946cf835e1019bbdbb3ee95a8df126ba924e
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : Introdução: (E A )B A B7}
# SOURCE A VERIFIER:             Introdução: (E A )B A B7
SW[E]IN[A]G FOI FEITO PRA AGITAR
RAPAZIADA QUE É ESPERTA           BIS
ENTRA NA RODA PRA DANÇAR
O SOM TÁ MANEIRO,TÁ DE ARRASAR
A MULHERADA QUE É ESPERTA HOJE VAI SE ARRUMAR
V[E]IO[A]LÃO,CONTRABAIXO,PERCUSSÃO E UM METAL
EU TÔ VENDO A GALERA CURTINDO EM ALTO ASTRAL
SE NÃO SABE DANÇAR TUDO BEM NÃO FAZ MAL
EU CONFESSO PRA QUE A GENTE TRATA DE IGUAL PRA IGUAL
E NA PALMA DA MÃO VOCÊ VAI AGITAR
NÃO QUERO TE VER PARADO
QUERO TE VER BALANÇAR
E NA PALMA DA MÃO VOCÊ VAI ME AJUDAR
O[B] T[A]EU CORPO É UM INSTRUMENTO QUE ESTÁ PRONTO PRA TOCAR
E CANTAR,PRA DANÇAR,BALANÇAR,PRA CANTAR,DELIRAR
QUANDO OS TRAVESSOS CHEGAR
F[E]AB[A]INHO,RODRIGÃO,EDMILSON,RODRIGUINHO E CHORÃO
OS TRAVESSOS NA PARADA                          BIS
VEM CURTIR O PANCADÃO
A GENTE SÓ QUER CANTAR PRA TOCAR SEU CORAÇÃO
OS TRAVESSOS NA PARADA
VEM CURTIR
S[E]WI[A]NG FOI FEITO PRA AGITAR
RAPAZIADA QUE É ESPERTA
ENTRA NA RODA PRA DANÇAR
O SOM TÁ MANEIRO,TÁ DE ARRASAR
A MULHERADA QUE É ESPERTA HOJE VAI SE ARRUMAR
H[E]EI[A]!HEI!E A FELICIDADE INVADE A MULTIDÃO
HEI!HEI!
{comment: À vérifier : (B)B7}
# SOURCE A VERIFIER: (B)B7
E TODO MUNDO DANÇA...VAI FABINHO,CHORÃO,EDIMILSON,RODRIGÃO
VEM DANÇAR!!!
S[E]WI[A]NG FOI FEITO PRA AGITAR
RAPAZIADA QUE É ESPERTA                          BIS
ENTRA NA RODA PRA DANÇAR
O SOM TÁ MANEIRO,TÁ DE ARRASAR
A MULHERADA QUE É ESPERTA HOJE VAI SE ARRUMAR
V[E]IO[A]LÃO,CONTRABAIXO,PERCUSSÃO E UM METAL
EU TÔ VENDO A GALERA CURTINDO EM ALTO ASTRAL
SE NÃO SABE DANÇAR TUDO BEM NÃO FAZ MAL
EU CONFESSO PRA QUE A GENTE TRATA DE IGUAL PRA IGUAL
E NA PALMA DA MÃO VOCÊ VAI AGITAR
NÃO QUERO TE VER PARADO
QUERO TE VER BALANÇAR
E NA PALMA DA MÃO VOCÊ VAI ME AJUDAR
O[B] T[A]EU CORPO É UM INSTRUMENTO QUE ESTÁ PRONTO PRA TOCAR
E CANTAR,PRA DANÇAR,BALANÇAR,PRA CANTAR,DELIRAR
QUANDO OS TRAVESSOS CHEGAR
F[E]AB[A]INHO,RODRIGÃO,EDMILSON,RODRIGUINHO E CHORÃO
OS TRAVESSOS NA PARADA                          BIS
VEM CURTIR O PANCADÃO
A GENTE SÓ QUER CANTAR PRA TOCAR SEU CORAÇÃO
OS TRAVESSOS NA PARADA
VEM CURTIR
S[E]WI[A]NG FOI FEITO PRA AGITAR
RAPAZIADA QUE É ESPERTA
ENTRA NA RODA PRA DANÇAR
O SOM TÁ MANEIRO,TÁ DE ARRASAR
A MULHERADA QUE É ESPERTA HOJE VAI SE ARRUMAR
{comment: À vérifier : REPETE INTRODUÇÃO}
# SOURCE A VERIFIER: REPETE INTRODUÇÃO
