{title: Forever}
{artist: Andy Grammer}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, dance pop, modern rock, neo mellow, pop, pop rock, post-teen pop}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 18477
# Empreinte source SHA256: a72e9ee3efdda54d4fde39527d748a11031a30dea2b51fc5e3b45f307eefe4fc
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, repetition_ou_jeu_source, tonalite_absente

{start_of_part: Intro}
# SOURCE A VERIFIER: A - Bm - D - A (x2) 
[A] [Bm] [D] [A]

[A]Its amazing the time that its taken fo[Bm]r you to come out here... [D]
I don't know what you're doing th[A]ere...
T[A]here's only so many ways you can change how [Bm]light will hit your face...[D]
Or how you can fix your ha[A]ir...

Cause you only [A]got two eyes...
Two [Bm]lips so wide...[D]
You shouldn?t really take long at [A]all...
But when you fi[A]nally smile...
Cause [Bm]it's just right... [D]
Damn you look beautif[A]ul...

You take fo[A]rever..ever..ever..ev[Bm]er... [D]
But you're always worth waiting f[A]or...
You take for[A]ever..ever..ever..e[Bm]ver... [D]
I guess I'll wait a little mor[A]e...

Now I know i[A]t's time I realize I'm gonna be s[Bm]pending half my life...[D]
With my back up against the [A]door...

Cause you take for[A]ever..ever..ever..ever.[Bm].ever...ever..ever... [D]
But you're always worth waiting f[A]or...

[A]And you lie through your teeth when you try to c[Bm]onvince me that you'll be... [D]
You'll be out in less than [A]five...
[A]Cause we both know that the only way y[Bm]ou ever leave... [D]
Is if I set this whole place on f[A]ire...

You already [A]said you had the [Bm]perfect dress... [D]
So why you gotta try them [A]all?...
No matter how l[A]ate it gets [Bm]I must confess... [D]
But damn you look beautiful[A]...

Cause you take fore[A]ver..ever..ever..eve[Bm]r... [D]
But you're always worth waiting f[A]or...
You take fore[A]ver..ever..ever..eve[Bm]r... [D]
I guess I'll wait a little mo[A]re...

Now I know it's [A]time I realize I'm gonna be [Bm]spending half my life... [D]
With my back up against the d[A]oor...

Cause you take fore[A]ver..ever..ever..ever..[Bm].ever..ever..ever... [D]
But you're always worth waiting fo[A]r...

(palm mute this part)
[F#]And I guess you've trained me we[Db]ll...
Cause I a[A]lways end up singing to myse[Eb]lf...
You take f[D]orever love...
I'll wait for[E]ever love...

You take for[A]ever..ever..ever..e[Bm]ver... [D]
But you're always worth waiting f[A]or...
You take for[A]ever..ever..ever..e[Bm]ver... [D]
I guess I'll wait a little mo[A]re...

{end_of_part}
