{title: Perdóname}
{artist: Luciano Pereyra}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, argentine telepop, folklore argentino, latin pop}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 51650
# Empreinte source SHA256: fd067b4214584127353643ef43641a93c13b8bc090cc89373ea68b1c85b99f1f
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tablature_conservee_en_commentaire, tabulations_interpretees_4_colonnes, tonalite_absente

            ADVERTENCIA: Antes de copiar cada transcripción de ATAME a un archivo de texto,
selecciona la fuente tipográfica 'COURIER NEW', así no se te moverán los acordes
ni los punteos de su posición original y podrás tocar la canción correctamente.

                _______________________
# TAB:                |                       | 
               |      'PERDÓNAME'      |
               |    LUCIANO PEREIRA    |
               |   (VERSIÓN ORIGINAL)  |
               |_______________________|

=INTRO=

{comment: À vérifier : hide this tab D A D A}
# SOURCE A VERIFIER: hide this tab     D                A          D                A 
# TAB:  E--5-----5----5-----7--10-9----5-----5----5-----7--10-9--- 
# TAB:  G---------------8-7-------------------------8-7----------- 
# TAB:  B------7---------------------------7---------------------- 
# TAB:  D----7---------------------------7------------------------ 
[A---------------------------------------------------------]
[E---------------------------------------------------------]

=Estrofa 1.1=
  [D]SIENTO QUE LA VIDA SE ME [G]VA...
  [Em]SIENTO QUE EL SI[A]LENCIO SE APO[D]DERA MÁS DE MÍ...
  [Em]SIENTO QUE LLE[G]GÓ LA SOLE[A]DAD...
  [F#m]Y PLANTÓ BAN[F#m7]DERA EN [Bm]MÍ... [G]PARA DAR RE[Em]FUGIO A ESTE FI[A]NAL...

=Estrofa 1.2=
  [D]SIENTO QUE MI DIA SE NU[G]BLÓ...
  [Em]SIENTO QUE MIS [A]OJOS VUELVEN [D]A LLORAR...
  [Em]SIENTO QUE ME A[G]BRAZA EL DO[A]LOR... [G]Y QUE NO ME DEJA RESPI[A]RAR...

=CORO=
  PER[D]DÓNAME... PER[Bm]DÓNAME...
  [Em]SI NO SUPE A[G]MARTE COMO [A]QUIERES...
  PE[D]RDÓNAME... PER[Bm]DÓNAME...
  [Em]NADIE OCUPA[G]RÁ EN MI [A]ALMA TU LUGAR SI [D]VUELVES...

*Se repite la INTRO*

=Estrofa 2.1=
  [D]CÓMO ME LASTIMA ESTE A[G]DIOOO_ÓS...
  [Em]CÓMO SEGUI[A]RÉ MI VIDA [D]SI NO ESTÁS...
  [Em]CÓMO HE DE EXPLI[G]CARLE A TU [A]RAZÓN...
  [G]QUE MI ERROR FUE A[Em]MARTE MÁS Y [A]MÁS...

=CORO=
  PER[D]DÓNAME... PER[Bm]DÓNAME...
  [Em]SI NO SUPE A[G]MARTE COMO [A]QUIERES...
  PE[D]RDÓNAME... PER[Bm]DÓNAME...
  [Em]NADIE OCUPA[G]RÁ EN MI [A]ALMA TU LUGAR SI [D]VUELVES...

=PUENTE=
[Bm]  EL TIEMPO CORRE Y NO PRE[F#m]TENDE DESCAN[F#m7]SAR...
[Bm]  PERO MI [Bm7]VIDA SE DE[A]TUVO EN TU MIRAR...
  CÓMO [G]ES QUE POR AMOR... ME [A]TENGAS QUE OLVIDAAA_[B]AAAR...

=CORO FINAL=
  PER[E]DÓNAME... PER[C#m]DÓNAME...
  [F#m]SI NO SUPE A[A]MARTE COMO [B]QUIERES...
  PER[E]DÓNAME... PER[C#m]DÓNAME...
  [A]NADIE OCUPARÁ EN MI [B]ALMA TU LUGAR SI [E]VUELVEEES...
  [A]   [B]SI [E]VUELVEEES...[A]   [B]SI [E]VUELVEEES...
