{title: Swingueira}
{artist: Os Travessos}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, pagode}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 123507
# Empreinte source SHA256: b233469d6bfb3f92f74cd7c2e574a54e31bc7e709f6311cc1ea358fc243d13cc
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : Introdução: (E A)B A B7}
# SOURCE A VERIFIER:             Introdução: (E A)B A B7
{comment: À vérifier : (E A)B7}
# SOURCE A VERIFIER: (E A)B7
{comment: À vérifier : A SWINGUEIRA,A SWINGUEIRA}
# SOURCE A VERIFIER: A SWINGUEIRA,A SWINGUEIRA
SWINGUEIRA BRASILEIRA
A SWINGUEIRA DOS TRAVESSOS É MANEIRA
E VAI FAZER VOCÊ DANÇAR
{comment: À vérifier : (E A)B7}
# SOURCE A VERIFIER: (E A)B7
E O PESO DO BAIXO
JUNTO COM A BATERA
SEGUIDO DA PERCUSSÃO
ESTREMECE O CORAÇÃO
E O POVO DANÇA
E O POVO DANÇA
SEM PARAR
{comment: À vérifier : (E A)B7}
# SOURCE A VERIFIER: (E A)B7
GATINHA GOSTOSA
CORPINHO BONITO EM FORMA DE VIOLÃO
RAPAZIADA CAI NO CHÃO
QUANDO ELA PASSA
NO RITMO DA MARCAÇÃO
{comment: À vérifier : (B A)B7}
# SOURCE A VERIFIER: (B A)B7
E DANCE,BALANÇE
NÃO FIQUE DE BOBEIRA
PORQUE É MUITO RARO UMA BANDA DE SWINGUEIRA
{comment: À vérifier : (E A)B7}
# SOURCE A VERIFIER: (E A)B7
VEM PRA BALANÇAR
A GALERA SACUDINDO O ESQUELETO
E VEM PRA BALANÇAR
QUERO VER BRANCO,AMARELO,ÍNDIO E PRETO
[E]VEM PRA BALANÇAR
VOU CURTIR ESSA PANCADA QUE EU M[A]EREÇO
SE QUISER ATÉ TE DOU O ENDE[B]REÇO
DE ONDE T[A]Ô COM A GALE[B7]RA DOS TRAVES[E]SOS
{comment: À vérifier : (E A)B7}
# SOURCE A VERIFIER:  (E A)B7
{comment: À vérifier : A SWINGUEIRA,A SWINGUEIRA}
# SOURCE A VERIFIER: A SWINGUEIRA,A SWINGUEIRA
SWINGUEIRA BRASILEIRA
A SWINGUEIRA DOS TRAVESSOS É MANEIRA
E VAI FAZER VOCÊ DANÇAR
{comment: À vérifier : (E A)B7}
# SOURCE A VERIFIER: (E A)B7
E EU TÔ COM A CORDA TODA
NESSA SWINGUEIRA
NA 2ª,3ª,4ª,5ªE 6ª FEIRA
EU VOU DANÇAR
SÁBADO E DOMINGO DESCANSAR?
NEM PENSAR!!!!!
E EU TÔ COM A CORDA TODA
DENTRO DO SALÃO
A TROCA DE OLHARES
O CLIMA DE AZARAÇÃO
JÁ DEU PRA NOTAR
QUE NÃO TEM HORA PRA ACABAR
{comment: À vérifier : (B A)B7}
# SOURCE A VERIFIER: (B A)B7
E DANCE,BALANÇE
NÃO FIQUE DE BOBEIRA
PORQUE É MUITO RARO UMA BANDA DE SWINGUEIRA
{comment: À vérifier : (E A)B7}
# SOURCE A VERIFIER: (E A)B7
HEI!A GALERA SACUDINDO O ESQUELETO
E VEM PRA BALANÇAR
QUERO VER BRANCO,AMARELO,ÍNDIO E PRETO
[E]VEM PRA BALANÇAR
VOU CURTIR ESSA PANCADA QUE EU ME[A]REÇO
SE QUISER ATÉ TE DOU O END[B]EREÇO
DE ONDE TÔ[A] COM A GALERA D[B7]OS TRAVES[E]SOS
{comment: À vérifier : (E A)B7}
# SOURCE A VERIFIER: (E A)B7
E VEM PRA BALANÇAR
SACODE EDIMILSON,RODRIGÃO E CHORÃO
EU VOU CURTIR
VEM FABINHO,RODRIGUINHO VAI CURTIR
Ô MEU IRMÃO

[E]VEM PRA BALANÇAR
VOU CURTIR ESSA PANCADA QUE EU MER[A]EÇO
SE QUISER ATÉ TE DOU O ENDERE[B]ÇO
DE ONDE [A]TÔ COM A GALERA[B7] DOS TRAVES[E]SOS
{comment: À vérifier : (E A)B7}
# SOURCE A VERIFIER: (E A)B7
{comment: À vérifier : A SWINGUEIRA,A SWINGUEIRA}
# SOURCE A VERIFIER: A SWINGUEIRA,A SWINGUEIRA
SWINGUEIRA BRASILEIRA
A SWINGUEIRA DOS TRAVESSOS É MANEIRA
E VAI FAZER VOCÊ DANÇAR
