{title: The Pill}
{artist: Loretta Lynn}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, country, country rock, nashville sound}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 97623
# Empreinte source SHA256: b2857fbeb086c5bf7fb02459c0a0065a4281989848653704f2383bd5836b2d65
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

[D] [G]
[D]YOU WINED ME AND DINED ME, WHEN I WAS YOUR GIRL

[A7]PROMISED IF I'D BE YOUR WIFE, YOU'D SHOW ME THE WORLD
[D] [G]
[D]BUT ALL I'VE SEEN OF THIS OLE WORLD IS A BED AND A DOCTOR BILL

[A7]I'M TEARIN' DOWN YOUR B[D]ROODER HOUSE CAUSE NOW I GOT THE PILL

[D]
[G]ALL THESE YEARS I'VE STAYED AT[D] HOME, WHY YOU HAD ALL YOUR FUN

[A7]AND EVERY YEAR THAT'S GONE BY, ANOTHER BABY'S COME
[D]
[G]THERE'S GONNA BE SOME CHANGES [D]MADE RIGHT HERE ON NURSERY HILL

[A7]YOU'VE SET THIS CHICKEN YOU[D]R LAST TIME CAUSE NOW I'VE GOT THE PILL

[A7] [G]
[D]THIS OLD MATERNITY DRESS I'VE GOT IS GOIN IN THE GARBAGE
THE CLOTHE[A7]S I'M WEARIN' FROM NOW ON
WON'T TAKE UP[G] SO MUCH YARDAGE [A7]
[D] [G]
[D]MINI SKIRTS, HOT PANTS AND A FEW LITTLE FANCY FRILLS
[A7]
[D]I'M MAKIN UP FOR ALL THOSE YEARS, SINCE I'VE GOT THE PILL

[D] [G]
[D]I'M TARD OF ALL YOUR CROWIN', HOW YOU AND YOUR HENS PLAY

[A7]WHILE HOLDIN' A COUPLE IN MY ARMS, ANOTHER'S ON THE WAY
THIS CHICKE[D]N'S DONE TORE UP HER NEST
AND I'M READY TO [G]MAKE A DEAL [D]

AND YOU CAN'T AFFORD TO TURN IT DOWN
CAUSE YOU KNOW I'VE GOT[A7] THE PILL [D]

[A7] [G]
[D]THIS INCABATOR IS OVERUSED, BECAUSE YOU'VE KEPT IT FILLED
[A7] [G]
[A7]THE FEELIN' GOOD COMES EASY NOW, SINCE I'VE GOT THE PILL
[D] [G]
[D]IT'S GETTIN' DARK, IT'S ROOSTIN' TIME, TONIGHT'S TO GOOD TO BE REAL

[A7]AH BUT DADDY DON'T YOU WORR[D]Y NONE, CAUSE MAMA'S GOT THE PILL

[A7]NAH DADDY DON'T YOU WOR[D]RY NONE, CAUSE MAMA'S GOT THE PILL
