{title: Play Guitar Play}
{artist: Conway Twitty}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, arkansas country, country, country rock}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 62863
# Empreinte source SHA256: 8e76f437b2385f7e4d84f61a1a8e494ee3f50d34df4cc92f4fc12d97ea52cbfc
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

Play, guitar[C] play.... Take me back.... to yes-terday...
let me see... cotton growin'... in the [G]fields....[Gm]
Let me [C]hear... my momma callin'... "Look a yon-der y'all who's comin'!
Down the road, he's comin' [G]home!".[F]... but they know i never [C]will.
[G]I left them livin' with that [F]awful thang i [C]done....
[G]I didn't tell them I just [F]packed my clothes and [G]run....[Gm]
[C]Play... Guitar play... Help me through... another day.
Help me make... another dollar... before I [G]go....[Gm]...
We got [C]time... for one more song... then we'll have... to move along...
another town... another [G]crowd...[F]  Lord I wonder if they [C]know...
[G]Can they read between the [F]lines in my [C]songs...
[G]as i sing about a [F]good boy, that went [G]wrong...[Gm]
[F]Guitar we got years to [C]kill...
[F]Got to climb that distant [C]hill...
[F]I wonder if they think of [C]me............

Guitar play....
