{title: So mais um maluco}
{artist: MV Bill}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, brazilian hip hop, funk ostentacao, rap nacional antigo}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 95893
# Empreinte source SHA256: 1ab4932727c33176705b2b73325eec6cc64b1d1f22713217db444b8128963698
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: aucun_accord_converti, tabulations_interpretees_4_colonnes, tonalite_absente

            SO MAIS UM MALUCO

DIRETO DO HOSPÍCIO QUE CHAMAM DE FAVELA
AQUI MAIS UM MALUCO QUE NÃO ACREDITA EM NOVELA
SE A VIDA É BELA, NA TELA TUDO BEM
QUEM É LOUCO COMO EU VESTE A CAMISA DE FORÇA TAMBÉM
MINHA LOUCURA É SIMPLES DE SER COMPREENDIDA
ME TRANSFORMARAM EM CANIBAL PRETO SUICIDA
INCONFORMADO MENSAGEIRO DA VERDADE
PELO POVO AGONIZANDO AS MARGENS DA SOCIEDADE
QUE MASSACRA DESTRÓI HUMILHA
TRANSFORMA SEU FILHO EM LADRÃO E PROSTITUI SUA FILHA
TE ESCRAVIZA TE HUMILHA TE MATA
ENQUANTO O VERDADEIRO LADRÃO USA TERNO E GRAVATA
NÃO MANUSEIA FUZIL NEM ESCOPETA
MATA MILHÕES DE BRASILEIROS SÓ COM UMA CANETA
FICA IMPUNE, NÃO VAI PRESO
ELE NÃO É POBRE (NÃO) NÃO É PRETO
SE FOR CONDENADO FICA EM CELA SEPARADA
COM TELEVISÃO FRIGOBAR E ÁGUA GELADA
CRIMINOSO COM NÍVEL SUPERIOR
FINANCIA A GUERRA O ÓDIO O RANCOR
A BURGUESIA FAZ QUESTÃO DE NÃO ENTENDER
DISCA 1-9-0 E MANDA OS HOME ME PRENDER
O SOCIÓLOGO ME OUVE E FICA PUTO
DIZ QUE ESSE BAGULHO DE RAP É COISA DE MALUCO
ANALFABETO IGNORANTE SEM CULTURA
DIZ QUE QUEM É SÁBIO COM FAVELADO NUNCA SE MISTURA
QUEM DIRIA, QUE SABEDORIA
ESTUDOU EM OUTRO PAÍS AGORA TEM PAVOR DA MAIORIA
MV BILL UM MALUCO CHAPA QUENTE
QUE NÃO ACEITA AS COVARDIAS ASSIM TÃO FACILMENTE
EU TO LIGADO QUE A ELITE ME ODEIA
ME CHAMA DE BANDIDO E DIZ QUE MULHER PRETA E FEIA
EU NA CADEIA SENTIRIAM ATÉ PENA
MENOS UM PROBLEMA E ME VISTA FORA DE CENA
O PESADELO QUE A ELITE NÃO QUER TER
BATER DE FRENTE COM ALGUÉM DA CDD
TREMA NA BASE QUANDO VÊ O BILL
CHAMA A POLÍCIA QUANDO VÊ O BILL
AQUELE PRETO COM O CORPO TATUADO
DENUNCIANDO A POBREZA E A MISÉRIA DO BRASIL
TEM MUITA COISA NA TV QUE EU NÃO CURTO
SÓ MAIS UM MALUCO, SÓ MAIS UM MALUCO
NA HORA DE FALAR EU NUNCA FICO MUDO
SÓ MAIS UM MALUCO, SÓ MAIS UM MALUCO
MANDA OS HOME ME PRENDER ME DEIXA PUTO
SÓ MAIS UM MALUCO, SÓ MAIS UM MALUCO
EU NASCI ASSIM POR ISSO EU NUNCA MUDO
SÓ MAIS UM MALUCO, SÓ MAIS UM MALUCO
A MADAME SE ASSUSTOU A FAVELA ME DEU DEZ
QUANDO EU ENTREI SEM CAMISA DE PISTOLA NO FREEJAZ
PRA QUEM DUVIDA AINDA TEM MUITO MAIS
EU FAÇO APOLOGIA NÃO DO CRIME E SIM DA PAZ
MAS, ROUPA BRANCA SEM PENSAR NA MAIORIA
PEDIR PAZ SEM JUSTIÇA É UTOPIA
A GUERRA ME PARECE INEVITÁVEL
PRA QUEM VIVE NA POSIÇÃO DESFAVORÁVEL
SUFOCADA AMONTOADA AQUI NO MORRO
SE A POPULAÇÃO SE REVOLTAR NÃO GRITE POR SOCORRO
É O ARMAMENTO O POVO QUE VAI SE FORMAR
VEJA SEU DESCASO E ARROGÂNCIA NO QUE VAI PARAR
PODE ESNOBAR, QUEM VIVE DE BAIXA RENDA
QUANDO O SANGUE BATER NA SUA PORTA ESPERO QUE VOCÊ ENTENDA
E DESCUBRA QUE SE PRETO E POBRE É FODA
SOCIEDADE HIPÓCRITA, SÓ LEMBRE DE SER BRASILEIRO NA COPA
FORA DA MODA EM CIMA DO TOQUE AFRICANO
DESOBEDIENTE TROCA O PENTE ENQUANTO EU VOU FALANDO
MILITANDO, DECLAMANDO, RIMANDO, VERSANDO
BRIGANDO, GRITANDO, MORRENDO E AO MESMO TEMPO MATANDO
MEU PAÍS, CADÊ SUA RAIZ?
AQUI O POVO QUE NÃO LUTA É CHAMADO DE FELIZ
E SEGUE A RISCA OS PADRÕES DA BURGUESIA
A MESMA QUE ASSIMILA A DANÇA COM PORNOGRAFIA
INFLUÊNCIA MINHA SOBRINHA E SUA TIA
NA FRENTE DO ESPELHO IMITANDO A COREOGRAFIA
INCENTIVANDO A BRUTAL PEDOFILIA
EU CREIO EM DEUS PAI TODO PODEROSO O ÚNICO QUE ME GUIA
SE FOR PRA SER FELIZ ASSIM
SEREI MALUCO ATÉ O FIM
E SE UMA GUERRA AMANHÃ ESTOURAR
SEI QUAL LADO EU VOU ESTAR
É MUITO CONFUSO É MUITO SINISTRO
QUEM CAUSA A MISÉRIA QUE JURA TER AMOR A CRISTO
E COM SEU AR SUPERIOR NÃO TEM RESPEITO PELO GAY
PELO IDOSO PELO POBRE E PELO PRETO
TREMA NA BASE QUANDO VÊ O BILL
CHAMA A POLÍCIA QUANDO VÊ O BILL
AQUELE PRETO COM O CORPO TATUADO
DENUNCIANDO A POBREZA E A MISÉRIA DO BRASIL
TEM MUITA COISA NA TV QUE EU NÃO CURTO
SÓ MAIS UM MALUCO, SÓ MAIS UM MALUCO
NA HORA DE FALAR EU NUNCA FICO MUDO
SÓ MAIS UM MALUCO, SÓ MAIS UM MALUCO
MANDA OS HOME ME PRENDER ME DEIXA PUTO
SÓ MAIS UM MALUCO, SÓ MAIS UM MALUCO
EU NASCI ASSIM POR ISSO EU NUNCA MUDO
SÓ MAIS UM MALUCO, SÓ MAIS UM MALUCO
