{title: Eu Chorei}
{artist: Exaltasamba}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, funk carioca, pagode, samba paulista, sertanejo, sertanejo universitario}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 134689
# Empreinte source SHA256: c3baec0b955aa044445da7416ef82b86a6a33fdedd31ec0037d6bf510b17097c
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

{start_of_part: Intro}
[A7+] [E/G#]

E[A7+]u Chorei,
todo m[D7+]undo ta lutando, minha v[E/G#]ida transformando...
[A7+]Eu Chorei,
o meu p[D7+]ranto ta inundando, toda á[G7+]gua do oceano...
E[C7+]u Amei, Só a Lu[Bm7]a companheira pro meu pranto decifrar...
[C7+]Eu Amei,[Bm7] Coração bate em silêncio pede a[E/G#] Deus pra melhorar...
[Am7]Tanto Amor,[Bm7] Tanto Amor...[E/G#]

[A7+]Deixe Estar, o[D7+] tempo é o mestre pro teu cho[E/G#]ro enxugar...
[A7+]Deixe Estar, d[D7+]evagar Deus da uma força as coisas vo[G7+]ltam pro lugar...
Já[C7+] Amei,como você[Bm7] ta amando, todo mundo amou um Dia...
J[C7+]á chorei, como vo[Bm7]cê está chorando já [E/G#]vivi essa agonia...
[Am7]É o amor , É o [Bm7]amor.... [E/G#][Dm7]

[Am7]Eu vivo contando as estrelas do[Dm7] céu...
Tentando esq[G7+]uecer esse amor me fez [C7+]réu...
Eu [F7+]to tão perdido[Bm7] eu ando sozinho, Procu[E/G#]ro um carinho pra me completar....
[Am7]O amor quando chega não dá pra [Dm7]evitar...
Você ta na f[G7+]aze aprendendo a a[C7+]mar...
Só tenha um p[F7+]ouco mais de pac[Bm7]iência...
o amor nem ci[E/G#]ência consegue explicar...

[A7+]É o amor... Me desculpe se eu c[D7+]horar...
É o amor[G7+]... Não se preocupe vai p[C7+]assar...
É o amor..[F7+]. Eu sou muito men[Bm7]ino...
Mais calma que a pr[E/G#]essa é amiga do azar...
[A7+]É o amor... nunca pensei sofrer [D7+]assim...
É o amor... [G7+]É tão normal conf[C7+]ie em mim...
É o amor..[F7+]. Mais to tão preo[Bm7]cupado...
Eu to do seu [E/G#]lado não é tão rui[A7+]m...

Cifrado por Danilo Dias Pereira (Ganí)

{end_of_part}
