{title: Solo quedate en silencio}
{artist: Anahí}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-es, dance pop, latin pop, post-teen pop}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 27991
# Empreinte source SHA256: 42eef48f41bf88800a508a0e5a4aa6bca60d07371f391ecc210e07fe79b1d87f
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

te encuentro des[A]pierto
me dices [C#]lo siento, con una lag[B7]rima derramas...
me abrazas,[A] me hielo, me pid[C#]es un beso
y yo m[F#m]e quedo sin r[B7]espirar...
solo[Bm] espera un mo[C#]mento, solo[F#m] dime no es[C#m] cierto...

CORO
Solo [A]quedate en silencio cinc[F#m]o minutos...
acaric[Bm]iame un momento, ven ju[E]nto a mi...
te dare el u[A]ltimo beso, el ma[F#m]s profundo...
guarda[Bm]re mis sentimientos y me [E]ire lejos de [A]ti...

tengo t[A]anto miedo y es que [C#]no comprendo...
¿que [F#m]fue lo que yo he hech[B7]o mal?...
me [A]abrazas, me hielo[C#], me pides un beso
y yo m[F#m]e quedo sin r[B7]espirar...
solo[Bm] espera un mo[C#]mento, solo[F#m] dime no es[C#m] cierto...

se repite el coro...

dame tu mano, devuelv[C#m]eme el aire...
di que[F#m] me amas, que no [B7]eres culpable...
por lo meno[Bm]s un momento,dime que esto [E]no es cierto....
Solo qued[A]ate en silencio... el requinto
acariciame[Bm] un momento...
te dare[A] el ultimo beso...
guardare[Bm] mis sientimientos y [E]me ire lejos de [A]ti...

se repite otra ves el coro y termina asi
guardare[Bm] mis sentimientos y m[E]e ire lejos de ti[A]iii....
