{title: Para Alcanzarte}
{artist: Sin Bandera}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, latin, latin arena pop, latin pop, mexican pop}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 28588
# Empreinte source SHA256: 39451effd3552d359bfc0e2d13f3d2af95ed691797737d5bbe627748d82b28f9
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

PARA ALCANZARTE YO VO[Em]Y HA[G] CR[Am]UZAR EL MAR [B7]ENTERO [Em][G][Am][B7]
Y SI HAY [Em]MONT[G]AÑA[Am]S ME VOY A V[B7]OLAR CRUZANDO E[Em]L CI[G]EL[Am]O.U[B7]OH.OH
TRAS DE TUS P[Em]ASO[G]S V[Am]OY A DECRU[B7]BIR EL UNIVE[Em]RSO [G][Am][B7]
Y GRITA[Am]RE POR TODO EL [B7]MUNDO QUE TE QUIE[Em]RO..[G]..[Am]...[B7]TE QUI[Em]ERO.[G]UO[Am7]H..O[B7]H.OH

TE QUIERO.UOH..OH.OH

AH[Em]ORA QUE SE DONDE ES[B7]TAS Y QUE SE COMO [Em]HACER
PARA SER TAN FEL[B7]IZ VOY A LUCHAR POR TI
AH[Em]ORA QUE YA PROBE TU A[B7]MOR Y QUE DECUBRI QUIEN[Em] SOY
VOY HACABARME LOS CA[B7]MINOS ALCANZARTE
[Am]VOY H[B7]ACERTE SENTIR LO QUE ERES[Em] PAR[A7]A MI
VOY A V[C]IVIR POR [B7]TI

PARA ALCA[Em]NZAR[G]TE [Am]YO VOY HA CR[B7]UZAR EL MAR [Em]ENTE[G]RO[Am] (E[B7]L MAR EL MAR)
Y SI HAY [Em]MONT[G]AÑA[Am]S ME VOY A V[B7]OLAR CRUZANDO E[Em]L CI[G]EL[Am]O ([B7]ME VOY A VOLAR UOH OH)
TRAS DE TUS P[Em]ASO[G]S V[Am]OY A DECRU[B7]BIR EL UNIVE[Em]RSO [G](V[Am]OY [B7]A DESCUBRIR)
Y GRITA[Am]RE POR TODO EL [B7]MUNDO QUE TE QUIE[Em]RO [G][Am][B7]

[Em]SE QUE TE VOY A EXTRA[B7]ÑAR Y QUE VOY A LLO[Em]RAR
ALGUNA TARDE QUE TALV[B7]EZ YO PIERDA ALGUNA
[Em]PERO YO SE QUE AL FIN[B7]AL NUESTRO AMOR GAN[Em]ARA
PORQUE NO HAY NADA EN ESTE [B7]MUNDO TAN PROFUNDO
[Am]VOY H[B7]ACERTE SENTIR LO QUE ERES[Em] PAR[A7]A MI
VOY A MO[C]RIR POR [B7]TI

PARA ALCA[Em]NZAR[G]TE [Am]YO VOY HA CR[B7]UZAR EL MAR [Em]ENTE[G]RO[Am] (E[B7]L MAR EL MAR)
Y SI HAY [Em]MONT[G]AÑA[Am]S ME VOY A V[B7]OLAR CRUZANDO E[Em]L CI[G]EL[Am]O ([B7]ME VOY A VOLAR CRUZANDO EL CIELO)
TRAS DE TUS P[Em]ASO[G]S V[Am]OY A DECRU[B7]BIR EL UNIVE[Em]RSO [G](V[Am]OY [B7]A DESCUBRIR)
Y GRITA[Am]RE POR TODO EL [B7]MUNDO QUE TE QUIE[Em]RO  [G][Am][B7]

RIFF

[Am]VOY H[B7]ACERTE SENTIR LO QUE ERES[Em] PAR[A7]A MI
VOY A V[C]IVIR POR [B7]TI

(SUBE UN TONO)

PARA ALCA[F#m]NZAR[A]TE [Bm]YO VOY HA C[C#7]RUZAR EL MAR[F#m] ENTE[A]RO[Bm] (E[C#7]L MAR EL MAR)
                                               (VOY A VOLAR VOY A NADAR PARA ALCANZARTE)
Y SI HAY MO[F#m]NTAÑ[A]AS [Bm]ME VOY A V[C#7]OLAR CRUZANDO EL [F#m]CIELO[A]  [Bm][C#7]
TRAS DE TUS [F#m]PASO[A]S V[Bm]OY A DECRU[C#7]BIR EL UN[F#m]IVERS[A]O [Bm](VO[C#7]Y A DESCUBRIR)
Y GRIT[Bm]ARE POR TODO EL[C#7] MUNDO QUE TE QUIE[F#m]RO  [A][Bm][C#7]
Y GRIT[Bm]ARE POR TODO EL[C#7] MUNDO QUE TE QUIE[F#m]RO (Y[A] G[Bm]RIT[C#7]ARE POR TI)
Y GRIT[Bm]ARE POR TODO EL[C#7] MUNDO QUE TE QUI[F#m]ERO
