{title: High Life}
{artist: Brad Paisley}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, contemporary country, country, country road}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 34467
# Empreinte source SHA256: 020f43d3a57d0a38cb4312dce9587f9ca3cb00e1be831fa128fc79d6d50d14e6
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

            HIGH LIFE - BRAD PAISLEY
Tabbed by Kyle K

[C]I CAN STILL REMEMBER WHEN
GRANDPA DIED AND OUR [G]SHIP CAME IN
DADDY SAID HE LEFT [F]MOMMA AND HIM
MORE [Dm]MONEY THAN WE?D EVER [G]SEEN

[C]AND JUST LIKE THAT
WE WERE [F]THOUSANDAIRES
HAD A [C]BRAND NEW BOAT
AND [G]FRIGID AIR
AND [Am]ALL US KIDS IN OUR [F]UNDERWEAR
WERE [G]JUMPING ON A TRAMPOLINE

A BUNCH OF [F]LOWLIFES
LIVING THE [C]HIGH LIFE
MONEY BURNING A [G]HOLE RIGHT
THROUGH THE POCKETS OF OUR HOLEY [C]JEANS

[C]GRANDPA?S WITH THE [F]LORD NOW
BUT WE GOT A NEW [C]FORD NOW
AND WE CAN WATCH THE BIG [G]ORANGE NOW
ON A 57 INCH T[C]V

[C]THAT?S RIGHT [F][C][F][C]

THE [C]MONEYS GONE BY MID [F]JULY
[C]WE WENT BACK TO JUST GETTING BY
TIL [F]MOMMA SLIPPED ON A PATCH OF ICE
[Dm]OUTSIDE A CHICK FIL [G]A

 NOW[C] WE KNEW THEY WAS A[F] CHRISTIAN BUNCH
 [C]SO WE DIDN?T ASK FOR [G]ALL THAT MUCH
 SETTLED [Am]OUTTA COURT FOR 10 [F]THOUSAND BUCKS
 AND FREE [C]CHICKEN TILL OUR DYING DAY

A BUNCH OF [F]LOWLIFES
LIVING THE [C]HIGH LIFE
MONEY BURNING A [G]HOLE RIGHT
THROUGH THE POCKETS OF OUR HOLEY [C]JEANS

[C]MOMMA?S GOT A [F]LIMP NOW
BUT WE ALL GET TO [C]SWIM NOW
[F]CAUSE WE GOT AN ABOVE [C]GROUND
SITTIN [G]OUT BY THE [C]TRAMPOLINE

YEAH WE DO

[C]WE ROCKED WE [F]ROLLED
WE LIVED IT UP TILL
IT [G]STARTED RUNNING THIN
[Am]WE BEGAN LOOKING [F]FOR A WAY
TO [G]SPEND THAT MONEY AGAIN

[C]I HEARD A SONG A COUPLE MONTHS AGO

WAS CARRIE UNDERWOOD ON THE RADIO
[F]REMINDED ME OF A POEM MY BROTHER WROTE
[Dm]BACK IN SECOND [G]GRADE
AND I KNOW SHE DIDN?T STEAL IT BUT
[C]SO WHAT WE LAWYERED UP AND [G]SUED HER BUTT

THESE [Am]DAYS WE FIGURED WE?D [F]PRETTY MUCH
GET [C]PAID TO GO AWAY

A BUNCH OF [F]LOWLIFES

LIVING THE [C]HIGH LIFE
MONEY BURNING A [G]HOLE RIGHT
THROUGH THE POCKETS OF OUR HOLEY [C]JEANS

[C]THIS SONGS A NUMBER [F]ONE NOW
GONNA GET A HOT [C]TUB NOW
[F]SIT IT NEXT TO THE [C]ABOVE GROUND
WHICH IS [G]NEXT TO THE TRAMPO[C]LINE

[C]IT?S GONNA RUN OUT [F]SOMEDAY
AND THAT AIN?T GONNA BE A [C]FUN DAY
[F]BUT AS LONG AS IT AIN?T A [G]SUNDAY
WE CAN GO TO CHICK FIL A AND [C]EAT

[C]ME I LOVE THEM WAFFLE FRIES
[G]THAT CHICK FIL A?S GOT SOME GOOD WAFFLE FRIES

ID SAY THATS RIGHT
MAYBE I?LL GET A [C]DIET COKE  I DON?T KNOW
[F]I WISH THEY HAD BEER IT WOULD BE PERFECT
[C]I LIKE THE LITTLE TRAYS THAT THE [G]FOOD COMES ON
[C]I LIKE THE POLYNESIAN SAUCE
