{title: Soy loco por ti, America}
{artist: Ivete Sangalo}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, axe, funk carioca, mpb, pagode, pop nacional, samba reggae}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 42750
# Empreinte source SHA256: 02adf9d5acc8fa23d6bc90e44fe4a5685847116b8860fc4e8a3a246bd3e54076
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

[F#m] [B] [E] [F] [F#m] [B] [E] [F] [F#m] [Am] [E]

SOY LOCO POR TI, AM[A/B]ERICA YO VOY TRAER UNA [E]MUJER PLAYERA
QUE SU NOMBRE SEA M[A/B]ARTI, QUE SU NOMBRE SEA MA[E]RTI
SOY LOCO POR TI DE AM[A/B]ORES TENGO COMO COL[E]ORES LA ESPUMA
BLANCA DE LATINO[A/B]AMERICA Y EL CIELO COMO BAND[E]EIRA
Y EL CI[F#m]ELO C[Am]OMO BAND[E]EIRA
SOY LOCO POR TI, AME[A/B]RICA SOY LOCO POR TI DE AM[E]ORES
SORRISO DE QUASE NU[A/B]VEM, OS RIOS CANCOES, O M[E]EDO
O CORPO CHEIO DE EST[A/B]RELAS O CORPO CHEIO DE EST[E]RELAS
COMO SE CHAMA A AM[A/B]ANTE DESSE PAIS SEM N[E]OME

ESSE TANGO, ESSE RANCHO
ESSE POVO DIZ[A/B]EI-ME, ARDE O FOGO DE CONHE[E]CE-LA
O F[F#m]OGO D[Am]E CONHEC[E]E-LA
SOY LOCO POR TI AME[A/B]RICA SOY LOCO POR TI DE AMO[E]RES

{comment: À vérifier : solo.C#m Bm Em Dm C#m Bm Dm E}
# SOURCE A VERIFIER: solo.C#m Bm Em Dm C#m Bm Dm E 
EL NOMBRE DEL HOMBRE MU[A/B]ERTO YA NO SE PUEDE
DEC[E]IRLO, QUIEN SABE
ANTES QUE O DIA ARREB[A/B]ENTE, ANTES QUE O DIA ARREB[E]ENTE
EL NOMBRE DEL HOMBRE MU[A/B]ERTO
ANTES QUE A DEFINIT[E]IVA NOITE SE ESPALHE EM LATINOA[A/B]MERICA
EL NOMBRE DEL HOMBRE ES PU[E]EBLO,EL NO[F#m]MBRE DEL HO[Am]MBRE ES PU[E]EBLO
SOY LOCO POR TI AM[A/B]ERICA SOY LOCO POR TI DE AMO[E]RES
ESPERO QUE AMANHA QUE CA[A/B]NTE EL NOMBRE DEL HOMBRE MU[E]ERTO
NAO SEJA PALAVRAS TR[A/B]ISTES
SOY LOCO POR TI DE AMO[E]RES
UM POEMA AINDA EX[A/B]ISTE COM PALMEIRAS, COM TRINCH[E]EIRAS
CANCOES DE GUERRA QUEM SABE C[A/B]ANCOES DO MAR, AI,
H[G#m]ASTA [F#m]TE COMOV[E]ER, AI H[F#m]ASTA T[Am]E COMO[E]VER
SOY LOCO POR TI AME[A/B]RICA SOY LOCO POR TI DE AMO[E]RES
ESTOU AQUI DE PAS[A/B]SAGEM, SEI QUE ADIANTE UM DIA V[E]OU MORRER
DE SUSTO, DE BALA VI[A/B]CIO, DE SUSTO, DE BALA OU V[E]ICIO
NUM PRECIPICIO DE L[A/B]UZES ENTRE SAUDADE, SOL[C#m]UCOS,
EU VOU MORR[C#7]ER DE BRUCOS
NOS BR[F#m]ACOS, NOS OLHOS, NOS BR[B]ACOS DE UMA MUL[E]HER
NOS BR[F#m]ACOS DE U[Am]MA MULH[E]ER
MAIS APAIXONADO A[A/B]INDA D[C]ENTRO DOS BRACOS DA C[C#m]AMPONESA
GUERRIL[C#7]HEIRA MANE[F#m]QUIM, AI DE MIM, NOS BR[B]ACOS
DE QUEM ME QU[E]EIRA NOS B[F#m]RACOS [Am]DE QUEM ME QU[E]EIRA
SOY LOCO POR TI AM[A/B]ERICA SOY LOCO POR TI DE AM[E]ORES
