{title: Festa Do Estica E Puxa}
{artist: Xuxa}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, musica infantil, musica para criancas}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 111279
# Empreinte source SHA256: 96361ad04176f74303c11769493494b7a0dbe4f29407aa3f0bb60ac98b914745
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tonalite_absente

[Bb]Lô galera nós va[Cm]mos curtir agora a maior festa do [Ab]ano,[G] [Cm]
é f[Bb]esta do estica e pux[Cm]a...
e não é que é a festa da x[Ab]uxa...é [G]da xu.[Cm]..

e todos dançam[Bb], o pega, estica e puxa... [Cm]
[Ab]e viva a fe[G]sta da xuxa ( 2x [Cm])

lá[G] o cãozinho... au...au[Cm]...
não briga com o gatinho...[G] miau ( 2x ) [Cm]

o dengue conta d[Bb]e um até trê[Cm]s,
as brincadeir[Ab]as come[G]çam de uma [Cm]vez...

e todos dançam[Bb], o pega, estica e pux[Cm]a...
[Ab]e viva a fe[G]sta da [Cm]xuxa ( 2x )

tem pingÃ[Bb]¼im tomando sau[Cm]na...
o papag[Bb]aio falador, só pede [Eb]calma.
scoobydoo.[Bb].. fica calado[Cm]...pra v[Ab]er qual é[G]...
enquanto a praga pega o [Cm]pé...

e todos dançam[Bb], o pega, estica e pu[Cm]xa...

[Ab]e viva a fe[G]sta da [Cm]xuxa ( 2x )

e os ba[Bb]ixinhos vão chegando numa nave e[Cm]spacial...
te[Bb]m até um escoteiro, vestido de gene[Cm]ral...
[Bb]o he-man, dança um rock, gravado por tom job[Cm]im...
e[Bb]nquanto a she-ha namorava o[Ab] esqueleto,[G] no jar[Cm]dim...

e todos [Bb]dançam, o pega, estica e [Cm]puxa...
[Ab]e viva a fe[G]sta da [Cm]xuxa ( 2x )

lá[G] o cãozinho... a[Cm]u...au...
não briga com o gatinho... m[Cm]iau ( 2x )

o dengue [B]conta de um até t[Cm]rês,
as brincad[Ab]eiras c[G]omeçam de uma [Cm]vez...

e todos dançam[Bb], o pega, estica e [Cm]puxa...
[Ab]e viva a fe[G]sta da xu[Cm]xa ( 2x )

tem pingÃ[Bb]¼im tomando [Cm]sauna...

[Bb]o papagaio falador, só pede ca[Eb]lma..
scoo[Bb]bydoo... fica[Cm] calado...pra[Ab] ver qual[G] é...
enquanto a praga pega o [Cm]pé...

e todos da[Bb]nçam, o pega, estica e [Cm]puxa...

[Ab]e viva a fe[G]sta da x[Cm]uxa ( 2x )

e os ba[Bb]ixinhos vão chegando numa nave esp[Cm]acial...
te[Bb]m até um escoteiro, vestido de gen[Cm]eral...
[Bb]o he-man, dança um rock, gravado por tom j[Cm]obim...
e[Bb]nquanto a she-ha n[Ab]amorava o esq[G]ueleto, no ja[Cm]rdim...

E todos dançam[Bb], o pega, estica [Cm]e puxa...
[Ab]e viva a fe[G]sta da xu[Cm]xa  ( 2x )

{start_of_part: Solo}
[Bb] [Cm] [Ab] [G]
[Bb] [Cm] [Ab] [G] [Cm]

e[Bb] todos dançam, o pega, estica e pu[Cm]xa...
[Ab]e viva a fe[G]sta da xu[Cm]xa  (4x )

{end_of_part}
