{title: Sexo}
{artist: Oswaldo Montenegro}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, mpb}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 114224
# Empreinte source SHA256: 6b08f48bfd886f215b141d1d2ca92c896638ff15b024f49b9b56555733c1bfe5
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : INTRODUÇÃO: ( E A ) 2X}
# SOURCE A VERIFIER:             INTRODUÇÃO: ( E A ) 2X 
[E] SEJA QUAL F[A]OR O TEMA O QUE TE IMPORTA É [E]SEXO
SEJA ALEG[A]RIA, ANGÚSTIA, CHORO, ENCANTO OU [E]DOR
SEJA DE AUS[A]ÊNCIA, SONHO, TARA OU POR COM[E]PLEXO
SEJA NA [A]CAMA, PALCO ESCADA, ELEVADO[E]R
ESTÁ NO [G]LEITO FLUIDO Q[A]UE ESCORREU DO [E]RALO
ESTÁ NO [G]OLHAR DE SAL DE J[A]ACK, O ESTRIPA[E]DOR
E VEM DO [G]FUNDO DA GARR[A]AFA PRO GARG[E]ALO
ESTÁ NO [G]RISO OBRIGAT[A]ÓRIO E NO VAPO[E]R
É O OLH[D]AR DE SAL DE J[A]ACK, O ESTRIPADO[E]R

{start_of_part: SOLO}
[E]
[E] EU PENSO M[A]AIS NA TUA PELE A NA TUA L[E]ÍNGUA
DO QUE NA [A]ALMA QUE TEU OLHO ME MEST[E]ROU
É SEM TEU [A]CORPO QUE MINH'ALMA FICA À [E]MÍNGUA
É NO TEU [A]SEIO QUE CONCERTO O QUE QUEB[E]ROU
E QUANDO [G]FALO DA TUA L[A]UZ ASSIM, QUEM D[E]ERA
ELA ACEND[G]ESSE EM MIM O [A]SANTO QUE NÃO [E]SOU
MAS ILUM[G]INA EM MEU OLH[A]AR O OLHAR DA [E]FERA
QUE ENTRE TUAS [G]PERNAS CARNE S[A]Ã DESPEDAÇO[E]U
É OL[D]HAR DE SAL DE J[A]ACK, O ESTRIPADO[E7/9+]R
[E] O QUE EU MARQUE[A]I NA TUA PELE NÃO SE [E]LAVA
PODE SER [A]CHEIRO, EMATOMA OU CICATRI[E]Z
É PELO [A]SEXO QUE MEU SOL TE FAZ [E]ESCRAVA
QUER SEJA [A]SANTA, CIDADÃ OU MERETRI[E]Z
SE PERGUNT[G]AREM PELO IRM[A]ÃO NÃO ME AP[E]ONTE
PRA DESFAR[G]ÇAR ESCRAVA NA[A] CHUVA COM O [E]GIZ
QUE MINHA F[G]ACA DESFIBRO[A]U SEU HORIZ[E]ONTE
RASGANDO A [G]PELE DA PAIS[A]AGEM POR UM [E]TRIZ
É A ESC[D]OLHA ENTRE SER[A] CALMO E SER FEL[E]IZ

{end_of_part}
{start_of_part: SOLO}
[E7] [E]
[E]SEJA QUAL F[A]OR O TEMA O QUE TE EMPORTA É S[C#m]EXO
SEJA CAB[A]ALA, UMBANDA, HERÓI OU DESERT[E]OR
SEJA LOUC[A]URA, DE VERDADE, OU TENHA [C#m]NEXO
SEJA OU NAO [D]SEJA, OU SEJA, [A]SEJA O QUE FO[E]R
SEJA DANÇ[G]AR NO VENTO, AR[A]EIA OU TEMPEST[E]ADE
SEJA NO [G]SONHO SEJA [A]NO QUE DESPER[E]TOU
SEJA UMA [G]FLOR OU SEJA ALGUÉ[A]M NA FLOR DA ID[E]ADE
É O PERD[G]ÃO AO LOBO Q[A]UE TE ABOCANHO[E]U
É OLHA[D]R DE SAL DE J[A]ACK, O ESTRIPADO[E]R

{end_of_part}
