{title: The right Kind of Wrong}
{artist: LeAnn Rimes}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, country, country dawn, dance pop, pop rock}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 57102
# Empreinte source SHA256: 5d2dd08111ab0d683d12fcdc6b0b459f6e76c800727af7012a9dc73dce07443d
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

I KNOW ALL A[Bm]BOUT, 'BOUT Y[G]OUR REP[D]UTATION[A]
AND H[Bm]OW IT'S B[G]OUND TO BE A H[A]EARTBREAK SITUATION
[Bm]BUT I CAN'T H[G]ELP IT IF I'M H[A]ELPLESS
EVERYTIME THAT I'M WH[Bm]ERE Y[G]OU [A]ARE

YOU WALK [G]IN AND MY STRENGTH WALKS [A]OUT THE DOOR
SAY MY N[G]AME AND I CAN'T FIGHT [A]ANYMORE
OH I KN[G]OW I SHOULD G[D]O
BUT I N[A]EED YOUR TOUCH JUST TOO DAMN MUCH

L[Bm]OVING YOU [G]  [A]  ISN'T REALLY SOMETHING [Bm]I SHOULD DO[G][A]
SHOULDN'T WANNA SPEND MY T[Bm]IME WITH YOU [G][A]
I SHOULD TRY TO BE STR[Bm]ONG [G] BUT B[A]ABY,
YOU'RE THE RIGHT KIND OF WR[Bm]ONG  [G]  B[A]ABY
YOU'RE THE RIGHT KIND OF WR[Bm]ONG

MIGHT BE A MIST[G]AKE,[D] A MISTAKE I'M M[A]AKING
B[Bm]UT WHAT YOU'RE G[G]IVING I AM H[A]APPY TO BE TAKING
[Bm]'COZ NO-ONE'S [G]EVER MADE ME F[A]EEL THE WAY I FEEL
WHEN I'M [Bm]IN Y[G]OUR [A]ARMS

THEY SAY Y[G]OU'RE SOMETHING I SHOULD D[A]O WITHOUT
THEY DON'T KN[G]OW WHAT GOES ON WHEN THE L[A]IGHTS GO OUT
THERE'S NO W[G]AY TO EXPL[D]AIN
ALL THE PL[A]EASURE IS WORTH ALL THE PAIN

[Bm]LOVING YOU[G]  [A]   ISN'T REALLY SOMETHING[Bm] I SHOULD DO[G][A]
SHOULDN'T WANNA SPEND MY T[Bm]IME WITH YOU[G] [A]
I SHOULD TRY TO BE STR[Bm]ONG [G] BUT B[A]ABY,
YOU'RE THE RIGHT KIND OF WR[Bm]ONG  [G]  B[A]ABY
YOU'RE THE RIGHT KIND OF W[G]RONG

[G]I SHOULD TRY TO RUN
BUT [D]I JUST CAN'T SEEM TO
'C[G]OZ EVERY TIME I RUN YOU'RE THE [D]ONE I RUN TO
[G]I CAN'T DO WITHOUT [D] WHAT YOU DO TO ME
I D[A]ON'T CARE IF I'M IN TOO DEEP

[Bm]I KNOW ALL AB[G]OUT, 'B[D]OUT YOUR REPUT[A]ATION
[Bm]AND HOW IT'S B[G]OUND TO BE A H[A]EARTBREAK SITUATION
[Bm]BUT I CAN'T H[G]ELP IT IF I'M H[A]ELPLESS
EVERYTIME THAT I'M WH[Bm]ERE Y[G]OU [A]ARE

YOU WALK [G]IN AND MY STRENGTH WALKS [A]OUT THE DOOR
SAY MY N[G]AME AND I CAN'T FIGHT [A]ANYMORE
OH I KN[G]OW I SHOULD G[D]O
BUT I N[A]EED YOUR TOUCH JUST TOO DAMN MUCH  [A]  yeeeaahhh

[Bm]LOVING YOU[G]  [A]   ISN'T REALLY SOMETHING[Bm] I SHOULD DO[G][A]
SHOULDN'T WANNA SPEND MY T[Bm]IME WITH YOU [G][A]
I SHOULD TRY TO BE STR[Bm]ONG [G] BUT B[A]ABY,
YOU'RE THE RIGHT KIND OF WR[Bm]ONG  [G]  B[A]ABY
YOU'RE THE RIGHT KIND OF W[Bm]RONG[G]
B[A]ABY YOU'RE THE RIGHT KIND OF WR[Bm]ONG[G]
n/c
BUT BABY YOU'RE THE RIGHT KIND OF WRONG
