{title: Mais tempo pra você}
{artist: Imaginasamba}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, funk carioca, pagode, pagode novo}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 116024
# Empreinte source SHA256: 5d6cb789c849299923527e46c22b885f11dc72fd4a3e9b2ad4e4862eeddf066b
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, ponctuation_chordpro_neutralisee, tabulations_interpretees_4_colonnes, tonalite_absente

{start_of_part: Intro}
[A7+] [Dm6] [D/F#] [Bm7/11] [Esus4]

Q[A7+]ue susto que eu lev[A5+]ei...quando [A6]voçê...pediu um tem.[A5+]..po...
[A7+]Por um momento ach[Dm6]ei...ter acaba..[C#m7].do o sentimen.[C#7]..to...
[F#m]A tua solidão..[F#m7+].eu não[Bm]...podia ver...
[E7/9]Não vi que o meu tempo...era[Bm7/11] pouco pra[Esus4] voçê...
[A7+]   *   Querendo co[A5+]nstruir...um[A6] bom futu...ro pra nós do...is
[E7/9]Eu quase destruí...o que n[C#m7]ós te...mos de mais l[G#m7/5-]in...do.[C#7]..
[F#m]Agora deixo [F#m7+]os...meus compr[Bm]omis...sos pra depo...is....
[E7/9]Pra poder ficar[E7] mais..[A9/7+]...tem....po cont[F#7/5+]i...go....
[Bm]Pode...mos [Bm7+]sair....ir a[Bm7]o cine...ma e [Bm7]mais[F#7/5+] ain...da...
[C#m]Buscar emoção...nas coisas [F#7/9]ma...is simples da[A7/5+] vi...da....
[Dm]Com certeza ace[Dm6]nder...n[Bm7]ossa paixão[E7(9/11)].....

De ho.[A7+].je em..[C#m7]dian...te[Bm7]....  vou viver mais pr[C#m7]a voçê....
[F#m]Vou deixar meu cora[F#m7+]ção.....t[Bm7]e entender.[E7(9/11)]..........
{comment: À vérifier : A7+ C#m7 Bm7 C#m7 (Refrão)}
# SOURCE A VERIFIER:       A7+         C#m7     Bm7                  C#m7                   (Refrão)                                
De ho..je em..dian...te....  vou viver mais pra voçê....
# SOURCE A VERIFIER: Bm                   Esus4               { INTRODUÇÃO, depois volta no * }                                                                                                     
Bm                   Esus4               ｛ INTRODUÇÃO, depois volta no * ｝
Vou deixar meu coração.....te entender...........

OBS: O que está entre colchetes é "OPCIONAL"

{end_of_part}
