{title: Separação}
{artist: Amado Batista}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, sertanejo, sertanejo universitario}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 71056
# Empreinte source SHA256: cc1fb3696d9ea51e2e14688a1e9eeea6a45e4479dd04a36c6aa3f8f5c9053144
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

já faz muito[E]s anos, que nos separamo[A]s...
ma[B]s só nós dois sa[F#]bemos...
o quanto nos am[B7]amos...
[E]você não teve juízo
na[A] solidão me deixou...
mas [B]já fiquei sa[F#]bendo...
que[A] quando  me viu... choro[E]u... [B7]
[E]como posso me acostumar? te v[A]er como novo amor... se[B]i que quando vai do[F#]rmir, abraçando outro
[B7]corpo...
[E]eu vou tentar esquecer... nossos[A] beijos, nossas bocas... mu[B]rmurando no silenc[F#]io...
[A]isso é o que me faz so[E]frer...[E7]

{start_of_chorus: REFRAO}
[A]acordei de madrug[E]ada...
pen[D]sativo ao [A]olhar...
nossas coisas desprez[E]adas...
que [D]você dei[E]xou de [A]amar...
suas roupas tão bon[E]itas...
que só[D] lhe faz reco[A]rdar...
e o cheiro do seu perf[E]ume... que[D] ainda est[E]á no a[A]r..[B7].
[E]se um dia se arrepender...
[A]de tudo o que fez comigo...
v[B]olte, pois a casa é[F#] sua...
tens aqui paz e[B7] abrigo...
[E]vou ficando por aqui...
[A]por você a esperar...
q[B]uero sentir a[F#] alegria...
[A]se um dia você v[E]oltar...[B7]
[E]nem que as pessoas sejam contra...
[A]nem que o mundo diga não...
[B]vou tentando apro[F#]ximar-me...
nem que seja [B7]ilusão...
[E]depois de tanto tempo juntos...
[A]e tanto tempo separados...
[B]o inocente está[F#] pagando...
[A]pelo que fizemos de [E]errado...

{end_of_chorus}
{start_of_chorus: REFRAO}

{end_of_chorus}
