{title: El Actor}
{artist: Los Apson}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, mexican rock-and-roll, ranchera}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 115459
# Empreinte source SHA256: 8de2b2b851edd0de934630b714e6795add0ea3273c1c7f5410c715d92185f5d8
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

[E] [E] [E] [E]
[E]A VECES PIENSO QUE ME HICISTE UN GRAN FAVOR,
[A]PUES ME HA SERVIDO LA EXPERIENC[E]IA DE TU AMOR
[B]HOY PUEDES VERME YA T[A]RIUNFANDO C[E]OMO ACTOR
[E]ME ENAMORE DE TI Y FUI TAN FELIZ
[E]MAROMA, CIRCO Y TEATRO ME  HICISTE PROBAR
[A]POR TI, UU,[E] POR TI,
[B]LE HICE TANTO AL TEATRO Q[A]UE UN GRAN A[E]CTOR ME VOLVI
[E]PUES YO TE QUERIA EN SERIO CONQUISTAR
[E]Y HACIENDO PAYASADAS LO PUDE LOGRAR
[A]POR TI, SII[E], POR TI
[B]LE HICE TANTO AL TEATRO Q[A]UE UN GRAN A[E]CTOR ME VOLVI
[E]RECUERDO MUY BIEN CUANDO ME DECLARE
[E]A MITAD DE LA CALLE EL TROPICO PARE
[A]POR TI, UU,[E] POR TI
[B]LE HICE TANTO AL TEATRO Q[A]UE UN GRAN A[E]CTOR ME VOLVI
[E]ME RECUERDO TAMBIEN QUE A DIARIO TE LLEVE
[E]SERENATAS DE VIOLIN DURANTE MÁS DE UN MES
[A]POR TI, AAA[E], POR TI
[B]LE HICE TANTO AL TEATRO Q[A]UE UN GRAN A[E]CTOR ME VOLVI
[E]DE CHISTE EMPECÉ TUS BESOS A ROBAR,
[E]Y LUEGO NADIE NADIE NOS PODIA PARAR
[A]POR TI, AAA[E], POR TI
[B]LE HICE TANTO AL TEATRO Q[A]UE UN GRAN A[E]CTOR ME VOLVI
[E]MAS TODO EN LA VIDA DEBE UN DIA ACABAR
[E]TAMBIEN NUESTRO CARIÑO LLEGO HASTA EL FINAL
[A]POR TI, YYY[E], POR TI
[B]LE HICE TANTO AL TEATRO Q[A]UE UN GRAN A[E]CTOR ME VOLVI
[E]PUES YO TE QUERIA EN SERIO CONQUISTAR
[E]Y HACIENDO PAYASADAS LO PUDE LOGRAR
[A]POR TI,[E] AAA, POR TI
[B]LE HICE TANTO AL TEATRO Q[A]UE UN GRAN A[E]CTOR ME VOLVI
[E]RECUERDO MUY BIEN CUANDO ME DECLARE
[E]A MITAD DE LA CALLE EL TROPICO PARE
[A]POR TI, UUU[E], POR TI
[B]LE HICE TANTO AL TEATRO Q[A]UE UN GRAN A[E]CTOR ME VOLVI

[B] [E]
