{title: De Bobeira}
{artist: Exaltasamba}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, funk carioca, pagode, samba paulista, sertanejo, sertanejo universitario}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 134652
# Empreinte source SHA256: 8dfea23c926e86afa0ee4ffb3dac14dac78bf9c9a90760f6ce16757b8528a465
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : Introdução: A7+ - F7+ - Bm7/5- - F#7+ - E7}
# SOURCE A VERIFIER:             Introdução:  A7+ - F7+ - Bm7/5- - F#7+ - E7

T[Am7/9]e amar........é[Bm7/5-] tudo que eu sonh[E7/9]ei..........
[Am7/9]Mas sei lá........[Gm].eu não imagi[C7/9]nei .............
[F7+]Que o a[F6]mor..........[Gm]fosse me encarcer[C7]ar..........
[F7+]E me fazer sofr[E7/9]er........
[Am7/9]Qual será.........[Bm7/5-].o preço que pag[E7/9]uei...........
[Am7/9]Pois num mar...........[Gm].. de sonhos mergulh[C7/9]ei.............
[F7+]E o medo em[F6] mim ..........[Dm] foi de chegar à conclu[G7]são............
[C6/9]Que o amor é [C7/9]assim
[F7+]Me entreguei à ilu[E7/9]são
[A7+]De bob[A6]eira você[D]........deu manc[E7/9]ada..........
[A7+]Aposte[A6]i........ toda a[Dm] nossa jorn[G7]ada..........
[C6/9]E pare[C7/9]i com a r[F7+]apazia[G7]da.........
[C6/9]Pra fic[Am]ar com vo[D]cê......... minha am[E7/9]ada
