{title: Jesus Verbo No Sustantivo}
{artist: Ricardo Arjona}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, cantautor, latin, latin arena pop, latin pop, rock en espanol, tropical}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 11926
# Empreinte source SHA256: 70158f37867600542ec04db485d322f5154b40787080e0eb746e69bcaa3f5524
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

JESUS ES MAS QU[D]E UNA SIMPLE Y LLANA[A] TEORÃA, Â¿QUE[Bm] HACES HERMAN[G]O LEYENDO LA B[A]IBLIA TODO EL DIA[D]?

LO Q[G]UE AHI ESTA ESCRITO SE RE[A]SUME EN AM[D]OR VAMOS [F#m]VE Y PRACT[Bm]ÃCALO,

JES[G]US HERMANOS MIOS ES V[A]ERBO NO SUSTANT[D]IVO.

JES[D]US ES MAS QUE UN TEMPLO DE L[A]UJO CON TENDENCIA BARR[Bm]OCA,

EL S[G]ABE QUE TOTAL A LA L[A]ARGA ESTO NO ES MAS Q[D]UE ROCA,

LA IGL[G]ESIA SE LLEVA EN EL A[Bm]LMA Y EN LOS AC[D]TOS [F#m]NO SE TE OLV[Bm]IDE,

QUE J[G]ESUS HERMANOS MIOS ES V[A]ERBO NO SUSTANT[D]IVO.

JES[D]US ES MAS QUE UN GRUPO DE SEÃ[A]?ORAS DE MUY NEGRA CON[Bm]CIENCIA,

QUE PRETE[G]NDEN GANARSE EL CI[A]ELO CON CLUB DE [D]BENEFICENCIA

SI QUI[G]ERES SER TU MIEMBRO ACT[A]IVA TENDRAS QUE P[D]RESENTAR A [F#m]LA DIRECT[Bm]IVA,

TU CU[G]ENTA DE AHORROS EN S[A]UIZA Y VINCULOS OFICI[D]ALES.

JES[D]US ES MAS QUE PERSIN[A]ARSE HINCARSE Y HAC[Bm]ER DE ESTO ALARDE,

EL S[G]ABE QUE QUIZAS POR D[A]ENTRO LA CONCIENCIA LES [D]ARDE,

JES[G]US ES MAS QUE UNA F[A]LOR EN EL ALT[D]AR SALVAD[F#m]ORA DE PEC[Bm]ADOS,

JES[G]US HERMANOS MIOS ES VE[A]RBO, NO SUSTANT[D]IVO.

JES[D]US CONVERTIA EN H[A]ECHOS TODOS SUS SERM[Bm]ONES, QUE SI T[G]OMAS CAFE ES PEC[A]ADO DICEN LOS MORM[D]ONES,

TIENEN T[G]AN POCO QUE HAC[A]ER QUE ANDAN INVENT[D]ANDO [F#m]CADA [Bm]COSA,

JES[G]US HERMANOS MIOS ES V[A]ERBO NO SUSTANT[D]IVO.

JES[D]US NO ENTIENDE POR QU[A]E EN EL CULTO LE APL[Bm]AUDEN, HABLAN D[G]E HONESTIDAD SABI[A]ENDO QUE EL DIEZMO

ES UN FRA[D]UDE.

A JES[G]US LE DA ASCO EL PAST[A]OR QUE SE HACE R[D]ICO [F#m]CON LA [Bm]FE,

 JES[G]US HERMANOS MIOS ES V[A]ERBO NO SUSTANT[D]IVO.

DE MI B[D]ARRIO LA MAS RELIGI[A]OSA ERA DOÃ?A CAR[Bm]LOTA, QUE HAB[G]LABA DE AMOR AL P[A]RÃ?JIMO Y ME PONCHO[D] 100 PELOTAS,

DESDE N[G]IÃ?O FUE APREND[A]IENDO QUE LA RELIG[D]ION NO ES[F#m] MAS QUE UN[Bm] MÃ?TODO,

CON EL T[G]ITULO: 'PROHIBIDO PENS[A]AR QUE YA TODO ESTA ESCR[D]ITO'

ME BAUTIZ[D]ARON CUANDO TENIA DOS M[A]ESES Y A MI NO ME AVIS[D]ARON,

HUBO FI[G]ESTA PIÃ?ATA Y A [A]MI NI ME PREGN[D]TARON.

BAUTI[G]ZAME TU JES[A]US POR FAV[D]OR AS[F#m]I ENTRE AM[Bm]IGOS,

SE QUE [G]ODIAS EL PROTO[A]COLO HERMANO M[D]IO.

SEÃ[D]?ORES NO DIVIDAN LA [A]FE LAS FRONTERAS SON P[Bm]ARA LOS PAISES,

EN ESTE M[G]UNDO HAY MAS RELIGI[A]ONES QUE NIÃ?OS FE[D]LICES.

JESUS PENS[G]Ã? ME HARÃ? INV[A]ISIBLE PARA QUE[D] TODO[F#m]S MIS HE[Bm]RMANOS,

DEJEN DE ESTAR HABL[G]ANDO TANTO DE M[A]I Y SE TIENDAN LA M[D]ANO

JES[D]US ERES EL MEJOR TEST[A]IGO DEL AMOR QUE TE PRO[Bm]FESO,

TEN[G]GO LA CONCIENCIA TRANQU[A]ILA POR ESO NO ME CONF[D]IESO,

REZ[G]ANDO DOS PADRES NU[A]ESTROS EL ASES[D]INO NO REV[F#m]IVE A SU MU[Bm]ERTO

JES[G]US HERMANOS MIOS ES V[A]ERBO NO SUSTANT[D]IVO.

JES[D]US NO BAJES A LA T[A]IERRA QUEDATE ALLÃ AR[Bm]RIBA,

TODOS L[G]OS QUE HAN PENSADO COMO T[A]U HOY ESTAN BOCA ARR[D]IBA,

OLVID[G]ADOS EN ALGUN CEMENT[A]ERIO DE EQUI[D]PAJE [F#m]SUS IDE[Bm]ALES,

MURI[G]ERON CON LA SONRISA EN LOS L[A]ABIOS POR QUE FUERON VERBO Y NO....

SUSTANT[D]IVO......
