{title: Escapar}
{artist: Kudai}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-es, latin, latin pop}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 94721
# Empreinte source SHA256: fa18a33a7043eda129d6195873af81407451f182684359895533c50d9c9cdf93
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

Veo sombras [C]que [G]se apagan [F]
[C]de mil [G]fotos de la [F]piel
[C]mil rec[G]uerdos que se ac[F]aban
[C]que de un[G] sueño aun pod[F]ré ....

Quiero escap[C]ar y desper[Em]tar sin sa[A]ber del[A7] tiempo...
Quiero r[F]espirar sin nunca [Fm]regresar ...
y quiero [C]vivir , quiero exi[Em]stir , sentir [A]el sil[A7]encio...
Ya no q[F]uiero hablar... Solo [Fm]quiero encontrar, un dia de p[C]az...

[C]Veo las [G]calles del ma[F]ñana
[C]veo la [G]ausencia del [F]ayer...
y mil sue[C]ños , que se f[G]ueron
mil hist[F]orias que se hun[Fm]dieron
como b[C]arcos , que se p[G]ierden en el [F]mar...

Quiero escap[C]ar y desper[Em]tar sin sa[A]ber del[A7] tiempo...
Quiero r[F]espirar sin nunca [Fm]regresar ...
y quiero [C]vivir , quiero exi[Em]stir , sentir [A]el sil[A7]encio...
Ya no q[F]uiero hablar... Solo [Fm]quiero encontrar, un dia de p[C]az...

{start_of_part: SOLO}
[C] [G] [F] [Fm]
[C] [G] [F] [Fm]
[C] [G] [F]

CORO:
Quiero escap[C]ar y desper[Em]tar sin sa[A]ber del[A7] tiempo...
Quiero r[F]espirar sin nunca [Fm]regresar ...
y quiero [C]vivir , quiero exi[Em]stir , sentir [A]el sil[A7]encio...
Ya no q[F]uiero hablar... Solo [Fm]quiero encontrar, un dia de p[C]az...
[C] [G] [F] [Fm]
Un día de p[C]az..[G]. [F][Fm]

yo solo kiero es[C]capar, Quiero escap[G]ar
Y nunca regre[F]sar, Y yo no quiero nunca [Fm]regresar...
Quiero escap[C]ar..., ya nos aleja Mas el[G] tiempo ...
Y no regre[F]sar, Solo quiero estar en [Fm]silencio...

{end_of_part}
