{title: El Rastro}
{artist: Marea}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, punk urbano, spanish pop, spanish punk}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 70411
# Empreinte source SHA256: aeb4d65b334c895a156b31f1cb0492878a9d34b82eda4e2a03ddff75f14a5f32
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

VOY A APREND[E]ERME EN LA SOLAPA [G]
UN CAER QUE HUELE A FL[D]ORES
UN PLANTEL CON DESAM[E]ORES

[E]Y HACERME UN VERSO QUE T C[G]AGAS
PARA VER SI ALGUIEN LO [D]TRAGA
Y ENGALAN MIS BALCO[E]NES

[C]NO ME  HAGA[D]S NI PUTO C[E]ASO SI PASO A TU VERA
[C]VENDIENDO FRACA[D]SOS COMO SI FUE[E]RA HIERBA BUENA
[C]AUNQUE LAS GITANAS GUAP[D]AS, NO LO VE[E]NDAN MAS BARATO
[C]EN EL RASTRO DONDE GU[D]LAN LA TRISTE[E]ZA

[E]HOY TRAIGO UN TRINO QUE DA C[G]ALMA
QUE ESTA RONCO DE AGUARDIE[D]NTE
QUE ESTA ARTO DE L[E]A GENTE

[E]Y TRAIGO EL PEINE DE MI[G] ALMA
QUE YA ESTA HASTA LOS C[D]OJONES
DE PEINAR TIRABUZO[E]NES

[C]NO ME  HAGA[D]S NI PUTO C[E]ASO SI PASO A TU VERA
[C]VENDIENDO FRACA[D]SOS COMO SI FUE[E]RA HIREBA BUENA
[C]AUNQUE LAS GITANAS GUAP[D]AS, NO LO VE[E]NDAN MAS BARATO
[C]EN EL RASTRO DONDE GU[D]LAN LA TRISTE[E]ZA

{comment: À vérifier : ACOMPAÑAMIENTO: Bb C# D# A}
# SOURCE A VERIFIER: ACOMPAÑAMIENTO: Bb C# D# A 
UN TOQUE EN CADA[Bb] NO[C#]TA.[D#]

[C]TE REGALO MI[D] FOGATA A FUEG[E]O LENTO
PA TUS[G] OJOS DE SARM[C]IENTO
Y QUE NO[D] AMANEZCA[E] HOOOOOY
[C]POR UN BESO,[D] YO ME ARRASTRO COMO U[E]N SAPO
COMO UN [G]PRINCIPE  EN ARAPOS [C]
EN FIN[D] COMO LO QUE[E] SOOOY

SOLO DE GUITARRA

[E]Y PA QUE NO ME HECHES E[G]N FALTA
LLORANDO COMO UN CHIKI[D]LLO
AL VER MARCHAR MI MERCADI[E]LLO

[E]TE DEJO EL SUEÑO QUE MAS Q[G]UIERO
PARA ANCLARLO EN TU SOMB[D]RERO
PARA HACERTE UN OFERC[E]ILLO

[C]NO ME  HAGA[D]S NI PUTO C[E]ASO SI PASO A TU VERA
[C]VENDIENDO FRACA[D]SOS COMO SI FUE[E]RA HIRBA BUENA
[C]AUNQUE LAS GITANAS GUAP[D]AS, NO LO VE[E]NDAN MAS BARATO
[C]EN EL RASTRO DONDE GU[D]LAN LA TRISTE[E]ZA

{comment: À vérifier : ACOMPAÑAMIENTO: Bb C# D# A}
# SOURCE A VERIFIER: ACOMPAÑAMIENTO: Bb C# D# A 
UN TOKE EN CADA [Bb]NOT[C#]A. [D#]

[C]TE REGALO MI[D] FOGATA A FUEG[E]O LENTO
PA TUS[G] OJOS DE SARM[C]IENTO
Y QUE NO[D] AMANEZCA[E] HOOOOOY
[C]POR UN BESO,[D] YO ME ARRASTRO COMO U[E]N SAPO
COMO UN [G]PRINCIPE  EN ARAPOS [C]
EN FIN[D] COMO LO QUE[E] SOOOY

[C]TE REGALO MI[D] FOGATA A FUEG[E]O LENTO
PA TUS[G] OJOS DE SARM[C]IENTO
Y QUE NO[D] AMANEZCA[E] HOOOOOY
[C]POR UN BESO,[D] YO ME ARRASTRO COMO U[E]N SAPO
COMO UN [G]PRINCIPE  EN ARAPOS [C]
EN FIN[D] COMO LO QUE[E] SOOOY

[C]TE REGALO MI[D] FOGATA A FUEG[E]O LENTO
PA TUS[G] OJOS DE SARM[C]IENTO
Y QUE NO[D] AMANEZCA[E] HOOOOOY
[C]POR UN BESO,[D] YO ME ARRASTRO COMO U[E]N SAPO
COMO UN [G]PRINCIPE  EN ARAPOS [C]
EN FIN[D] COMO LO QUE[E] SOOOY

venga gente os dejo aqui esta padazo de cancion!!
