{title: People Loving People}
{artist: Garth Brooks}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, country, oklahoma country}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 107720
# Empreinte source SHA256: d2910f50c0e6d7e4f76952cf137c0a23accfc34ece2b41eca05589796aa2a4e2
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

            PEOPLE LOVING PEOPLE - GARTH BROOKS
Tabbed by Kyle K

[A5] [Db] [A5] [Db] [A5] [Db] [A5] [Db]

[A5]DOCTOR YOU AIN?T GOT A [Db]PILL
[A5]FOR WHATEVER?S MAKIN? THIS WORLD [Db]ILL
[A5]YOU CAN?T GET FORGIVENESS AT THE [Db]STORE
AND [A5]PEACE IT?S A POLITICIANS [Db]WAR

[A5]NO YOU WON?T FIND NO RESOLUTION
IN THE [Db]BOTTOM OF A BOTTLE
[A5]IN THE STARS OF ARISTOTLE
[Db]THE ONLY ANSWER TO THE PROBLEM IS

[A5]PEOPLE LOVING [Db]PEOPLE
[A5]THAT?S THE ENEMY OF EVERYTHING THAT?S [E5]EVIL
[A5]AIN?T NO QUICK FIX AT THE END OF A [Db]NEEDLE
IT?S JUST [A5]PEOPLE LOVING [E5]PEOPLE

[A5]WHO-O-OA  [C#m]WHO-O-OA  [A5]WHO-O-OA [E5]WHO-O-O-OH

[A5]WORDS AREN?T WHAT THEY SEEM TO [Db]BE
[A5]AND TALK IS CHEAP, BUT LIES ARE [Db]FREE
[A5]WE FEAR WHAT WE DON?T UNDERSTA[Db]ND
[A5]AND WE?VE BEEN SCARED SINCE [E5]TIME BEGAN

[A5]ALL THE COLORS AND THE CULTURES
[Db]CIRCLE ROUND US ON THE SPINDLE
[A5]IT?S A COMPLICATED RHYTHM
[Db]THE SOLUTION IS SO SIMPLE

IT?S JUST [A5]PEOPLE LOVING [Db]PEOPLE
[A5]THAT?S THE ENEMY OF EVERYTHING THAT?S [E5]EVIL
[A5]AIN?T NO QUICK FIX AT THE END OF THE [Db]NEEDLE
IT?S JUST [A5]PEOPLE LOVING [E5]PEOPLE

[A5]WHO-O-OA  [C#m]WHO-O-OA  [A5]WHO-O-OA    [E5]WHO-O-O-OH
[A5]WHO-O-OA  [C#m]WHO-O-OA  [A5]WHO-O-OA    [E5]WHO-O-O-OH

[A5]YOU CAN PAWN IT OFF ON KINGS AND QUEENS
AND [E5]THOSE BEHIND THE CURTAIN
SAY [Db]ONE CAN?T MAKE A DIFFERENCE
IN A [A5]WORLD SO FULL OF HURTIN?

BUT I BELIEVE THE REMEDY
STARTS RIGHT [E5]HERE WITH YOU AND ME

[A5]PEOPLE LOVING [Db]PEOPLE
[A5]THAT?S THE ENEMY OF EVERYTHING THAT?S [E5]EVIL
[A5]AIN?T NO QUICK FIX AT THE END OF THE [Db]NEEDLE

IT?S JUST [A5]PEOPLE LOVING [E5]PEOPLE
IT?S JUST [A5]PEOPLE LOVING [E5]PEOPLE
IT?S JUST [A5]PEOPLE LOVING [E5]PEOPLE

[A5]WHO-O-OA  [C#m]WHO-O-OA  [A5]WHO-O-OA    [E5]WHO-O-O-OH
[A5]WHO-O-OA  [C#m]WHO-O-OA  [A5]WHO-O-OA    [E5]WHO-O-O-OH
[A5]WHO-O-OA  [C#m]WHO-O-OA

IT?S JUST [A5]PEOPLE LOVING [E5]PEOPLE
