{title: Navigator}
{artist: The Pogues}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, celtic, celtic punk, celtic rock, folk punk, irish folk, punk}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 77955
# Empreinte source SHA256: ed957ae5126dfc86520cf119a5f2ea7435d9c56b995185566adcbdb8d030fdb8
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

THE CANALS, [G]THE BRIDGES, THE EMBANKMENTS AND CUTS, [C]
THEY BL[G]ASTED AND DUG WITH THERE SWE[C]AT AND THERE G[D]UTS,
THEY [G]NEVER DRANK WATER BUT WHISKY BY PI[C]NTS,
AND THE [G]SHANTY TOWNS RANG WITH THERE S[C]ONGS A[D]ND THERE [G]FIGHTS.
[G]NAVIGATOR, NAVIGATOR, RISE U[C]P AND BE ST[G]RONG,
[G]THE MORNING IS HERE AND THERE'S [C]WORK TO BE D[D]ONE,
TAKE a [G]PICK AND YOUR SHOVEL AND SOME [C]OLE' DYNAM[G]ITE,
[G]JUST TO SHIFT A FEW [C]TONS OF THIS EAR[D]THLY DELIGH[G]T,
[G]YES, TO SHIFT A FEW [C]TONS OF THIS EAR[D]THLY DELIGH[G]T.
[G]THEY DIED IN THERE THOUSANDS, WITH NO S[C]IGN TO MARK WH[G]ERE,
[G]SAVE THE BRASS IN THE POCKET OF THE EN[C]TREPRENEUR[D],
BY L[G]ANDSLIDE AND ROCK BLAST THEY ARE BU[C]RIED SO D[G]EEP,
[G]THAT IN DEATH IF NOT [C]LIFE THEY'LL HAVE PEA[D]CE WHILE THE[G]Y SLEEP.
[G]NAVIGATOR, NAVIGATOR, RISE U[C]P AND BE ST[G]RONG,
[G]THE MORNING IS HERE AND THERE'S [C]WORK TO BE D[D]ONE,
TAKE a [G]PICK AND YOUR SHOVEL AND SOME [C]OLE' DYNAM[G]ITE,
[G]JUST TO SHIFT A FEW [C]TONS OF THIS EAR[D]THLY DELIGH[G]T,
[G]YES, TO SHIFT A FEW [C]TONS OF THIS EAR[D]THLY DELIGH[G]T.
[G]THERE MARK ON THIS LAND IS STILL SE[C]EN AND STILL L[G]AID,
[G]A WAY FOR THE COMMERCE WHERE VAST FORT[C]UNES WERE MA[D]DE,
[G]THE SUPPLY OF AN EMPIRE WHERE THE S[C]UN NEVER S[G]ETS,
[G]WHICH IS NOW DEEP IN DA[C]RKNESS BUT THE RA[D]ILWAYS THERE YE[G]T.
[G]NAVIGATOR, NAVIGATOR, RISE U[C]P AND BE ST[G]RONG,
[G]THE MORNING IS HERE AND THERE'S [C]WORK TO BE D[D]ONE,
TAKE a [G]PICK AND YOUR SHOVEL AND SOME [C]OLE' DYNAM[G]ITE,
[G]JUST TO SHIFT A FEW [C]TONS OF THIS EAR[D]THLY DELIGH[G]T,
[G]YES, TO SHIFT A FEW [C]TONS OF THIS EAR[D]THLY DELIGH[G]T.
