{title: If That Ain't Country}
{artist: David Allan Coe}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, country, country rock, outlaw country}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 93396
# Empreinte source SHA256: 25f2a0677773c4838fb5c5ff162119765e74528b758c16d7ea8885ffa174f8c8
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

THE OLD MAN WAS [D]COVERED WITH TATOOS AND SCARS, HE GOT SOME IN [G]PRISON AND SOME IN THE BARS.
THE [A]REST HE GOT WORKIN' ON OLD JUNK CARS IN THE [D]DAY TIME.
THEY [D]LOOKED LIKE TOMBSTONES IN OUR YARD
AND I [G]NEVER SEEN HIM WHEN HE [A]WASN'T TIRED AND [D]MEAN.

HE [D]SOLD USED PARTS TO MAKE ENDS MEET, [G]COVERED WITH GREASE FROM HIS HEAD TO HIS FEET,
[A]CUSSIN' THE SUN AND THE TEXAS HEAT, AND THE [D]SKEETERS.
AND THE [D]NEIGHBORS SAY WE LIVE LIKE HICKS,
BUT THEY [G]BRING THEIR CARS FOR [A]PA TO FIX [D]ANYHOW.

HE WAS [D]VET'RIN PROUD, TRIED AND TRUE, HE'D [G]FIGHT TILL HIS HEART WAS BLACK AND BLUE,
[A]DIDN'T KNOW HOW HE'D MAKE IT THROUGH, THE [D]HARD TIMES.
[D]BOUGHT OUR HOUSE ON THE G.I. BILL,
BUT IT [G]WASN'T WORTH ALL HE [A]HAD TO KILL TO [D]GET IT.

HE DRANK [D]PEARL IN A CAN AND JACK DANIELS BLACK, [G]CHEWED TOBACCO FROM A MAIL-POUCH SACK,
[A]HAD AN OLD DOG THAT WAS TRAINED TO ATTACK, [D]SOMETIMES.
[D]HE'D GET DRUNK AND MEAN AS A RATTLESNAKE,
AND THERE [G]WASN'T TOO MUCH THAT [A]HE WOULD TAKE, FROM A [D]STRANGER.

THERE WAS [G]13 KIDS AND A [A]BUNCH OF DOGS, [D]HOUSE FULL OF CHICKENS AND A [G]YARD FULL OF HOGS,
[A]SPENT THE SUMMERTIME [G]CUTTIN' UP LOGS FOR THE [D]WINTER.
[G]TRYIN' LIKE THE DEVIL TO [A]FIND THE LORD, AND [D]WORKIN' LIKE A NIGGER FOR MY [G]ROOM AND BOARD,
[A]COAL BURNIN' STOVE, NO NATURAL GAS, AND IF THAT AIN'T COUNTRY, I'LL KISS YOUR [D]ASS.

[D]IF THAT AIN'T [G]COUNTRY, IT'LL HAIRLIP THE [D]POPE,
IF THAT AIN'T [G]COUNT[A]RY, IT'S A DAMN GOOD [D]JOKE.
I'VE SEEN THE [G]GRAND 'OLE [A]OPRY AND [D]I MET JOHNNY [G]CASH,
AND IF THAT AIN'T [A]COUNTRY, I'LL KISS YOUR [D]ASS.

WELL, [D]MOMMA SOLD EGGS AT THE GROCERY STORE, MY [G]OLDEST SISTER WAS A FIRST-RATE WHORE,
[A]DAD SAYS SHE CAN'T COME HOME ANY MORE, AND HE [D]MEANS IT.
[D]MA JUST SITS AND KEEPS HER SILENCE
[G]SISTER SHE LEFT 'CAUSE [A]DAD GOT VIOLENT, AND SHE [D]KNOWS IT.

[D]MOMMA SHE'S OLD, FAR BEYOND HER TIME, FROM [G]CHOPPIN' TOBACCO
AND I SEEN HER CRYIN WHEN [A]BLOOD STARTED FLOWIN' FROM HER CALLOUSED HANDS, AND IT [D]HURT ME.
[D]BUT SHE'D JUST KEEP WORKIN' TRYIN' TO HELP THE OLD MAN,
FROM THE [G]END OF ONE ROW AND [A]BACK AGAIN,LIKE [D]ALWAYS.

SHE'D [D]BEEN THROUGH HELL SINCE JUNIOR WENT TO JAIL, AND WHEN THE [G]LIGHTS GO OUT SHE AIN'T NEVER FAILED,
TO [A]GET DOWN ON HER KNEES AND PRAY, 'CAUSE SHE [D]LOVES HIM.
[D]SHE TOLD ALL THE NEIGHBORS HE WAS OFF IN THE WAR,
[G]FIGHTIN' FOR FREEDOM, HE'S [A]GOOD TO THE CORE, AND SHE'S [D]PROUD.

[D]OUR PLACE WAS A GRAVEYARD FOR AUTOMOBILES, AT THE [G]END OF THE PORCH WERE 4 STACKS OF WHEELS,
AND [A]TIRES FOR SALE FOR A DOLLAR OR TWO, [D]CASH.

THERE WERE[G] 50 HOLES IN THAT [A]OLD TIN ROOF.
[D]ME AND MY FAMILY WAS [G]LIVIN' PROOF,
OF [A]PEOPLE WHO FORGOT ABOUT POOR WHITE TRASH
AND IF THAT AIN'T COUNTRY I'LL KISS YOUR [D]ASS.

[D]IF THAT AIN'T [G]COUNTRY, IT'LL HAIRLIP THE [D]POPE,
IF THAT AIN'T [G]COUNT[A]RY, IT'S A DAMN GOOD [D]JOKE.
I'VE SEEN THE [G]GRAND 'OLE [A]OPRY AND [D]I MET JOHNNY [G]CASH,
AND IF THAT AIN'T [A]COUNTRY, I'LL KISS YOUR [D]ASS.
