{title: Agua De La Miseria}
{artist: Luis Alberto Spinetta}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-es, argentine indie, argentine rock, latin alternative, latin rock, post-punk argentina, rock en espanol, rock nacional}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 72637
# Empreinte source SHA256: 1e0f1158067e6dc160949e1be07c9f96bca70c266c95386a58668794f6a00364
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

Canta... [Amaj7]
[Fmaj7/5-]bajo la -  -  -  - l[Am7]luvia,
alguien... alguien sin nadie...
te oye...
llorar de noche,
cuando de tu alma sangras...
[Dm7/9]ya no me mires así[Bm7/9/11],
¿y para qué[Fmaj7/5-] vivir, [G6]
si ya no ti[Fmaj7/5-]enes fe... [G6] -  -  - [Fmaj7/5-]en tu hermano, [G6]
[Asus4]al que no amas ya?            Dm7/9   Bm7/9/11
! Ya no me digas que se siente !
si no se cam[Fmaj7/5-]bia hoy, [G6]
no se cambia más...
y tus hijos sabrán,                          y así sigue.
que vendíste tu amor...
que vendíste tu amor...

Juega,
juega que el tiempo huye...
y cambiame por una mosca...
vierte, vierte tu lágrima,
sobre la absurda suerte,
ya no me mires así,
si no se cambia hoy,
no se cambia más...
y tus hijos sabrán,
que vendíste tu amor...
que vendíste tu amor...
! Ya no me digas que se siente...
al atravesar,
la eternidad...
sin una gestión,
desde tu corazón... !
Tu sombra da,
contra el muro,
al que quiebras,
en múltiples ecos...
y acércate,
y ahuyentarás...
el desastre de mi alma,
que sueña...
Bebe,
bebe, desde el columpio...
el agua de la miseria...
y saca,
saca de los que sufren...
y quema la cruz,
tan ciego,
solo eres esclavo del poder...
¿y para qué vivir,
si ya no tienes fe,
en tu hermano,
al que no amas ya?
! Ya no me digas que se siente...
al atravesar,
la eternidad...
sin una gestión,
desde tu corazón... !
si no se cambia ya, tus hijos dirán...
que vendíste tu amor... !
Ya no me digas que se siente...
en la eternidad...
sin una gestión,
desde tu corazón... !
! Ya no me digas que se siente... !
si ya no tienes fe,
en tu hermano...
al que no amas ya...
¿pero qué es lo que te pasa, nene?
