{title: Soldado do Morro}
{artist: MV Bill}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, brazilian hip hop, funk ostentacao, rap nacional antigo}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 95894
# Empreinte source SHA256: 1e7c4fd78bf6cc4a0831e72e9ed7c00314901aa6fe4b0e4b6e00fd9b64a7075a
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: aucun_accord_converti, tabulations_interpretees_4_colonnes, tonalite_absente

            Soldado do Morro

MINHA CONDIÇÃO É SINISTRA NÃO POSSO DAR ROLÉ
NÃO POSSO FICAR DE BOBEIRA NA PISTA
NA VIDA QUE EU LEVO EU NÃO POSSO BRINCAR
EU CARREGO UMA NOVE E UMA HK
PRA MINHA SEGURANÇA E TRANQÜILIDADE DO MORRO
SE PA SE PAM EU SOU MAIS UM SOLDADO MORTO
VINTE E QUATRO HORAS DE TENÇÃO
LIGADO NA POLICIA BOLADO COM OS ALEMÃO
DISPOSIÇÃO CEM POR CENTO ATÉ O OSSO
TEM MAIS UM PENTE LOTADO NO MEU BOLSO
QUALQUER ROUPA AGORA EU POSSO COMPRAR
TEM UM MONTE DE CACHORRA QUERENDO ME DAR
DE OLHO GRANDE NO DINHEIRO ESQUECEM DO PERIGO
A MODA AQUI É SER MULHER DE BANDIDO
SEM SUCESSO MANTENDO O OLHO ABERTO
QUEBRARAM MAIS UM OTÁRIO QUERENDO SER ESPERTO
ESSA PORRA ME PERSEGUE ATÉ O FIM
NESSE MOMENTO MINHA COROA TA ORANDO POR MIM
É ASSIM DEMOROU JÁ É
ROUBARAM MINHA ALMA MAS NÃO LEVARAM MINHA FÉ
NÃO CONSIGO ME OLHAR NO ESPELHO
SOU COMBATENTE CORAÇÃO VERMELHO
MINHA MINA DE FÉ TA EM CASA COM O MEU MENOR
AGORA POSSO DAR DO BOM E MELHOR
VARIAS VEZES ME SENTI MENOS HOMEM
DESEMPREGADO MEU MOLEQUE COM FOME
É MUITO FÁCIL VIR AQUI ME CRITICAR
A SOCIEDADE ME CRIOU AGORA MANDA ME MATAR
ME CONDENAR E MORRER NA PRISÃO
VIRAR NOTICIA DE TELEVISÃO
SERIA DIFERENTE SE EU FOSSE MAURICINHO
CRIADO A SUSTAGEM E LEITE NINHO
COLÉGIO PARTICULAR DEPOIS FACULDADE
NÃO É ESSA MINHA REALIDADE
SOU CABOQUINHO COMUM COM SANGUE NO OLHO
COM ÓDIO NA VEIA SOLDADO DO MORRO
UM PELO PODER DOIS PELA GRANA
TEM MUITO CARA QUE ENTROU PELA FAMA
PLANTOU NA BOCA TENDO OUTRA OPÇÃO
NÃO DUROU QUASE NADA AMANHECEU NO VALÃO
PORQUE O PAPO NÃO FAZ CURVA AQUI O PAPO É RETO
OUVI ISSO DE UM BANDIDO MAIS VELHO
PLANTADO AQUI NÃO TENHO IRMÃO
SÓ O COSPE CHUMBO QUE TA NA MINHA MÃO
COMO PÁSSARO QUE DEFENDE SEU NINHO
ARREBENTO O PRIMEIRO QUE CRUZAR MEU CAMINHO
FORA DA LEI CHAMADO DE ELEMENTO
AGORA O CRIME QUE DA O MEU SUSTENTO
já PEDI ESMOLA já ME HUMILHEI
FUI PISOTEADO SÓ EU SEI QUE EU PASSEI
TO LIGADO NÃO VAI JUSTIFICAR
MEU TEMPO É PEQUENO NÃO SEI O QUANTO VAI DURAR
É PIOR DO QUE PEDIR FAVOR
ARRUMA UM EMPREGO TENHO UM FILHO PEQUENO SEU DOUTOR
FILA GRANDE EU E MAIS TREZENTOS
DEPOIS DE MUITO TEMPO SEM VAGA NO MOMENTO
A MESMA HISTÓRIA TODO DIA É FODA
ISSO QUE GEROU A MINHA REVOLVA
ME DEIXOU DESNORTEADO MAIS UM MALUCO ARAMADO
TO LIGADO BOLADO QUEM É O CULPADO?
QUE FABRICA A GUERRA E NUNCA MORRE POR ELA
DISTRIBUI A DROGA QUE DESTRÓI A FAVELA
FAZENDO DINHEIRO COM A NOSSA REALIDADE
ME DEIXARAM ENTRE O CRIME E A NECESSIDADE
FEIO E ESPERTO COM UMA CARA DE MAL
A SOCIEDADE ME CRIOU MAS UM MARGINAL
EU TENHO UMA NOVE E UMA HK
COM ÓDIO NA VEIA PRONTO PARA ATIRAR
VIOLÊNCIA DA FAVELA COMEÇOU A DESCER PRO ASFALTO
HOMICÍDIO SEQÜESTRO ASSALTO
QUEM DEVERIA DAR A PROTEÇÃO
INVADE A FAVELA DE FUZIL NA MÃO
EU SEI QUE O MUNDO QUE EU VIVO É ERRADO
MAS QUANDO EU PRECISEI NINGUÉM TAVA DO MEU LADO
ERRADO POR ERRADO QUEM NUNCA ERROU?
AQUELE QUE PEDE VOTO TAMBÉM já MATOU
ME COLOCOU NO LADO PODRE DA SOCIEDADE
COM MUITA DROGA MUITA ARMA MUITA MALDADE
VIDA DO CRIME É SUICÍDIO LENTO
NA CADEIA RANGU 1 2 3 MEUS AMIGOS TENHO LÁ DENTRO
EU TO LIGADO QUAL É SEI QUAL É O FINAL
UM SOLDADO NEGATIVO MENOS UM MARGINAL
PRA SOCIEDADE UMA BAIXA NA LISTA
E ENGORDAR UMA TRISTE ESTATÍSTICA
DE JOVENS COMO EU QUE DESCONHECEM O MEDO
SEDUZIDOS PELO CRIE DESDE MUITO CEDO
MESMO SABENDO QUE NÃO HÁ FUTURO
EU NÃO QUERIA TA NESSE BAGULHO
já TO NO PREJUÍZO UM TIRO NA BARRIGA
NA PRÓXIMA BATIDA QUEM SABE LEVAM MINHA VIDA
EU VOU DEIXAR MEU MOLEQUE SOZINHO
COM TENDÊNCIA A TRILHAR MEU CAMINHO
SE EU CAIR SÓ MINHA MÃE VAI CHORAR
NA FILA TEM UM MONTE QUERENDO ENTRAR NO MEU LUGAR
NÃO SEI SE É POR VIRAR BANDIDO
OU SE MATAR POR UM SALÁRIO MÍNIMO
EU NO CRIME IRONIA DO DESTINO
MINHA MÃE TA PREOCUPADO SEU FILHO TA PERDIDO
ENQUANTO NÃO CHEGAR A HORA DA PARTIDA
AGENTE SE CRUZA NAS FAVELAS DA VIDA
FEIO E ESPERTO COM UMA CARA DE MAL
A SOCIEDADE ME CRIOU MAS UM MARGINAL
EU TENHO UMA NOVE E UMA HK
COM ÓDIO NA VEIA PRONTO PARA ATIRAR
