{title: The Magnificent Seven}
{artist: The Clash}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, classic rock, permanent wave, punk, rock}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 26140
# Empreinte source SHA256: 1efc149a51456dfa8f351d149310764928a9095ee0ef800fa1124c13866a6ff2
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, ponctuation_chordpro_neutralisee, tabulations_interpretees_4_colonnes, tonalite_absente

THE MAGNIFIC[Am]ENT SEVEN [Dm7]
[Am]RlNG! RING! IT?S 7:00 AM
[Dm7]MOVE Y?SELF TO GO AGAIN
[Am]COLD WATER IN THE FACE
[Dm7]BRINGS YOU BACK TO THIS AWFUL PLACE
[Am]KNUCKLE MERCHANTS AND YOU BANKERS, TOO
[Dm7]MUST KEEP UP AN? LEARN THOSE RULES
[Am]WEATHER MAN AND THE CRAZY CHIEF
[Dm7]ONE SAYS SUN AND ONE SAYS SLEET
[Am]AM, THE FM, THE PM TOO
[Dm7]CHURNING OUT THAT BOOGALOO
[Am]GETS YOU UP AND GETS YOU OUT
[Dm7]BUT HOW LONG CAN YOU KEEP IT UP?
[Am]GIMME HONDA, GIMME SONY
[Dm7]SO CHEAP AND REAL PHONY
[Am]HONG KONG DOLLARS AND INDIAN CENTS
[Dm7]ENGLISH POUNDS AND ESKIMO PENCE
[Am]YOU LOT! WHAT?
[Dm7]DON?T STOP! GIVE IT ALL YOU GOT!
[Am]YOU LOT! WHAT?
[Dm7]DON'T STOP! YEAH!
WORKING FOR A RISE, BETTER MY STATION
TAKE MY BABY TO SOPHISTICATION
SHE'S SEEN THE ADS, SHE THINKS IT?S NICE
BETTER WORK HARD ? I SEEN THE PRICE
NEVER MIND THAT IT'S TIME FOR THE BUS
WE GOT TO WORK ? AN? YOU?RE ONE OF US
CLOCKS GO SLOW IN A PLACE OF WORK
MINUTES DRAG AND THE HOURS JERK
?WHEN CAN I TELL ?EM WOT I DO?
IN A SECOND, MAAAN...ORIGHT CHUCK!?
WAVE BUB-BUB-BUB-BYE TO THE BOSS
IT?S OUR PROFIT, IT'S HIS LOSS
BUT ANYWAY LUNCH BELLS RING
TAKE ONE HOUR AND DO YOUR THANNG!
CHEEESBOIGER!
WHAT DO WE HAVE FOR ENTERTAINMENT?
COPS KICKIN' GYPSIES ON THE PAVEMENT
NOW THE NEWS-SNAP TO ATTENTION!
THE LUNAR LANDING OF THE DENTIST CONVENTION
ITALIAN MOBSTER SHOOTS A LOBSTER
SEAFOOD RESTAURANT GETS OUT OF HAND
A CAR IN THE FRIDGE
OR A FRIDGE IN THE CAB?
LIKE COWBOYS DO IN TV LAND
YOU LOT! WHAT? DON'T STOP. HUH?
SO GET BACK TO WORK AN? SWEAT SOME MORE
THE SUN WILL SINK AN? WE?LL GET OUT THE DOOR
IT?S NO GOOD FOR MAN TO WORK IN CAGES
HITS THE TOWN, HE DRINKS HIS WAGES
YOU?RE FRETTIN?, YOU?RE SWEATIN?
BUT DID YOU NOTICE YOU AIN?T GETTIN'?
DON'T YOU EVER STOP LONG ENOUGH TO START?
TO TAKE YOUR CAR OUTTA THAT GEAR
DON'T YOU EVER STOP LONG ENOUGH TO START?
TO GET YOUR CAR OUTTA THAT GEAR
KARLO MARX AND FRIEDRICH ENGELS
CAME TO THE CHECKOUT AT THE 7-11
MARX WAS SKINT BUT HE HAD SENSE
ENGELS LENT HIM THE NECESSARY PENCE
WHAT HAVE WE GOT? YEH-O, MAGNIFICENCE!
LUTHER KING AND MAHATMA GANDHI
WENT TO THE PARK TO CHECK ON THE GAME
BUT THEY WAS MURDERED BY THE OTHER TEAM
WHO WENT ON TO WIN 5O-NIL
YOU CAN BE TRUE, YOU CAN BE FALSE
YOU BE GIVEN THE SAME REWARD
SOCRATES AND MILHOUS NIXON
BOTH WENT THE SAME WAY ? THROUGH THE KITCHEN
PLATO THE GREEK OR RIN TIN TIN
WHO'S MORE FAMOUS TO THE BILLION MILLIONS?
NEWS FLASH: VACUUM CLEANER SUCKS UP BUDGIE
OOOOHH...BUB-BYE
MAGNIFICENCE!!
FUCKING LONG, INNIT?

_______________________________________________________
# SOURCE A VERIFIER: Contribuição: rodrigo alan feltrin ferraz([email protected]) 
Contribuição: rodrigo alan feltrin ferraz(［email protected］)
