{title: The Race Is On}
{artist: George Jones}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, country, country rock, honky tonk}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 52363
# Empreinte source SHA256: 5031f25ca7dd2252ac01cbba736ecfac37e012f70ae9ede286b51b7ea2ed3edd
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

I FEEL TEARS[N.C.] WELLIN UP COLD AND DEEP INSIDE, LIKE MY HEARTS SPRUN[D]G A BIG BREAK [A]
AND A STAB OF LONELINESS SHARP AND PAINFUL, [E]THAT I MAY NEVER SHAKE
YOU MIGHT [A]SAY THAT I WAS TAKING IT HARD, OH, SHE [D]WROTE ME OFF WITH A [A]CALL
BUT DON?T YOU WAGGER THAT I?LL HIDE THE SORROW, [E]WHEN I MAY BREAK RIGHT DOWN AND [A]BAWL

[N.C.]WELL, THE RACE IS [A]ON AND HERE COMES PRIDE UP THE BACKSTRETCH, [D]HEARTACHES ARE GOING TO THE INS[A]IDE
MY TEARS ARE HOLDING BACK, THEY?RE TRYIN [E]NOT TO FALL
[A]MY HEARTS OUT OF THE RUNNING, TRUE LOVE?S [D]SCRATCHED FOR ANOTHERS [A]SAKE
THE RACE IS ON AND IT LOOKS LIKE HEARTACHES, AND THE [E]WINNER LOSES [A]ALL

ONE DAY I VENTURED IN LOVE, NEVER ONCE SUSPECTIN, WHAT THE FINAL RESULT WOULD BE
HOW I LIVED IN FEAR WAKING UP EACH MORNING, AND THINKING YOU WERE GONE FROM ME
THERE?S ACHE AND PAIN IN MY HEART, FOR TODAY WAS THE ONE THAT I HATED TO FACE
SOMEBODY NEW CAME UP TO WIN HER, I CAME OUT IN SECOND PLACE

[N.C.]NOW,  THE RACE IS [A]ON AND HERE COMES PRIDE UP THE BACKSTRETCH, [D]HEARTACHES ARE GOING TO THE INS[A]IDE
MY TEARS ARE HOLDING BACK, THEY?RE TRYIN [E]NOT TO FALL
[A]MY HEARTS OUT OF THE RUNNING, TRUE LOVE?S [D]SCRATCHED FOR ANOTHERS [A]SAKE
THE RACE IS ON AND IT LOOKS LIKE HEARTACHES, AND THE [E]WINNER LOSES [A]ALL
