{title: Pub With No Bear}
{artist: Slim Dusty}
{capo: 1}
{x_source_capo: 1}
{x_chord_convention: concert; formes source transposees du capo}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, australian country, australian rock, bush ballad, classic australian country}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 120922
# Empreinte source SHA256: 5057bae2e659f2d3c3398d4d4c8d89f430501895106429fc863bfb923f5b06f4
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: aucun_accord_converti, capo_source_interprete_formes, tonalite_absente

OH IT'S (C) LONESOME AWAY FROM YOUR (F) KINDRED AND ALL
BY THE (G7) CAMPFIRE AT NIGHT WHERE THE WILD DINGOES (C) CALL
BUT THERE'S NOTHING SO LONESOME, (F) MORBID OR DREER
THAN TO (G7) STAND IN THE BAR OF A PUB WITH NO (C) BEER

NOW THE (C) PUBLICAN'S ANXIOUS FOR THE (F) QUOTA TO COME
AND THERE'S A (G7) FAR AWAY LOOK ON THE FACE OF THE (C) BUM
THE MAID'S GONE ALL CRANKY AND THE (F) COOK'S ACTING QUEER
OH WHAT A (G7) TERRIBLE PLACE IS A PUB WITH NO (C) BEER

THEN THE (C) STOCKMAN RIDES UP WITH HIS (F) DRY DUSTY THROAT
HE (G7) BREASTS UP TO THE BAR, PULLS A WAD FROM HIS (C) COAT
BUT THE SMILE ON HIS FACE QUICKLY (F) TURNS TO A SNEER
AS THE (G7) BARMAN SAYS SADLY, "THE PUB'S GOT NO (C) BEER"

THEN THE (C) SWAGGIE COMES IN SMOTHERED IN (F) DUST AND FLIES
HE (G7) THROWS DOWN HIS ROLL RUBS THE SWEAT FROM HIS (C) EYES
BUT WHEN HE IS TOLD, HE SAYS (F) "WHAT'S THIS I HEAR?
I'VE (G7) TRUDGED FIFTY FLAMING MILES TO A PUB WITH NO (C) BEER"

NOW THERE?S A (C) DOG ON THE VERANDAH, FOR HIS (F) MASTER HE WAITS
BUT THE (G7) BOSS IS INSIDE DRINKING WINE WITH HIS (C) MATES
HE HURRIES FOR COVER AND HE (F) CRINGES IN FEAR
IT'S (G7) NO PLACE FOR A DOG 'ROUND A PUB WITH NO (C) BEER

AND OLD (C) BILLY THE BLACKSMITH, THE FIRST (F) TIME IN HIS LIFE
HAS (G7) GONE HOME COLD SOBER TO HIS DARLING (C) WIFE
HE WALKS IN THE KITCHEN, SHE SAYS (F) "YOU'RE EARLY MY DEAR"
BUT (G7) THEN HE BREAKS DOWN AND TELLS HER, "THE PUB'S GOT NO(C)  BEER"

SO IT'S (C) LONESOME AWAY FROM YOUR (F) KINDRED AND ALL
BY THE (G7) CAMPFIRE AT NIGHT WHERE THE WILD DINGOES (C) CALL
BUT THERE'S NOTHING SO LONESOME, (F) MORBID OR DREER
THAN TO (G7) STAND IN THE BAR OF A PUB WITH NO (C) BEER
