{title: Anclada En Mis Sueños}
{artist: Abel Pintos}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, argentine rock, argentine telepop, folklore argentino, pop argentino}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 34293
# Empreinte source SHA256: 00b0af42fe3af624325f8e0c3bf8608cdfd981baef9d8f169adfea49a98663f9
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

YO, QUE CAMI[Em]NO EL MUNDO CONOZ[D]CO EL DOLOR [Em]
[Em]DE TU FRIA A[D]USENCIA EN EL A[C]MANECER
[Am]SE ME SECA EL TIEMPO EN LA PIEL
[C]SI MIS LABIOS NO TE E[B7]VOCAN

LLEVO TU SOMBRA ALTIVA EN MI SOMBRA Y EL SOL
ALUMBRANDO EL GRITO DE MI CORAZON
QUE SE VUELVE ANSIOSO POR SER
LA COSTUMBRE DE TU BOCA

[C]CUANDO LA LUNA SE HAGA E[Am]CLIPSE EN TU MIRAR
Y MIS [D]VERSOS SEAN CANCIONES EN EL[G] ALMA
[Am]SERAS LA LUZ,[Em] LA REALIDAD
[C]Y LA RAZON DE MIS PA[B7]LABRAS

[Em]LLEVO TU NOMBRE ESCRITO EN MI[D] SANGRE
Y TU MI[C]RADA ANCLADA EN MIS S[G]UEÑOS
LA FUERZA [Am]DE UN HURACAN, Y EL D[Em]ESEO TOTAL
DE TE[C]NERTE, LATIENDO EN MI [B7]PECHO
(repite la secuencia de acordes)
QUIERO PERDERME EN UN ABRAZO PLENO
DEJAR MI PIEL MARCADA EN TUS MANOS
QUIERO QUE PUEDAS LLEVARME A ALGUN CIELO LEJANO
[C]Y ARRANCARME E[B7]L ALMA CON UN[Em] BESO

CUANDO LA LUNA SE HAGA ECLIPSE EN TU MIRAR
Y MIS VERSOS SEAN CANCIONES EN EL ALMA
SERAS LA LUZ, LA REALIDAD
Y LA RAZON DE MIS PALABRAS

LLEVO TU NOMBRE ESCRITO EN MI SANGRE
Y TU MIRADA ANCLADA EN MIS SUEÑOS
LA FUERZA DE UN HURACAN, Y EL DESEO TOTAL
DE TENERTE, LATIENDO EN MI PECHO
QUIERO PERDERME EN UN ABRAZO PLENO
DEJAR MI PIEL MARCADA EN TUS MANOS
QUIERO QUE PUEDAS LLEVARME A ALGUN CIELO LEJANO
Y ARRANCARME EL ALMA CON UN BESO
QUIERO PERDERME EN UN ABRAZO PLENO
DEJAR MI PIEL MARCADA EN TUS MANOS
QUIERO QUE PUEDAS LLEVARME A ALGUN CIELO LEJANO
Y ARRANCARME EL ALMA CON UN BESO
