{title: Em Glória e Poder}
{artist: Elaine Martins}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, brazilian gospel}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 119236
# Empreinte source SHA256: 14365854ed86776a054677fa595011c8f4c8199fa8fada7bddfc8ea19d42abc0
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tonalite_absente

GLÓRIA, GLÓRIA, GLÓRIA,          GLÓRIA, GLÓRI[C]A,[C4] GLÓRI[C]A, GLÓRIA, GLÓR[C4]IA [C][C]
EM GLÓRIA E PODER, EU SEI[C] QUE ELE VEM,    O MEU AMADO VEM BUSCAR-ME [F][Em][Dm][G]
E QUAL NOIVA AD[Dm]ORNADA E PRONTA ESTOU A ESPERAR [G][C]
O DIA EM QUE ELE VEM CAVALGAND[F]O SOBRE[Em] AS BRANCAS NUV[Dm]ENS [G]
ESCOLTADO POR[Dm] MILHARES DE ANJOS [G]
VEM O MEU AMOR VESTIDO CO[C]MO UM REI QUE NEM PRECISA CONQUISTAR [F][C]
SE ASSENTA COMO UM REI NO TRONO QUE NUNCA P[F]ERDEU [C]
É LÁ QUE EU VOU ESTAR A DESTRA DO GRAND[F]E VENCEDOR[G] [C][Em][F]
É LA QUE EU VOU REINAR L[Em]ADO A LADO [Dm]DO SENHOR [G][C]

NÃO VÃO ACREDITAR NO QUE EU VOU [C]DIZER       PORQUE NADA DO QUE O HOMEM DIG[F]A [Em][Dm][G]
SE ASSEMELHA COM A[Dm] NOVA VIDA QUE O MEU AMOR ME DEU[G] [C]
O DIA EM QUE ELE VEM CAVALGAND[F]O SOBRE[Em] AS BRANCAS NUV[Dm]ENS [G]
ESCOLTADO POR[Dm] MILHARES DE ANJOS [G]
VEM O MEU AMOR VESTIDO CO[C]MO UM REI QUE NEM PRECISA CONQUISTAR [F][C]
SE ASSENTA COMO UM REI NO TRONO QUE NUNCA P[F]ERDEU [C]
É LÁ QUE EU VOU ESTAR A DESTRA DO GRAND[F]E VENCEDOR[G] [C][Em][F]
É LA QUE EU VOU REINAR L[Em]ADO A LADO [Dm]DO SENHOR OR OR [G][C]

[F]NEM PRECISA CONQUISTAR [C]
SE ASSENTA COMO UM REI NO TRONO QUE NUNCA P[F]ERDEU [C]
É LÁ QUE EU VOU ESTAR A DESTRA DO GRAND[F]E VENCEDOR[G] [C][Em][F]
É LA QUE EU VOU REINAR L[Em]ADO A LADO [Dm]DO SENHOR       AO [G]LADO DO MEU SENHOR, [C][Dm][G][C]

AL[F]ELUI[C]A SE[F]NHOR[Em] PREP[Dm]ARA-T[G]E Ó ISRAEL PARA ENCONTRARES COM O SENHOR TEU DEUS

SENHOR TU ÉS SANTO E JUNTO COM O CORAL CELESTIAL

NÓS ENTOAREMOS QUE TU É SANTO, SANTO, SANTO PARA SEMPRE SANTO
[C]SANTO, SANTO, SANTO, SANTO, [F]TU ÉS SANTO [C][F][Em]
É LA QUE EU VOU REINAR LADO A LADO DO S[Dm]ENHOR [G][C]
AO LADO DO MEU SENHOR, AO LADO DO MEU [Dm]SENHO[Em]R [F][C]
