{title: O Show Tem Que Continuar (ver. 2)}
{artist: Grupo Revelação}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, pagode}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 133102
# Empreinte source SHA256: 14a023dde789cbe355092fb978ce579b0216fad5cd4e330a1a8ebc86c921f722
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : Introdução.: C}
# SOURCE A VERIFIER:             Introdução.: C 

[C7]  Lalaia lalaia lai[F]a
[Fm]Lalaia lalaia[C] laia
[C7]  Lalaia la[F7+]laia l[G7]aaaai[C]a
O teu cho[A7]ro já não to[Dm]ca..[G7]. Meu[C] bandolim...
[A7]Diz que minha voz su[Dm]foca.[G7].. Teu [Gm]violão...
Afr[C7]ouxaram-se as c[F7+]ordas... E a[Fm]ssim desaf[Em]ina.[A7]..
E pobre das [Dm]rimas... [G7]Da nossa [Gm]canção...
Se hoje [C7]somos folha [F7+]morta... M[Fm]etais em s[Em]urdina[A7]...
Fechada a cor[Dm]tina... [G7]Vazio o sa[C]lão...
***Se os d[A7]uetos não se enc[Dm]ontram [G7]mais... E os s[C]olos perderam a em[A7]oção...
Se ac[Dm]abou o g[G7]ás... [C]Para cantar o mais simples Ref[Am]rão...
Se agente [Bm7/5-]nota... [E7]Que uma só n[Am]ota... Já nos es[Dm]gota... [G7]O show perde [Gm]a razão..[C].
Nós iremos ac[F]har o tom[Fm]... Um acorde com um l[Em]indo som.[A7].. E fazer com que f[Dm]ique bom...
[G7]Outra vez.[Gm].. O nosso c[C7]antar...
E agente vai s[F]er feliz.[Fm].. Olha nós outra v[Em]ez no ar.[A7].. O show tem que [Dm]conti[G7]nuar[C]...

(Volta no ***)

[C7]Nós iremos até [F]Paris.[Fm].. Arrasar [Em]no Olímpia... [A7]O show tem que co[Dm]ntinu[G7]ar...[Gm] [C7]
Olha o povo pid[F]indo bis.[Fm].. O igressos v[Em]ão se esgotar[A7]... O show tem que c[Dm]onti[G7]nuar[Gm]... [C7]
[C7]Todo mundo que [F]hoje diz.[Fm].. Acabou vai s[Em]er admirar...[A7] Nosso amor vai cont[Dm]inua[G7]r...[Gm] [C]
Lalaia lalaia l[F]aia...
[Fm]Lalaia lalaia lai[Em]a...
[A7]Nosso amor vai c[Dm]onti[G7]nuar[Gm]... [C7]
Lalaia lalaia [F]laia...
[Fm]Lalaia lalaia [Em]laia...
[A7]Nosso amor vai c[Dm]onti[G7]nuar[C]...

Cifra adicionada por.:

AndrezinhoO Marques - Grupo Você Que Sabe - Curitiba - Paraná
