{title: Can't Break Me Down}
{artist: Billy Idol}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, album rock, classic rock, dance rock, hard rock, mellow gold, new romantic, new wave, new wave pop, rock, soft rock}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 30799
# Empreinte source SHA256: dc6d96b7657b26584d6fe6b2b9b50082d7eddd4742fc652327b1c2d43bfab055
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

            CAN?T BREAK ME DOWN - BILLY IDOL
Tabbed by Kyle K

[E5]WHO-O-O-OO-[Db]OA  WHO-O-O-OO-[Ab]OA  WHO-O-O-OO-OA  [E]WHO-O-O-OO-OA

[E5]THE DEVIL?S HOUSE IN THE SHAPE OF A CHAPEL
[Db]YOU HID THE KNIFE IN THE CORE OF A APPLE
[Ab]BURN ME, TRY TO HURT ME
TRY TO HIT ME WHEN MY [B5]BACK WAS TURNING

[E5]I SAW YOU WAIT WHEN THE SHADOWS WERE GROWING
[Db]YOU?RE TALKING STRAIGHT

BUT YOUR COLORS ARE SHOWING
[Ab]BURN ME, TRY TO HURT ME
TRY TO GET ME WHEN MY [B5]HEAD WAS TURNING

[A5]YOU WANT TO RAIN ON MY [E5]SURVIVAL STORY
[B5]YOU?RE CRAZY BABY CAUSE I?VE NEVER HAD A DOUBT
[A5]I?M SINGING SONGS ABOUT [E5]LOVE AND GLORY
[B5]OH OH OH

[A5]YOUR GUN WENT
[E5]BANG BANG BANG
YOU SHOT ME TO THE [B5]GROUND
BUT YOU [A5]CAN?T BREAK ME DOWN

[E5]BANG BANG BANG
YOU TRIED TO KNOCK ME [B5]OUT
NO, YOU [A5]CAN?T BREAK ME DOWN

[A5]IT?S JUST MY NATURAL [B5]REACTION
WHEN I HIT THE [A5]FLOOR
I?M THE ORIGINAL [B5]ASSASSIN
I COME UP FOR [E5]MORE

[E5]WHO-O-O-OO-[Db]OA  WHO-O-O-OO-[Ab]OA  WHO-O-O-OO-OA  [E]WHO-O-O-OO-OA

[E5]YOU PUT ME UP SO YOU CAN WATCH ME CRUMBLE
[Db]I ALWAYS KNEW YOU WERE SOME KINDA TROUBLE
[Ab]LURKING, YOU CAN?T HURT ME
CAUSE I SEE JUST HOW YOUR [B5]EVIL?S WORKING

[E5]A SILVER TONGUE WITH THE BEST OF INTENTIONS
[Db]BUT YOU?RE A CHILD WITH THE CRUELEST INVENTIONS
[Ab]BURNING, YOU?RE JUST HURTIN?
I KNOW SOMEWHERE DEEP IN[B5] HELL YOU?RE WORKING

[A5]YOU WANT TO RAIN ON MY [E5]SURVIVAL STORY
[B5]YOU?RE CRAZY BABY CAUSE I?VE NEVER HAD A DOUBT
[A5]I?M SINGING SONGS ABOUT [E5]LOVE AND GLORY
[B5]OH OH OH

[A5]YOUR GUN WENT
[E5]BANG BANG BANG
YOU SHOT ME TO THE [B5]GROUND
BUT YOU [A5]CAN?T BREAK ME DOWN

[E5]BANG BANG BANG
YOU TRIED TO KNOCK ME [B5]OUT
NO, YOU [A5]CAN?T BREAK ME DOWN

[A5]IT?S JUST MY NATURAL [B5]REACTION
WHEN I HIT THE [A5]FLOOR
I?M THE ORIGINAL [B5]ASSASSIN
I COME UP FOR [E5]MORE

[E5]YOU DON?T KNOW WHAT YOU STARTED
[Db]YOU HIT BUT MISSED THE TARGET

[Ab]YOU DON?T KNOW WHAT YOU STARTED

YOU HIT BUT MISSED THE TARGET

[E5]YOU DON?T KNOW WHAT YOU STARTED
[Db]YOU HIT BUT MISSED THE TARGET

[Ab]YOU DON?T KNOW WHAT YOU STARTED

YOU HIT BUT MISSED THE TARGET

[E5]BANG BANG BANG
YOU SHOT ME TO THE [B5]GROUND
BUT YOU [A5]CAN?T BREAK ME DOWN

[E5]BANG BANG BANG
YOU TRIED TO KNOCK ME [B5]OUT
NO, YOU [A5]CAN?T BREAK ME DOWN

[A5]IT?S JUST MY NATURAL [B5]REACTION
WHEN I HIT THE [A5]FLOOR
I?M THE ORIGINAL [B5]ASSASSIN
I COME UP FOR [E5]MORE
