{title: El Nano O El Cabo}
{artist: Alta Consigna}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, corrido, corridos tumbados, nuevo regional mexicano, regional mexican, sierreno}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 71901
# Empreinte source SHA256: 83908a543823cff1c27203cb64fb93968a6a8d8423df2de6a5d38fd22938938d
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

ME DICEN EL [A]NANO O EL CABO QUE ANDO LIMPIANDO LA PLA[F#m]ZA OBREGON
POR LA ALEM[D]AN ME LA LLEVO RONDANDO ME GUSTAN LAS ARMAS DE ORO ADIAMAN[E]TADO
PERO UN CALIBRE 5[A]0 SE RIFA DE  DI[F#m]ARIO DEJANDO LA SANGRE EN EL PISO CONTRA[D]RIOS
LUIS MI COMPA Y CONMIGO SIEMPRE AL RE[E]SPALDO

S[A]ON LAS TIERRAS SINALOENSES DONDE YO ME CR[F#m]IE
CUIDANDO LA PLAZA CUIDANDO EL CART[D]EL PASEANDO EN VILLA JUAREZ DONDE ME INICI[E]E
[F#m]UN EJERCITO A MI MANDO ME RESPALDA EL [E]EME
[F#m]Y LE PESE A QUIEN LE P[D]ESE YO SOY SINAL[E]OENSE
SIEMPRE [A]ANDO EN LA PELEA TUMBANDO TRAID[F#m]ORES
DEFIENDO PLAZA DE GOBIERNO Y SOP[D]LONES FIELES PISTOLEROS LOS PROTEGEN D[E]IARIO
S[F#m]OY UN GALLO FINO Y DE SON[E]ORA ESTOY A CARGO
[D]UNA ORDEN BASTA PARA TROZAR LOS CONTR[E]ARIOS

NO L[A]E GUSTAN LAS INJUSTICIAS TAMPOCO TRAIC[F#m]IONEN A MI COMPA VICTOR
A EL NI LO T[D]OQUEN PORQUE SI LO HACEN MEJOR QUE SE P[E]ELEN
EST[A]AMOS MUY BIEN AJUAREADOS TAMBIEN EQUIP[F#m]ADOS
CON ARMAS POTENTES PARA LOS CONT[D]RARIOS
Y LA SANTA MUERTE SIEMPRE ME PROTEGE DONDE QUIERA QUE[E] ANDO

UN CIGARRITO V[A]ERDE ES QUE A MI ME REL[F#m]AJA
WHISKY DEL 18 INICIA LA PARR[D]ANDA SI BRINCA LA LIEBRE YO JALO LA [E]BANDA
[F#m]Y NO ME RINDE LA NOCHE [D]VAN SONAR CINCUENTO[E]NES
ME LA PASO EN BACOB[A]AMPO SIEMPRE CON MI G[F#m]ENTE
DIA EN EL QUE SIEMPRE ESTAMOS AL PEN[D]DIENTE
DE BADIRAGUATO VIENE MIS RA[E]ICES
[F#m]YO SOY DE LA SIERRA Y ESO TENGANLO PRES[E]ENTE
Y[D] A LOS CONTRAS SIEMPRE LOS ATORO YO DE FR[E]ENTE.
