{title: Vale Vergara}
{artist: Molotov}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, latin alternative, latin hip hop, latin rock, mexican hip hop, mexican rock, rock en espanol}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 41298
# Empreinte source SHA256: e0b88827758b1b68944b68ecf99dfedd2234a164cff6e2270bc5fdffbbbc41bf
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : ....Am G}
# SOURCE A VERIFIER:             ....Am                  G 
ESTO ES UN SON DEDICADO
A[G7] LOS QUE LE GUSTA EL REGE!!!! QUE ME DISCULPEEE[F]EN

[Am]AMI ME GUSTA LA PASION DEL FUTBOL
[G]POR QUE SE JUEGA CON EL CORAZÓN
[G7]COMPARTIRLO CON NUESTRA AFIC[F]IÓN

LA TIERRA REDONDA POR QUE ES UN BALON
A GALILEO NADIEN LE CREIA
POR QUE DE FUTBOL NO LO CONOCIA
COMO EL GENIO LEONARDO DA VINCI
CUENTA MAS NUESTRO PENTAPICHICHI.

ESTE DEPORTE TAMBIEN ES CARRERA
Y AL QUE NOS PONGAN LE DAREMOS GUERRA
POR QUE DE FÚTBOL SOMOS UNA ESCUELA
POR ESO VERGARA SIEMPRE NOS LA PELA!!!

CORO x 2
AMI ME VALE VERGARA EL GUADALAJARA
VALE VERGARA ESTOY HECHO EN C.U.

ESTADIO DE FÚTBOL TE VALE UN MILLÓN
EQUIPO EN PRIMERA SEGUNDA OPINIÓN
VER A TU EQUIPO SER EL BICAMPEON
NO TIENE PRECIO DE NOMINACION
DESDE LA REBEL A LA HC-9 LA DIRECTIVA Y LA QUE VENDE CHEVE.
Y SI PERDEMOS TAMBIEN SI NOS LLUEVE,
VAMOS AL ESTADIO QUE PUMAS LA MUEVE
ENSEÑAR A JUGAR A LOS SIMIOS
EN LA CANCHA SOMO UNO MISMO
NO SOMOS 11 SOMOS UN CHINGO
QUE NO PASAR ANTI-DOPING EN DOMINGO.

CORO x 3
AMI ME VALE VERGARA EL GUADALAJARA
VALE VERGARA ESTOY HECHO EN C.U.

NO NOS PODRÁN DETENER EN LA CANCHA
SI LES GANAMOS LES DAMOS REVANCHA
Y AUNQUE PERDIÉRAMOS SE NOS RESPETA
POR QUE SUDAMOS NUESTRA CAMISETA

SER EL DUEÑO DEL BALÓN
COMPRAR AL EQUIPO CON MAS TRADICIÓN
USTED NO MANDA EN NUESTRO CORAZÓN
NO MEZCLE EL NEGOCIÓ CON NUESTRA PASIÓN

CORO x 3
AMI ME VALE VERGARA EL GUADALAJARA
VALE VERGARA ESTOY HECHO EN C.U.

EL EQUIPO NO TIENE LA CULPA
TAMPOCO SU GENTE TAN SOLO QUE EEEEEEES
SU PRESIDENTEEEEE.

CORO x 3
AMI ME VALE VERGARA EL GUADALAJARA
VALE VERGARA ESTOY HECHO EN C.U.
