{title: Get a life}
{artist: Soul II Soul}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, british soul, funk, hip house, post-disco, quiet storm, urban contemporary}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 106112
# Empreinte source SHA256: 1127679bfc23841e39925f53fe1bffe3395e12a3cb90e64ca05009ec9457261f
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

THIS THING CALLED LIFE [Am][Dm][Am][G]
KNOW WHAT'S THE MEANING OF THE LINE
TELL ME
WELL IT'S LIKE DREAMING OF YOUR GOALS , AMBITIONS FEELING FREE
ACHIEVE WHAT
WHAT'S IN YOUR MINDS EYE
THIS IS WHAT YOU SHOULD GAIN

SATISFACTION BECOMES A SHINNNING EXAMPLE
A TEST OF A SAMPLE OF A NEW RACE
THAT HAS AMPLE SUPPLY OF POSITIVITY
YOU MEAN FLOW
WELL LIKE ELECTRICITY
SO
YOU SEE A CLEAR WAY WITH NO AMBIGUITY
DON'T YOU KNOW
[Am]WHA[Dm]TS [Am]THE[G] M[F]EA[Am]NING
WHATS THE MEANING OF LIFE
WHATS THE MEANING
WHATS THE MEANING OF LIFE

ELEVATE YOUR MIND
FREE YOUR SOUL
WELL COME ON COME ON
FEEL THE FEELING LET YOUR BODY TAKE CONTROL
WELL DON'T BE [Am]AFR[Dm]AID[Am] TO[G] EXPERIMENT YOU KNOW UMM
GO AHEAD YOU KNOW AND IMPLEMENT YOUR IDEAS
YOUR NOTIONS PUT THEM IN MOTION
LIKE THE WORDS THE FUNKI DREDS HAVE SPOKEN TO YOU
SO LISTEN UP LOUD AND CLEAR
THIS IS A WORD YOU MUST BE AWARE OF

WHAT YA GONNA DO PUT IT IN YOUR LIFE TOOL
AND THATS THE MEANING OF LIFE
[Am]WHA[Dm]TS [Am]THE[G] M[F]EA[Am]NING
WHATS THE MEANING OF LIFE
WHATS THE MEANING
WHATS THE MEANING OF LIFE
WHATS THE MEANING
WHATS THE MEANING OF LIFE
WHATS THE MEANING
WHATS THE MEANING OF LIFE

AND IT GOES ON

ELEVATE YOUR MIND
FREE YOUR SOUL
WELL COME ON COME ON
FEEL THE FEELING LET YOUR BODY TAKE CONTROL

SO THERE IT IS WORK IT OUT FOR YOURSELF
YEAH , BE SELECTIVE BE OJECTIVE
BE AN ASSET TO THE COLLECTIVE
AS YOU KNOW YOU HAVE TO GET A LIFE

WHATS THE MEANING
WHATS THE MEANING OF LIFE
WHATS THE MEANING
WHATS THE MEANING OF LIFE
WHATS THE MEANING
WHATS THE MEANING OF LIFE
WHATS THE MEANING
WHATS THE MEANING OF LIFE
ELEVATE YOUR MIND
FREE YOUR SOUL
WELL COME ON COME ON
FEEL THE FEELING LET YOUR BODY TAKE CONTROL
AH YEAH

«BACK

ww w e - chords . co m
