{title: Dead On Time}
{artist: Slim Dusty}
{key: F#}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, australian country, australian rock, bush ballad, classic australian country}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 120911
# Empreinte source SHA256: 11ad6d0b977c09e125c64153d59c9986a4f8a2e275d57ae86cc9638b859c6d33
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_source_a_confirmer

            DEAD ON TIME.
HE[F#]?D DONE THIS RUN FOR A LONG TIME NOW

AND HE DON?T KNOW WHY AND HE DON?T KNOW HOW
BUT HE?D NEVER BEEN LATE SO THEY CALLED HIM DEAD ON TIME. [C#7]

HE PAINTED THE NAME ON THE BONNET IN BLACK

AND THE STATION KIDS ON THE MAILMAN?S TRACK
WOULD ALL LOOK OUT FOR THE DUST OF DEAD ON TIME. [F#]
WOULD ALL LOO[C#7]K OUT FOR THE DUST OF DEAD ON TIME. [B][F#]

I GOTTA BE BACK FOR THE KIDS BIRTHDAY

HE MAILMAN SAID AS HE WAVED HOORAY
AND WHELED HIS TRUCK ON THE LONG HAUL HOMEWARD BOUND. [C#7]

THE  WIFE?S GONNA MAKE HIM A CHOCOLATE CAKE

THEY MADE ME PROMICE THAT I WON?T BE LATE
I?LL SEE YOU AGAIN WHEN I COME NEXT TIME AROUND. [F#]
I?LL S[C#7]EE YOU AGAIN WHEN I COME NEXT TIME AROUND. [B][F#]

BUT DEAD ON TIME RAN OUTTA LUCK

AND HE COULD?T BELIEVE WHEN HIS GOOD OLD TRUCK
GROUND TO A HAULT WITH A BURNT OUT BEARINGS WHINE [C#7]

NOT A TREE IN SIGHT AND THE WATER BAG LOW

NOT A HOPE IN HELL OF GETTING HER TO GO
DIDN?T LOOK TO GOOD AT ALL FOR DEAD ON TIME. [A]
DIDN?T LOOK TO[C#7] GOOD AT ALL FOR DEAD ON TIME. [B][F#]

A BIRTHDAY PARTY AND A CHOCOLATE CAKE

WENT DANCIN ACROSS THE DRY SALT LAKE
WHERE THE MIRAGE MET WITH THE DISTANT TIMBER LINE. [C#7]

AND THE SILENT TRUCK THREW A MEAGRE SHADE

OVER THE PLEA FOR HELP THAT HE MADE
SCRATCHED IN THE DIRT ON THE ROAD BY DEAD ON TIME. [B][F#]

HE?D DONE THIS RUN FOR A LONG TIME NOW

AND HE DON?T KNOW WHY AND HE DON?T KNOW HOW
BUT HE?D NEVER BEEN LATE SO THEY CALLED HIM DEAD ON TIME. [C#7]

HE PAINTED THE NAME ON THE BONNET IN BLACK

AND THE STATION KIDS ON THE MAILMAN?S TRACK
STILL LOOK OUT FOR THE DUST OF DEAD ON TIME. [B][F#]

YEAH!  STILL L[C#7]OOK OUT FOR THE DUST OF DEAD ON TIME. [F#]
