{title: Bonita}
{artist: Arcángel}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, flamenco, nuevo flamenco}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 118526
# Empreinte source SHA256: 187839ce88bc28f279a46a5dabd1d6009ae53772dcff229e8dea986b78036b8b
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

AYER TE VI B[F#m]ONITA [D][A][E]
[F#m]CAMINANDO P[D]OR LA PLAYA S[A]OLA Y DESOR[E]IENTADA  MA
[F#m]POR QUE [D]TE ENCUENTRAS SO[A]LITA [E]
[F#m]TU MERECES [D]SER AMADA, QU[A]ERIDA Y NO MAL[E]TRATADA  MA
[F#m]SI QUIERES Y[D] PUEDES [A]YO TE VOY A AY[E]UDAR
[F#m]SI TE GUSTA Y [D]NO TE ASUSTA S[A]E QUE T[E]E VA A ENCANTAR
[F#m]SI TU QUIERES [D]YO ME ENTREGO [A]SI TU QUIERES  V[E]OY POR TI
[F#m]TU SABES QUE POR T[D]I ME MUERO, P[A]OR TI YO PODRIA MO[E]RIR
[F#m]DEJAME DECIRTE C[D]OSAS AL OIDO M[A]AMA QUE YO [E]SE QUE TE PUEDEN
AYUDA[F#m]R
OU NO N[D]O MAS YO S[A]E QUE A TI T[E]E VA GUSTAR
[E]ARCANGEL PA?
?LA SEGUNDA ESTROFA SE TOCA COMO LA PRIMERA?

AYER TE VI BONITA
CAMINANDO POR LA PLAYA SOLA Y DESORIENTAD MA
POR QUE TE ENCUENTRAS SOLITA
TU MERECES SER AMADA QUERIDA Y NO MALTRATADA MA
[E]MAMBO KINGS
SI TU QUIERES YO ME ENTREGO SI TU QUIERES VOY POR TI
TU SABES QUE POR TI ME MUERO, POR TI YO PODRIA MORIR
SI QUIERES Y PUEDES  YO TE VOY A LLEVAR
SI TE GUSTA Y NO TE ASUSTA SE QUE TE VA A ENCANTAR
[F#m]VENTE CONMIGO QUE [D]YO SE QUE TE HAGO S[A]ENTIR COSAS BOOM
 BOOM [E]BOOM MARIPOSA
[F#m]YO TE PROMETO UNA [D]VIDA AMOROSA, AMOR[A]ES SITUACIONES
 PENOSAS[E]
[F#m]YO TE PROMETO TERN[D]URA NOC[A]HES DE PASION Y D[E]E MUCHA LOCURA
[F#m]YO TE PROMETO SER Y[D]O TU NENE  ( [A]REAL) YO TU[E] NENE?..
SI TU QUIERES YO ME ENTREGO SI TU QUIERES VOY POR TI
TU SABGES QUE POR TI ME MUERO, POR TI YO PODRIA MORIR

ESTA CANCION VA DEDICADA A TODAS AQUELLAS PERSONAS
QUE DE UNA U OTRA FOR CREEN EN EL AMOR COMO YO PARTE
DE LA MARAVILLA?????.
