{title: Ombro Amigo}
{artist: Grupo Revelação}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, pagode}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 133105
# Empreinte source SHA256: 1534a7392343cf68f8d422282b8ca4ab751396f4fadb2094e265962a32ba8b17
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : Acompanhamento do solo: Am G Am G E7}
# SOURCE A VERIFIER:             Acompanhamento do solo:  Am     G    Am   G    E7
[Am]*Você é meu [E/G#]ombro amigo.[Am7/9].....motivo do[Em/G] meu sorriso......
[Dm/F] Você é meu[G] mundo de pai[C6/9]xão..... meu am[E7/9]or........
[Am] Contigo me re[E/G#]alizo....[Am7/9]você é meu pa[Em/G]raíso.......
[Gm7] A luz que eu tanto p[C7/9]reciso.....[F7+].... pra ilum[F6]inar meu vi[Bm7/5-]ver.....[E7/9]..
[Am]** Você sed[E/G#]uziu meu olhar.[Am7/9].......atiçou me[Em/G]u desejo.......
[Dm/F] Adoro seu [G]jeito de a[Bm7/5-]mar......do sabor[E7/9] do teu beijo......
[Am] Meu sonh[E/G#]o bom de sonhar [Am7/9]....... encontrei minha [Em/G]paz........
[Dm/F] Você tem o[G7] dom de encan[Bm]tar.......te [E7/9]amo demais.......
[A7+] A feli[E/G#]cidade amor..[Em/G]...... com você [A7]vou encont[D]rar.......
 No seu corpo [D5+]sedutor.[D6]........ Quero s[E7]empre despertar ........
[A7+] Perder para o [E/G#]desamor....[Em/G]......   outra[A7] vez nem pensa[D]r.......
{comment: À vérifier : D5+ D6 E7 (Introdução e volta no * )}
# SOURCE A VERIFIER:             D5+         D6          E7           (Introdução e volta no * )
 Enfim expulsei a dor ........vou viver pra te amar........
 Na 2ª vez canta-se assim :
[Am] **Você sed[E/G#]uziu meu olhar...me conqu[Am7/9]istou........ atiçou[Em/G] meu desejo... com seu calor...
[Dm/F] Adoro o seu j[G]eito de amar..... minha se[Bm7/5-]dução ... o sabor[E7/9] do teu beijo...meu mar de emoção...
    [Am] Meu sonho [E/G#]bom de sonhar .. seja sempre [Am7/9]assim....encontrei [Em/G]minha paz...pra não mais ter fim..
[Dm/F] Você tem o[G7] dom de encantar....... te quero pr[Bm]a mim........ Te [E7/9]amo demais......
Refrão....
