{title: Amor Covarde}
{artist: Aviões do Forró}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, forro, pagode, sertanejo, sertanejo universitario}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 87470
# Empreinte source SHA256: 153771a18c7ffb8c0d57d19ab1e088e9ddffc582a6fba2a5c532d2eadec5f4fb
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : Intro: E/B/A/E...}
# SOURCE A VERIFIER:             Intro: E/B/A/E... 

[E]Quando a gente fica junto, tem b[B]riga...
Quando a gente se se[A]para, a saud[E]ade...
Quando marca um encontro disc[B]ute...
Desconheço um amor [A]tão co[E]varde...
[E]Quando a gente fica junto, tem [B]briga...
Quando a gente se se[A]para, a saudade...
[E]Quando marca um encontro discu[B]te...
Desconheço um amor [A]tão co[E]varde...
{comment: À vérifier : E B c#m}
# SOURCE A VERIFIER: E                      B            c#m 
não vou mais me preocupar com a situação...
[A]A gente se abraça e se [B]beija, com tanta tern[E]ura
[B]Mas sempre surge qualquer coisa de errado no [A]tempo
sem ver nem[E] porque...
De[B]talhes que somente o [A]tempo, pode re[E]solver...
[E]Se o erro foi meu, eu as[B]sumo...não quero [C#m]saber
Lhe [A]peço um milhão de des[B]culpa se preciso [E]for
Não [B]meço limite, dist[A]ância faço qual[E]quer coisa pra não
te per[B]der...
[E]Espero que você tam[B]bém, seja capaz de [A]fazer...
[E]Eu vou fazer de [B]tudo..
Bato perna, viro [A]o mundo se tiver que s[E]er..
Pra ter você co[B]migo, posso fazer qualquer [A]coisa, é só
me di[E]zer..
Me mate de saud[B]ade, de ciume, só não me [A]peça pra te
esque[E]cer..
Me ame do seu [B]jeito, todo mundo tem de[A]feito..
Por que não vo[E]cê?
