{title: Simples olhar}
{artist: Jorge Aragão}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, axe, mpb, pagode, samba}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 81941
# Empreinte source SHA256: c139321c3849531695192075c5f966f64681e55668b8b42a0b73625ed3e29388
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tablature_conservee_en_commentaire, tabulations_interpretees_4_colonnes, tonalite_absente

            Intodução:
# TAB: Solo: 17-16-25-36-47-36___17-16-25-36-47-36___36 36-27-27 27-35-35 35-25-25 25-36 
..[A7+]..Um simples olhar..[A°]..tem tanto poder....
.[Em/G]...Depende do [F#7]quanto e de quem....
.[Bm]...Do fogo e do[E7/9] jeito que vem....
.[A7+]...Quem quer se entregar.[A°]...no mínimo deve ter....
.[Em/G]...Desejo até q[F#7]uase plantar.[Bm]...um beijo na b[E7/9]oca de alguém....
.[G#m5-/7]...Um desses peca[C#7]dos que ninguém t[F#m7]em...."quase ninguém"
.[G#m5-/7]...Um dissimu[C#7]lado calor faz[F#m7] bem....
.[C#m5-/7]...E quando escond[F#7]er já cabe em nó[Bm]s....
.[C#m5-/7]........[Dm5-/7].......[D#m5-/7]...Um doce arrepio e[G#7]nche nossa voz.[C#7+]...
.[Bm]...De praz[E7/9]er  [E7/9-]

 1ªvez volta ao inicio

.[A7+]...Um simples olhar.[A°]...tem tanto poder....
.[Em/G]...Depende do qu[F#7]anto e de quem....           ||2X
.[Bm]...Do fogo e do [E7/9]jeito que vem....            ||
.[D#m]...D[Em/G]esejo até qu[F#7]ase plantar....
.[Bm]...Um beijo na [E7/9]boca de alguém....
.[D#m]....[Em/G]....Depende do q[F#7]uanto e de quem....
.[Bm]...Do fogo e do [E7/9]jeito que vem....
.[D#m]....[Em/G]....Desejo até q[F#7]uase plantar.[Bm]...."Um beijo"
