{title: Golden Ring}
{artist: George Jones}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, country, country rock, honky tonk}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 52235
# Empreinte source SHA256: 6799705d810815bc93fe9d0911dac9216446be7227f65155d3fa1a770305af4c
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

            (T.W.)
IN A [G]PAWN SHOP IN CHICAGO

ON A SUNNY SUMMER DAY
A [D7]COUPLE GAZES AT THE WEDDING [G]RINGS
THERE [C]ON DISP[G]LAY

(G.J)
SHE [G]SMILES N' NODS HER HEAD

AS HE SAYS, "HONEY THAT'S FOR YOU,
IT'S NOT MUCH, BUT IT'S THE [D7]BEST
THAT I CAN [G]DO."

(CHORUS-BOTH)
[G]GOLDEN RINGS (GOLDEN RING) WITH ONE TINY LITTLE STONE
WAITING [D7]THERE (WAITING THERE) FOR SOME[G]ONE TO TAKE YOU HOME

BY ITSELF (BY ITSELF) IT'S JUST A COLD METALLIC THING
ONLY LOVE CAN MAKE A [D7]GOLDEN WEDDING RING

(T.W.)
IN A LITTLE WEDDING CHAPEL
LATER ON THAT AFTERNOON
AN OLD UPRIGHT PIANO PLAYS
THAT OLD FAMILIAR TUNE

(G.J.)
TEARS ROLL DOWN HER CHEEKS
AND HAPPY THOUGHTS RUN THROUGH HER HEAD
AS HE WHISPERS LOW,
"WITH THIS RING, I THEE WED."

CHORUS- BOTH
GOLDEN RING (GOLDEN RING) WITH ONE TINY LITTLE STONE
SHINING RING (SHINING RING) NOW AT LAST IT'S FOUND A HOME
BY ITSELF (BY ITSELF) IT'S JUST A COLD METALLIC THING
ONLY LOVE CAN MAKE A GOLDEN WEDDING RING

(T.W.)
IN A SMALL TWO ROOM APARTMENT
AS THEY FOUGHT THEIR FINAL ROUND
HE SAYS, "YOU WON'T ADMIT IT,
BUT I KNOW YOU'RE LEAVIN' TOWN."

(G.J.)
SHE SAYS, "ONE THING'S FOR CERTAIN,
I DON'T LOVE YOU ANY MORE."
AND THROWS DOWN THE RING
AS SHE WALKS OUT THE DOOR

CHORUS- BOTH
GOLDEN RING (GOLDEN RING) WITH ONE TINY LITTLE STONE
CAST ASIDE (CAST ASIDE) LIKE THE LOVE THAT'S DEAD AND GONE
BY ITSELF (BY ITSELF) IT'S JUST A COLD METALLIC THING
ONLY LOVE CAN MAKE A GOLDEN WEDDING RING

(BOTH)
IN A PAWN SHOP IN CHICAGO
ON A SUNNY SUMMER DAY
A COUPLE GAZES AT THE WEDDING RINGS
THERE ON DISPLAY,
GOLDEN RING.
