{title: Songs About Texas}
{artist: Pat Green}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, texas country}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 120551
# Empreinte source SHA256: a6283948d7f622536f2d6d4effc7952ef21e391a416110914ff413cfc7eb836e
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

I SING SONGS A[A]BOUT TEXAS
[D]SING THEM OFTEN AS I[A]F SHE WAS SOME OLD LOVER [E]I USED TO KNOW
[A]WISH I COULD FOLLOW THEM B[D]ACK TO THE HOMELAND EVERY TI[A]ME
I HEAR ONE ON MY [E]RADI[A]O

TWIN FIDDLES PLAYING IN MY MEMORY
MY DADDY SANG THE WONDERS OF OLD COW TOWN
SILVER HAIR AND HE'S STILL THERE UNDER A SKY SO WARM AND FAIR
I TELL YOU FRIENDS THERE'S A SONG IN EVERY TOWN.

[E]SING ME ONE MORE SONG A[D]BOUT OLD SAN AN[A]TONE
[E]SEEMS LIKE A DREAM NOW IT WAS [D]SO LONG A[A]GO
[E]GUY CLARK HE CAN BE JUST LIKE A[D] COAT FROM TH[F#m]E CO[E]LD
[A]SONGS ABOUT TEXAS [D]SING THEM OFTEN EVERY TIM[A]E
[E]I THINK I'VE GOT NO [A]HOME

NOTHING SHORT OF THE GOSPEL HYMNS
I GUESS THAT'S WHY FOLKS KEEP WRITING 'UM
AND WHEN I DIE
I WANT TO GO THERE TOO

SOMEDAY I HOPE TO WALK ALONG HEAVENS STREET
I'LL STILL BE LOOKING FOR MY TACO MEAT
AND I SWEAR I HEAR A STEEL GUITAR
JUST RISING IN THE AIR

{start_of_chorus: CHORUS}

WHEN THE NIGHT IS REAL REAL STILL
I SWEAR I COULD HEAR A WHIPPEREWILL
SHE KNOWS THERE'S MUSIC IN THE IN THE DIRT DOWN THERE
HILL COUNTRY RAIN IS A CLEANSING THING AND I HAVE TO SEE ONE
AND I'LL BE SITTING IN A SHALLOW CREEK WITH NOTHING TO DO

{end_of_chorus}
{start_of_chorus: CHORUS}

LAST CHORUS
SING ME ONE MORE SONG ABOUT OLD SAN ANTONE
THEM HONKY TONK ANGELS AND THEIR LONELY BE HIVE PAIN
WISH I WAS STOWED AWAY ON SOME FAST MOVING TRAIN GOING HOME
SONGS ABOUT TEXAS SING THEM OFTEN EVERY TIME
I THINK I'VE GOT NO HOME

{end_of_chorus}
