{title: Que Voy A Hacer Conmigo}
{artist: Ricardo Arjona}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-pt, cantautor, latin, latin arena pop, latin pop, rock en espanol, tropical}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 11982
# Empreinte source SHA256: 8a81e7be59667d3ccdfe81216f16a7c16fa77b8634d0198c5096503cfb8dab55
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

AHORA QUE NO ESTAS, [B]
HOGAR LO ESCRIBO SIN [E]?H?,
Y LA PALABRA AM[B]OR LA CAMBIE POR DO[G#m]LOR.
ES TAN POBRE MI PRE[E]SENTE QUE SE ENDEUDA SO[B]ÑANDO
Y ES TAN RICO EL PA[F#7]SADO QUE AUN SIGO RECOR[B]DANDO.

*
AHORA QUE NO ESTAS,
ESTOY ABANDONADO COMO UN BOTE DE BRONCEADOR,
EN CASA DE ESQUIMALES.
MI HOROSCOPO DICE SON PROBLEMAS ASTRALES,
Y HE LLEGADO AL EXTREMO DE ENVIDIAR ANIMALES.

**
Y NUESTRO C[G#m]UARTO ES ALMACEN DE REC[F#7]UERDOS,
Y NUESTRA ME[E]SA ES AEROPUERTO DE MOS[B]CAS,
Y NUESTRA C[G#m]AMA ES UN INMENSO DESIE[F#7]RTO,
CON LA VI[E]DA Y LA ENERGIA DE UN MUE[F#7]RTO.

**
QUE VOY A HACER CON[B]MIGO,
QUE DIFICIL ES AM[F#7]AR AL OGRO DE MI PROPIO C[G#m]UENTO,
COMO ACEP[E]TAR QUE SOY COMO UN DELFIN
TIRADO EN UN DES[F#7]IERTO.

***
QUE VOY A HACER CONMIGO,
SI EL IDIOTA DEL ESPEJO SUELE SER MI UNICO AMIGO
SI HE CONFUNDIDO LA ALMOHADA MAS DE MIL VECES CONTIGO.

QUE VOY A HAC[F#7]ER CONMIGO,
AHORA QUE NO [B]ESTAS.

*
AHORA QUE NO ESTAS
EL SILENCIO ES UN RUIDO
QUE LASTIMA TREMENDAMENTE MIS OIDOS
SI ENCIENDO LA RADIO VUELVO A RECORDARTE
Y SI ES QUE LA APAGO NO QUIERO OLVIDARTE.

**
Y NUESTRO CUARTO ES ALMACEN DE RECUERDOS
Y NUESTRA MESA ES AEREOPUERTO DE MOSCAS
Y NUESTRA CAMA ES UN INMENSO DESIERTO
CON LA VIDA Y LA ENERGIA DE UN MUERTO.

***
QUE VOY A HACER CONMIGO,
QUE DIFICIL ES AMAR AL OGRO DE MI PROPIO CUENTO
COMO ACEPTAR QUE SOY COMO UN DELFIN
TIRADO EN UN DESIERTO.

***
QUE VOY A HACER CONMIGO,
SI EL IDIOTA DEL ESPEJO SUELE SER MI UNICO AMIGO
SI HE CONFUNDIDO LA ALMOHADA MAS DE MIL VECES CONTIGO.

Si hay algun error por favor avisame.
Desde COLOMBIA. Tato.
