{title: Desaparecidos}
{artist: Los Fabulosos Cadillacs}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, argentine rock, latin alternative, latin rock, rock en espanol, ska argentino}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 34835
# Empreinte source SHA256: f841f0de607b4b09bbd1e4d8effb917369b469f1199a61c1a5749216f94cf657
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

            ESTA CANCION SE LLAMA DESAPARICIONES Y NO ES DE LOS
CADILLACS,AUNQUE LA TOCAN COMO COVER... DUDAS O
CORRECCIONES
 ESCRIBANME....    SUERTE!

[Am]QUE ALGUIEN ME DIGA SI HA VISTO [E7]A MI ESPOSO
[Am]SE LLAMA ERNESTO Y TIENE [E7]CUARENTA AÑOS
[F]TRABAJA DE PEON EN UN NEGOCIO [C]DE AUTOS
[F]LLEVA CAMISA OSCURA PANTALON [C]CLARO
SALIO DE [E7]NOCHE... Y NO HA [Am]REGRESADO
[D]Y NO SE YO YA QUE PEN[E7]SAR..
PUES ESTO ANTES NO ME HABIA PA[Am]SADO
OH OH OH [E7]OH ... NO ME HABIA PA[Am]SADO

[E7] [Am]

[Am]LLEVO TRES DIAS BUSCANDO A [E7]MI HERMANA
[Am]SE LLAMA ALTAGRACIA IGUAL Q[E7]UE LA ABUELA
[F]SALIO DEL TRABAJO PARA LA [C]ESCUELA
[F]LLEVABA PUESTOS JEANS Y UNA CAMISA [C]BLANCA
NO HA SIDO [E7]EL NOVIO... EL TIPO ESTA EN SU [Am]CASA
[D]NO SABEN DE ELLA EN LA PO[E7]LICIA..
NI EN EL HOS[Am]PITAL
OH OH OH [E7]OH... NI EN EL HOS[Am]PITAL

[E7] [Am]

[Am]QUE ALGUIEN ME DIGA SI HA VISTO [E7]A MI HIJO
[Am]ES ESTUDIANTE DE ME[E7]DICINA
[F]SE LLAMA AGUSTIN Y ES UN BUEN [C]MUCHACHO
[F]MAS A VECES TERCO CUANDO [C]OPINA
SE LO HAN LL[E7]EVADO, NO SE QUE [Am]FUERZAS
[D]PANTALON BLANCO CAMISA A [E7]RAYAS
PASO ANTE[Am]AYER
OH OH OH [E7]OH... PASO ANTE[Am]AYER

[E7] [Am]

[Am]A DONDE VAN LOS DESAPARE[E7]CIDOS
BUSCA EN EL AGUA Y EN LOS MATO[Am]RRALES
Y PORQUE ES QUE SE DESA[E7]PARECEN
PORQUE NO TODOS SOMOS [Am]IGUALES
CUANDO REGRESA EL DESA[E7]PARECIDO
CADA VEZ QUE LO TRAE EL PENSA[Am]MIENTO
QUE COSA SON LOS DESA[E7]PARECIDOS
UNA EMOCION QUE TE APRIETA [Am]POR DENTRO

[Am]CLARA QUIÑONES SE LLAMA MI [E7]MADRE
[Am]ELLA ES UN ALMA DE DIOS QUE NO SE METE [E7]CON NADIE
[F]SE LA HAN LLEVADO DE [C]TESTIGO
[F]POR UN ASUNTO QUE ES NADAMAS [C]CONMIGO
Y FUI A ENTRE[E7]GARME HOY POR LA [Am]TARDE
[D]Y AHORA NO SABEN QUIEN SE LA [E7]LLEVO
DEL [Am]CUARTEL
OH OH OH [E7]OH.. QUIEN SE LA [Am]LLEVO

[E7] [Am]

[Am]ANOCHE ESCUCHE VARIAS EX[E7]PLOSIONES
[Am]TIROS DE ESCOPETA Y DE [E7]REVOLVER
[F]AUTOS ACELERADOS FRENOS [C]GRITOS
[F]ECOS DE BOTAS EN LAS [C]CALLES
TOQUES DE [E7]PUERTA QUEJAS POR DIOSES [Am]PLATOS ROTOS
[D]ESTABAN DANDO LA TELE[E7]NOVELA
POR ESO NADIE MIRO PA´ [Am]FUERA
OH OH OH [E7]OH... NADIE MIRO PA´[Am]FUERA

[E7] [Am]

[Am]A DONDE VAN LOS DESA[E7]PARECIDOS
BUSCA EN EL AGUA Y EN LOS [Am]MATORRALES
Y POR QUE ES QUE SE DESA[E7]PARECEN
PORQUE NO TODOS SOMOS [Am]IGUALES
CUANDO REGRESA EL DESA[E7]PARECIDO
CADA VEZ QUE LO TRAE EL [Am]PENSAMIENTO
QUE COSA SON LOS DESA[E7]PARECIDOS
UNA EMOCION QUE TE APRIETA POR [Am]DENTRO

[E7] [Am]
