{title: Romeo Y Julieta}
{artist: Aventura}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, bachata, bachata dominicana, latin, latin hip hop, latin pop, trap latino, tropical}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 15600
# Empreinte source SHA256: f8945648236f060013c828cf4ee9db5eb905a8cf09bb08ac14f869aad30fba2f
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tabulations_interpretees_4_colonnes, tonalite_absente

{comment: À vérifier : INTRO: Bm A G F#-F#7}
# SOURCE A VERIFIER:             INTRO: Bm A G F#-F#7 

[G]EXPLICAME POR QUE RAZ[A]ON NO ME MIRAS L[Bm]A CARA...
[G]SERA QUE NO QUIERES QUE [A]NOTE QUE SIGUES ENA[Bm]MORADA...
[G]TUS OJOS DEMUESTRAN PASI[A]ON Y FALSOS SENTIMI[Bm]ENTOS...
{comment: À vérifier : G A Bm A -A -Bm}
# SOURCE A VERIFIER: G                       A                            Bm       A -A -Bm 
POR EL HECHO DE TU RECHAZARME MIENTRAS TE MUERES POR DENTRO...

[Em]SABES BIEN QUE NO PUEDES OLVI[A]DARME Y MUCHO MENO'..ENG[Bm]AÑARME
{comment: À vérifier : G A Bm A -A -Bm}
# SOURCE A VERIFIER: G                          A                  Bm     A -A -Bm 
TODAVIA NO HA NACIDO OTRO HOMBRE QUE PUEDA ENAMORARTE

[D]SI ANTES DE INVENTARSE EL A[A]MOR YA YO TE ESTABA AM[Bm]ANDO...
{comment: À vérifier : G A Bm A -A -Bm}
# SOURCE A VERIFIER: G                          A                  Bm     A -A -Bm 
NI EL AMOR DE ROMEO Y JULIETA LLEGO A SER TAN GRANDE...

[Em]TE VOY A SER SINCERO Y CONFIE[A]SO NO TE MIENTO TE EXTR[Bm]AÑO...
[G]Y APESAR QUE TRANSCURRIO TANTO EL T[A]IEMPO AUN GUARDO TU RETR[Bm]ATO...
(PAUSA)
{comment: À vérifier : ...................G A Bm}
# SOURCE A VERIFIER: ...................G                 A                          Bm 
Y A DONDE IRA ESTE AMOR, TODITA LA ILUSION ME PREGUNTO A CADA INSTANTE...
YO SE QUE YO FALLE[G] PERO TU ORGULLO Y TU ACTIT[A]UD ME IMPIDEN RECUPERA[Bm]RTE...
NIEGAS SENTIR AMOR[G], OCULTAS LA PASI[A]ON Y TAMBIEN ME RECH[Bm]AZAS...
CONMIGO NO PODRA[G]S, TE CONOZCO DE MA[A]S, TU TODAVIA ME A[Bm]MAS...
     G....(PAUSA)...................................Bm
NO IMPORTA QUE HOY TE ALEJES DE MI ME EXTRAÑARAS MAÑANA...

{start_of_part: INTRO}

[G]Y HOY DISFRAZAS LO QUE POR MI S[A]IENTES Y MUY DISPUESTA A V[Bm]ENCER...
[G]INCLUSO DICES QUE ME ODI[A]AS Y QUE EL AMOR SE [Bm]TE FUE...
MIRA MIS O[G]JOS CONVENCEM[A]E QUE YA TU NO ME AM[Bm]AS...
{comment: À vérifier : G A Bm A -A -Bm}
# SOURCE A VERIFIER:            G                      A                   Bm   A -A -Bm 
Y ENTONCES SI NO TE HARE MAS CANCIONES NO DIRE MAS PALABRAS...

[Em]DISIMULAS AL DECIR QUE NO ME A[A]MAS QUE ESO FUE EN EL PAS[Bm]ADO...
{comment: À vérifier : G A Bm A -A -Bm}
# SOURCE A VERIFIER:          G                   A                     Bm  A -A -Bm 
PERO EL AMOR NO SE PUEDE OLVIDAR SIEMPRE QUEDA GRAVADO...

EN T[D]U DIARIO SE CONSERVA LA H[A]ISTORIA DE DOS ENAMORA[Bm]DOS...
{comment: À vérifier : G A Bm A -A -Bm}
# SOURCE A VERIFIER:       G                     A                   Bm  A -A -Bm 
LAS NOVELAS Y POESIAS DE AMOR LAS VIVIRE A TU LADO...

REC[Em]UERDA CUANDO TE HICE MUJE[A]R EN AQUELLA MADRUG[Bm]ADA...
CUANDO TE CANT[G]ABA CON MI GUITA[A]RRA Y LUEGO TU ME BES[Bm]ABAS...
AY..MI NIÑA[G] NO TE HAGAS EXTRAÑ[A]O SABIENDO QUE ME AM[Bm]AS...

(PAUSA)
{comment: À vérifier : ...................G A Bm}
# SOURCE A VERIFIER: ...................G                 A                          Bm 
Y A DONDE IRA ESTE AMOR, TODITA LA ILUSION ME PREGUNTO A CADA INSTANTE...
YO SE QUE YO FALLE[G] PERO TU ORGULLO Y TU ACTIT[A]UD ME IMPIDEN RECUPERA[Bm]RTE...
NIEGAS SENTIR AMOR[G], OCULTAS LA PASI[A]ON Y TAMBIEN ME RECH[Bm]AZAS...
CONMIGO NO PODRA[G]S, TE CONOZCO DE MA[A]S, TU TODAVIA ME A[Bm]MAS...
NO IM[G]PORTA QUE HOY TE ALEJES DE [A]MI ME EXTRAÑARAS MAÑA[Bm]NA...

     G....(PAUSA)...................................Bm
NO IMPORTA QUE HOY TE ALEJES DE MI ME EXTRAÑARAS MAÑANA...

{end_of_part}
