{title: Rhythm Guitar}
{artist: Emmylou Harris}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, country rock, folk, folk rock, lilith, melancholia, mellow gold, roots rock, singer-songwriter}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 65663
# Empreinte source SHA256: 9da6efa6b6ccd8151fa1adcb9f2677fab5db5ff55f2018ecf8f216dda0d6e525
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tonalite_absente

{comment: À vérifier : Intro: D|D|G|G|A|D}
# SOURCE A VERIFIER: Intro: D|D|G|G|A|D 

{start_of_verse: verse 1}
[D]She played around town till she opened the show......
For a high rolling singer up from[A] Tupe[D]lo
[D]He saw her in the lights and he gave her a hand......
[D]Next thing Sally knew she was o[A]ne of the [D]band...

[D]She said do[G]n't give me nothing that I can't us[D]e......
[D]I got the rhythm and I d[A]on't need the b[D]lues...
[G]I don't ride no shooting s[D]tar.......
[D]Just wanna play on the r[A]hythm g[D]uitar...

{end_of_verse}
{start_of_verse: verse 2}
[D]She was the sweetest thing that he ever had seen......
[D]And he had quite a few of them ba[A]ckstage q[D]ueens...
[D]She was the prettiest thing that he ever had heard......
[D]Playing rhythm guitar and s[A]inging the t[D]hird...

[D]She said do[G]n't give me nothing that I can't us[D]e......
[D]I got the rhythm and I d[A]on't need the b[D]lues...
[G]I don't ride no shooting s[D]tar......
[D]Just wanna play on the r[A]hythm g[D]uitar...

{comment: À vérifier : Guitar Solo}
# SOURCE A VERIFIER: Guitar Solo 
[D] [A] [D]
[D] [A] [D]

{end_of_verse}
{start_of_verse: verse 3}
[D]Well Sally keeps her feet planted on the ground......
[D]She don't lose her head when the s[A]un goes d[D]own...
[D]Everybody's out looking for romance......
[D]But Sally just wants to get p[A]eople to d[D]ance...

[D]She said do[G]n't give me nothing that I can't us[D]e......
[D]I got the rhythm and I d[A]on't need the b[D]lues...
[G]I don't ride no shooting s[D]tar......
[D]Just wanna play on the r[A]hythm g[D]uitar...

[D]She said do[G]n't give me nothing that I can't us[D]e......
[D]I got the rhythm and I d[A]on't need the b[D]lues...
[G]I don't ride no shooting s[D]tar......
[D]Just wanna play on the r[A]hythm g[D]uitar...

{end_of_verse}
{start_of_part: Outro}
[D]Just wanna play the r[A]hythm g[D]uitar...

{end_of_part}
