{title: Con Un Par}
{artist: Joaquín Sabina}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, cantautor, nueva cancion, rock en espanol, spanish pop, trova}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 26885
# Empreinte source SHA256: 77a19c2900b484bb3cf9df05d43b05f60343b5987f5fd48df2800b786f9d20dc
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: accord_apres_fin_ligne, tabulations_interpretees_4_colonnes, tonalite_absente

LO PRIMERO QU[C]E HIZO EL DIONI AL LLEGA[F]R A RIO [C]
[E7]FUE BRINDAR CON EL ESPEJO Y DECIR '¡QUE T[Am]IO!'.
[F]NO VEAS QUE PASON
[C]DE ENTRADA EN EL RESTAURANT,
[D7]NIÑAS AL SALON
QUE EL DIONI EST[G]A EN LA CIUDAD.
[C]CON SU BUEN PAR DE Z[F]APATOS DE COCODRI[C]LO
[E7]NO SE LE RESISTE NI LA VENUS DE M[Am]ILO
[F]SOBRE TODO SI
[C]LE PAGAN POR UN FRANCES
[D7]DOS VECES LO QUE EN MADRID
GANABA CURR[G]ANDO UN MES.
[F]PORQUE LAS MULATAS [G]CUANDO SON DE BANDERA
[Dm]CONFUNDEN EL CORAZON CON LA BI[C]LLETERA,
[G]Y LA PASMA,
[C]QUE TE VE CARA DE PRINGAO,
[G]VE FANTASMAS
[C]SI ENCIMA CORTAS EL BACALAO.
[G]AY DIONISIO,
[C]FUE TOTAL LO DEL BANCO, SIN UN MAL TIRO,
[G]MUCHO 'VISIO',
[C]TRINCAR EL PASTON Y PEGARSE EL PIRO.
[F]LA DE NOCHES QUE HE DEDICADO YO A PLA[E]NEAR
[G7]UN GOLPE COMO EL QUE DISTE TU CON UN P[C]AR.

MARCANDOSE UNA LAMBADA EN COPACABANA
AUN FLIPA REMEMORANDO AQUELLA MAÑANA
EN QUE DECIDIO
JUGARSELA A CARA O CRUZ,
PARA UNA VEZ QUE TE SALE UN ORDAGO CLARO AL MUS.
TUMBADO AL SOLETON DE IPANEMA SUEÑA
DESPIERTO; ¡COMO VA A ALUCINAR LA PEÑA,
VIENDO TU FOTO EN LA
PORTADA DEL INTERVIU!
POCO VA A 'GOSAR'
TU CUERPO EL CAMBIO DE LOOK.
VAYA NIVELON,
MENUDO APRENDIZ DE BRUJO,
NARIZ A LO INDIANA JONES,
PELUQUIN DE LUJO,
PERO AL LORO,
QUE EL DESTINO ES UN MARICON,
SIN DECORO
TE DA CHAMPAN Y DESPUES CHINCHON.
AY DIONISIO,
FUE TOTAL LO DEL BANCO SIN UN MAL TIRO,
MUCHO 'VISIO',
TRINCAR EL PASTON Y PEGARSE EL PIRO.
LA DE NOCHES QUE HE DEDICADO YO A PLANEAR
UN GOLPE COMO EL QUE DISTE TU CON UN PAR.
UN BOCATA CON LIMA TE LLEVARE
CON ESTA SALSITA ENCIMA A CARABANCHEL.
AL DIA SIGUIENTE DEL ROBO
Y PARECIA TAN BOBO
COMENTO EN EL BAR
UNO QUE TE CONOCIA
Y EL CAMARERO DECIA
'CHAPEAU' PORQUE TE LO HABIAS
SABIDO MONTAR
CON CLASE Y CATEGORIA,
COMO UN 'NUMBER ONE'
Y UN JUBILETA AÑADIA,
PUESTOS A INCORDIAR,
QUE MADRID TE DEBERIA
'PRIMO' LEVANTAR
UN BUSTO EN PLENA GRAN VIA
A CARGO POPULAR
Y UNA PLACA QUE DIRIA
'AL DIONI, CON UN PAR'
Y TODO EL MUNDO ASENTIA.
ESTA SALSITA VIAJERA PA TI
PUEDE BAILARLA CUALQUIERA.
UN BOCATA CON LIMA TE LLEVARE
CON ESTA SALDITA ENCIMA A CARABANCHEL.
DESTINO CHUNGO,
CRUEL Y CANALLA,
TE DA CHAMPAN
Y DESPUES CAZALLA.
UN BOCATA CON LIMA TE LLEVARE
CON ESTA SALSITA ENCIMA A CARABANCHEL.
Y TODO EL MUNDO ASENTIA,
Y YO MIENTRAS LOS OIA
COMPUSE ESTE 'TUMBAO',
QUE VENGA LA POLICIA
Y NOS QUITE LO BAILAO,
QUE ES MAS VACILON EL RITMO
CUANDO ES AGARRAO,
QUE SUELTO PA MI NO TIENE
CARNE NI PESCAO,
SE BAILA EN ANDALUCIA
CON MAS SON QUE EN BILBAO
Y EN NUEVA YORK LOS MORENOS
LO HACEN SWINGEAO,
Y TU SIN PERJUDICAR
A NADIE Y ESPOSAO,
QUE LA LEY DE EXTRADICION
TE PILLE 'CONFESAO'.
