{title: Forgiveness}
{artist: Don Henley}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-en, album rock, art rock, classic rock, country rock, folk, folk rock, heartland rock, mellow gold, new wave pop, pop rock, rock, roots rock, singer-songwriter, soft rock, yacht rock}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 47228
# Empreinte source SHA256: 10a398df13b22e05d1547703be8392d1ae7732c3cc35a19210b0569ec7ac65d6
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: tabulations_interpretees_4_colonnes, tonalite_absente

I GOT A CALL[D] TO DAY THAT I [A]DIDDINT WANT TO HEAR
BUT I [G]KNEW THAT IT WOULD COME
[D]OLD TRUE FREIND [A]OF OURS WAS TALKING ON THE PHONE
SHE SAID YOU [G]FOUND SOMEONE
AND I [A]THOUGHT OF ALL THE BAD LUCK
AND S[A7]TRUGGLES WE WENT THRUOGH
HOW [A]I LOST ME AND Y[G]OU LOST YOU
[A]WHAT ARE ALL THESE VOICES O[A7]UTSIDE LOVES OPEN DOOR
MAKE US [G]THROW OFF OUR CONTENTMENT AND [A]BEG FOR SOMETHING MORE
[D] IM LEARNING TO [D9]LIVE WITHOUT YOU [D]NOW
BUT I [G]MISS YOU SOMETIMES
[D]THE MORE I KNOW THE[BM] LESS I UNDERSTAND
ALL THE [G]THINGS I THOUGHT I KNEW IM [A]LEARNING AGAIN
[D]IVE BEEN TRYING TO GET DOWN[D9] TO THE HEART OF THE MATTER
BUT MY[D] WILL GETS WEA[G]K AND MY THOUGHTS SEEM TO SCATTER
BUT I THINK ITS [D]ABOUT FORGIVENESS[BM],FORGIVENESS
[G]EVEN IF EVEN IF [A]YOU DONT LOVE ME [D]ANYMORE
[D]AH THESE TIMES ARE SO UNCERTIAN
THERES A [A]YEARNING UNDEFINED [G]PEOPLE FILLED WITH RAGE
[D]WE ALL NEED A LITTLE TENDERNESS[A] HOW CAN LOVE SURVIVE
IN [G]SUCH A GRACELESS AGE
[A]THE TRUST AND SELF ASSURANCE THAT[A7] LEADS TO HAPPINESS
[G]WERE THE VERY THINGS WE KILLED I GUESS
OH [A]PRIDE AND COMPETITION CANNOT[A7] FILL THESE EMPTY ARMS
AND THE [G]WORK I PUT BETWEEN US YOU KNOW IT [A]DOESINT KEEP ME WARM
[D]IM LEARNING TO [D9]LIVE WITHOUT YOU[D] NOW
BUT I [G]MISS YOU BABY

[D]THE MORE I KNOW THE [BM]LESS I UNDERSTAND
ALL THE [G]THINGS I THOUGHT I FIGURED OUT I [A]HAVE TO LEARN AGAIN
[D]IVE BEEN TRYING TO GET DOWN[D9] TO THE HEART OF THE MATTER
BUT [D]EVERYTHING CHANGES[G] AND MY FREINDS SEEM TO SCATTER
 BUT I THINK ITS [D]ABOUT FORGIVENESS,[BM]FORGIVENESS
[G]EVEN IF EVEN IF [A]YOU DONT LOVE ME [D]ANYMORE
THERE ARE [C]PEOPLE IN YOUR LIFE WHOOVE C[G]OME AND GONE
THEY [AM]LET YOU DOWN YOU KNOW THEYVE [G]HURT YOUR PRIDE
 YOU B[C]ETTER PUT IT ALL BEHIND YOU BABY CAUSE [G]LIFE GOES ON
YOU KEEP [A]CARRYING THAT ANGER IT WILL [A]EAT YOU UP INSIDE BABY
[D]IVE BEEN TRYING TO GET DOWN[D9] TO THE HEART OF THE MATTER
BUT MY [D9]WILL GETS WEAK [G]AND MY THOUGHTS SEEM TO SCATTER
BUT I THINK ITS [D]ABOUT FORGIVENESS,[BM]FORGIVENESS
[G]EVEN IF EVEN IF [A]YOU DONT LOVE ME [D]ANYMORE
[D]IVE BEEN TRYING TO GET DOWN[D9] TO THE HEART OF THE MATTER
CAUSE THE [D]FLESH WILL GET WEAK[G] AND THE ASHES WILL SCATTER
SO IM THINKING [D]ABOUT FORGIVENESS,[BM]FORGIVENESS
[G]EVEN IF EVEN IF [A]YOU DONT LOVE ME [D]ANYMORE
