{title: Chance}
{artist: Attaque 77}
{status: en_travail}
{tags: import-kaggle, a-verifier, lang-es, argentine punk, argentine rock, latin alternative, latin rock, rock en espanol, ska argentino}

# Import automatique 1.1.0 ; validation musicale non effectuee.
# Source: https://www.kaggle.com/datasets/eitanbentora/chords-and-lyrics-dataset
# Ligne CSV (hors en-tete): 79234
# Empreinte source SHA256: 72a61b5798cedd01c82188132216cef678bf158c0a1ebf12a3edccd08c58b9fa
# Alignement par colonnes du texte source ; aucune syllabe devinee.
# Capo: accords stockes en sons reels, formes source retrouvees par le lecteur.
# Verifications: ligne_accords_non_reconnue, tonalite_absente

{comment: À vérifier : Intro: Piano, E}
# SOURCE A VERIFIER: Intro: Piano, E 

{start_of_verse: Verso}

[E]Día a día aprend[Bm]iendo a ser...
[F#m]Miro hacia atrás y t[A]odo el camino hecho...
[E]Lo que pudo ser y l[Bm]o que fue...
[F#m]Mi oportunidad [A]de comenzar de nuevo...
[F#m]...Y[G#m] lo [C#m]demás... francamente [A]no importa...

[E]Quién fui todo este tie[Bm]mpo no sé...
[F#m]Quién soy o seré, h[A]abré cumplido un sueño...
[E]Intentando la fel[Bm]icidad....
[F#m]A prueba y error, l[A]a vida es un momento...
[F#m]...Y[G#m] lo d[C#m]emás... francamente [A]no importa...

{end_of_verse}
{start_of_chorus: Estribillo}

[F#m]Te miro fijo y me sonreís...
[D]No pierdo un día lejos de ti...
[A]Mi chance es h[E]oy...

[F#m]Miro tus ojos y me veo ahí...
[D]Aprovechando cada ocasión...
[A]Mi chance es h[E]oy...

{end_of_chorus}
{start_of_verse: Verso}

[E]Tantas cosas que habré [Bm]hecho bien...
[F#m]Tantas que hice mal [A]y que ni ahí me entero...
[E]Cuánto que desperdic[Bm]ié sin ver...
[F#m]Que estuviste ahí c[A]onmigo todo el tiempo...
[F#m]...Y hoy[G#m] lo de[C#m]más francamente no [A]importa...

{end_of_verse}
{start_of_chorus: Estribillo}

[F#m]Te miro fijo y me sonreís...
[D]No pierdo un día lejos de ti...
[A]Mi chance es h[E]oy...

[F#m]Miro tus ojos y me veo ahí...
[D]Aprovechando cada ocasión...
[A]Mi chance es h[E]oy...

[F#m]...Y hoy[G#m] lo de[C#m]más francamente no [A]importa...

{end_of_chorus}
{start_of_chorus: Estribillo (3x)}

{end_of_chorus}
